-- =====================================================
-- SEED: Vocabulary - Japanese (JLPT N5 → N1)
-- Nguồn tham khảo: JLPT official sample (N5–N1), Tanos.co.uk word lists,
-- jamsinclair/open-anki-jlpt-decks (CC0). Dữ liệu đã được rút gọn & dịch sang tiếng Việt.
-- =====================================================

SET NAMES utf8mb4;
SET @ja := (SELECT id FROM languages WHERE code='ja');
SET @vi := (SELECT id FROM languages WHERE code='vi');
SET @en := (SELECT id FROM languages WHERE code='en');

-- ========== JLPT N5 (≈100 từ cốt lõi) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, audio_url, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '私', 'わたし', 'watashi', 'PRON', 'N5', 'A1', NULL, 1, 'tôi', 'I, me'),
(@ja, '人', 'ひと', 'hito', 'NOUN', 'N5', 'A1', NULL, 2, 'người', 'person'),
(@ja, '今', 'いま', 'ima', 'NOUN', 'N5', 'A1', NULL, 3, 'bây giờ', 'now'),
(@ja, '日', 'ひ', 'hi', 'NOUN', 'N5', 'A1', NULL, 4, 'ngày, mặt trời', 'day, sun'),
(@ja, '月', 'つき', 'tsuki', 'NOUN', 'N5', 'A1', NULL, 5, 'tháng, mặt trăng', 'month, moon'),
(@ja, '年', 'とし', 'toshi', 'NOUN', 'N5', 'A1', NULL, 6, 'năm', 'year'),
(@ja, '時', 'とき', 'toki', 'NOUN', 'N5', 'A1', NULL, 7, 'thời gian, lúc', 'time'),
(@ja, '本', 'ほん', 'hon', 'NOUN', 'N5', 'A1', NULL, 8, 'sách', 'book'),
(@ja, '水', 'みず', 'mizu', 'NOUN', 'N5', 'A1', NULL, 9, 'nước', 'water'),
(@ja, '火', 'ひ', 'hi', 'NOUN', 'N5', 'A1', NULL, 10, 'lửa', 'fire'),
(@ja, '木', 'き', 'ki', 'NOUN', 'N5', 'A1', NULL, 11, 'cây, gỗ', 'tree, wood'),
(@ja, '金', 'かね', 'kane', 'NOUN', 'N5', 'A1', NULL, 12, 'tiền, vàng', 'money, gold'),
(@ja, '土', 'つち', 'tsuchi', 'NOUN', 'N5', 'A1', NULL, 13, 'đất', 'earth, soil'),
(@ja, '空', 'そら', 'sora', 'NOUN', 'N5', 'A1', NULL, 14, 'bầu trời', 'sky'),
(@ja, '山', 'やま', 'yama', 'NOUN', 'N5', 'A1', NULL, 15, 'núi', 'mountain'),
(@ja, '川', 'かわ', 'kawa', 'NOUN', 'N5', 'A1', NULL, 16, 'sông', 'river'),
(@ja, '海', 'うみ', 'umi', 'NOUN', 'N5', 'A1', NULL, 17, 'biển', 'sea'),
(@ja, '花', 'はな', 'hana', 'NOUN', 'N5', 'A1', NULL, 18, 'hoa', 'flower'),
(@ja, '魚', 'さかな', 'sakana', 'NOUN', 'N5', 'A1', NULL, 19, 'cá', 'fish'),
(@ja, '犬', 'いぬ', 'inu', 'NOUN', 'N5', 'A1', NULL, 20, 'chó', 'dog'),
(@ja, '猫', 'ねこ', 'neko', 'NOUN', 'N5', 'A1', NULL, 21, 'mèo', 'cat'),
(@ja, '父', 'ちち', 'chichi', 'NOUN', 'N5', 'A1', NULL, 22, 'bố (gia đình mình)', 'father'),
(@ja, '母', 'はは', 'haha', 'NOUN', 'N5', 'A1', NULL, 23, 'mẹ (gia đình mình)', 'mother'),
(@ja, '兄', 'あに', 'ani', 'NOUN', 'N5', 'A1', NULL, 24, 'anh trai', 'older brother'),
(@ja, '姉', 'あね', 'ane', 'NOUN', 'N5', 'A1', NULL, 25, 'chị gái', 'older sister'),
(@ja, '弟', 'おとうと', 'otouto', 'NOUN', 'N5', 'A1', NULL, 26, 'em trai', 'younger brother'),
(@ja, '妹', 'いもうと', 'imouto', 'NOUN', 'N5', 'A1', NULL, 27, 'em gái', 'younger sister'),
(@ja, '友達', 'ともだち', 'tomodachi', 'NOUN', 'N5', 'A1', NULL, 28, 'bạn bè', 'friend'),
(@ja, '先生', 'せんせい', 'sensei', 'NOUN', 'N5', 'A1', NULL, 29, 'giáo viên', 'teacher'),
(@ja, '学生', 'がくせい', 'gakusei', 'NOUN', 'N5', 'A1', NULL, 30, 'học sinh', 'student'),
(@ja, '学校', 'がっこう', 'gakkou', 'NOUN', 'N5', 'A1', NULL, 31, 'trường học', 'school'),
(@ja, '会社', 'かいしゃ', 'kaisha', 'NOUN', 'N5', 'A1', NULL, 32, 'công ty', 'company'),
(@ja, '家', 'いえ', 'ie', 'NOUN', 'N5', 'A1', NULL, 33, 'nhà', 'house'),
(@ja, '部屋', 'へや', 'heya', 'NOUN', 'N5', 'A1', NULL, 34, 'căn phòng', 'room'),
(@ja, '車', 'くるま', 'kuruma', 'NOUN', 'N5', 'A1', NULL, 35, 'xe ô tô', 'car'),
(@ja, '電車', 'でんしゃ', 'densha', 'NOUN', 'N5', 'A1', NULL, 36, 'tàu điện', 'train'),
(@ja, '駅', 'えき', 'eki', 'NOUN', 'N5', 'A1', NULL, 37, 'nhà ga', 'station'),
(@ja, '道', 'みち', 'michi', 'NOUN', 'N5', 'A1', NULL, 38, 'đường', 'road'),
(@ja, '町', 'まち', 'machi', 'NOUN', 'N5', 'A1', NULL, 39, 'phố', 'town'),
(@ja, '国', 'くに', 'kuni', 'NOUN', 'N5', 'A1', NULL, 40, 'đất nước', 'country'),
(@ja, '日本', 'にほん', 'nihon', 'NOUN', 'N5', 'A1', NULL, 41, 'Nhật Bản', 'Japan'),
(@ja, '英語', 'えいご', 'eigo', 'NOUN', 'N5', 'A1', NULL, 42, 'tiếng Anh', 'English'),
(@ja, '日本語', 'にほんご', 'nihongo', 'NOUN', 'N5', 'A1', NULL, 43, 'tiếng Nhật', 'Japanese language'),
(@ja, '名前', 'なまえ', 'namae', 'NOUN', 'N5', 'A1', NULL, 44, 'tên', 'name'),
(@ja, '食べる', 'たべる', 'taberu', 'VERB', 'N5', 'A1', NULL, 45, 'ăn', 'to eat'),
(@ja, '飲む', 'のむ', 'nomu', 'VERB', 'N5', 'A1', NULL, 46, 'uống', 'to drink'),
(@ja, '見る', 'みる', 'miru', 'VERB', 'N5', 'A1', NULL, 47, 'xem, nhìn', 'to see'),
(@ja, '聞く', 'きく', 'kiku', 'VERB', 'N5', 'A1', NULL, 48, 'nghe, hỏi', 'to listen, ask'),
(@ja, '行く', 'いく', 'iku', 'VERB', 'N5', 'A1', NULL, 49, 'đi', 'to go'),
(@ja, '来る', 'くる', 'kuru', 'VERB', 'N5', 'A1', NULL, 50, 'đến', 'to come'),
(@ja, '帰る', 'かえる', 'kaeru', 'VERB', 'N5', 'A1', NULL, 51, 'trở về', 'to return'),
(@ja, '話す', 'はなす', 'hanasu', 'VERB', 'N5', 'A1', NULL, 52, 'nói chuyện', 'to speak'),
(@ja, '読む', 'よむ', 'yomu', 'VERB', 'N5', 'A1', NULL, 53, 'đọc', 'to read'),
(@ja, '書く', 'かく', 'kaku', 'VERB', 'N5', 'A1', NULL, 54, 'viết', 'to write'),
(@ja, '買う', 'かう', 'kau', 'VERB', 'N5', 'A1', NULL, 55, 'mua', 'to buy'),
(@ja, '売る', 'うる', 'uru', 'VERB', 'N5', 'A1', NULL, 56, 'bán', 'to sell'),
(@ja, '寝る', 'ねる', 'neru', 'VERB', 'N5', 'A1', NULL, 57, 'ngủ', 'to sleep'),
(@ja, '起きる', 'おきる', 'okiru', 'VERB', 'N5', 'A1', NULL, 58, 'thức dậy', 'to wake up'),
(@ja, '勉強する', 'べんきょうする', 'benkyou suru', 'VERB', 'N5', 'A1', NULL, 59, 'học', 'to study'),
(@ja, '働く', 'はたらく', 'hataraku', 'VERB', 'N5', 'A1', NULL, 60, 'làm việc', 'to work'),
(@ja, '休む', 'やすむ', 'yasumu', 'VERB', 'N5', 'A1', NULL, 61, 'nghỉ', 'to rest'),
(@ja, '大きい', 'おおきい', 'ookii', 'ADJ', 'N5', 'A1', NULL, 62, 'to, lớn', 'big'),
(@ja, '小さい', 'ちいさい', 'chiisai', 'ADJ', 'N5', 'A1', NULL, 63, 'nhỏ', 'small'),
(@ja, '新しい', 'あたらしい', 'atarashii', 'ADJ', 'N5', 'A1', NULL, 64, 'mới', 'new'),
(@ja, '古い', 'ふるい', 'furui', 'ADJ', 'N5', 'A1', NULL, 65, 'cũ', 'old'),
(@ja, '高い', 'たかい', 'takai', 'ADJ', 'N5', 'A1', NULL, 66, 'cao, đắt', 'tall, expensive'),
(@ja, '安い', 'やすい', 'yasui', 'ADJ', 'N5', 'A1', NULL, 67, 'rẻ', 'cheap'),
(@ja, '低い', 'ひくい', 'hikui', 'ADJ', 'N5', 'A1', NULL, 68, 'thấp', 'low'),
(@ja, '長い', 'ながい', 'nagai', 'ADJ', 'N5', 'A1', NULL, 69, 'dài', 'long'),
(@ja, '短い', 'みじかい', 'mijikai', 'ADJ', 'N5', 'A1', NULL, 70, 'ngắn', 'short'),
(@ja, '美しい', 'うつくしい', 'utsukushii', 'ADJ', 'N5', 'A1', NULL, 71, 'đẹp', 'beautiful'),
(@ja, '面白い', 'おもしろい', 'omoshiroi', 'ADJ', 'N5', 'A1', NULL, 72, 'thú vị', 'interesting'),
(@ja, '楽しい', 'たのしい', 'tanoshii', 'ADJ', 'N5', 'A1', NULL, 73, 'vui', 'fun'),
(@ja, '難しい', 'むずかしい', 'muzukashii', 'ADJ', 'N5', 'A1', NULL, 74, 'khó', 'difficult'),
(@ja, '易しい', 'やさしい', 'yasashii', 'ADJ', 'N5', 'A1', NULL, 75, 'dễ', 'easy'),
(@ja, '熱い', 'あつい', 'atsui', 'ADJ', 'N5', 'A1', NULL, 76, 'nóng', 'hot'),
(@ja, '寒い', 'さむい', 'samui', 'ADJ', 'N5', 'A1', NULL, 77, 'lạnh', 'cold (weather)'),
(@ja, '美味しい', 'おいしい', 'oishii', 'ADJ', 'N5', 'A1', NULL, 78, 'ngon', 'delicious'),
(@ja, '一', 'いち', 'ichi', 'NUM', 'N5', 'A1', NULL, 79, 'một', 'one'),
(@ja, '二', 'に', 'ni', 'NUM', 'N5', 'A1', NULL, 80, 'hai', 'two'),
(@ja, '三', 'さん', 'san', 'NUM', 'N5', 'A1', NULL, 81, 'ba', 'three'),
(@ja, '四', 'よん', 'yon', 'NUM', 'N5', 'A1', NULL, 82, 'bốn', 'four'),
(@ja, '五', 'ご', 'go', 'NUM', 'N5', 'A1', NULL, 83, 'năm', 'five'),
(@ja, '六', 'ろく', 'roku', 'NUM', 'N5', 'A1', NULL, 84, 'sáu', 'six'),
(@ja, '七', 'なな', 'nana', 'NUM', 'N5', 'A1', NULL, 85, 'bảy', 'seven'),
(@ja, '八', 'はち', 'hachi', 'NUM', 'N5', 'A1', NULL, 86, 'tám', 'eight'),
(@ja, '九', 'きゅう', 'kyuu', 'NUM', 'N5', 'A1', NULL, 87, 'chín', 'nine'),
(@ja, '十', 'じゅう', 'juu', 'NUM', 'N5', 'A1', NULL, 88, 'mười', 'ten'),
(@ja, '百', 'ひゃく', 'hyaku', 'NUM', 'N5', 'A1', NULL, 89, 'một trăm', 'hundred'),
(@ja, '千', 'せん', 'sen', 'NUM', 'N5', 'A1', NULL, 90, 'một nghìn', 'thousand'),
(@ja, '万', 'まん', 'man', 'NUM', 'N5', 'A1', NULL, 91, 'mười nghìn', 'ten thousand'),
(@ja, 'これ', 'これ', 'kore', 'PRON', 'N5', 'A1', NULL, 92, 'cái này', 'this'),
(@ja, 'それ', 'それ', 'sore', 'PRON', 'N5', 'A1', NULL, 93, 'cái đó', 'that'),
(@ja, 'あれ', 'あれ', 'are', 'PRON', 'N5', 'A1', NULL, 94, 'cái kia', 'that over there'),
(@ja, 'はい', 'はい', 'hai', 'INTJ', 'N5', 'A1', NULL, 95, 'vâng, có', 'yes'),
(@ja, 'いいえ', 'いいえ', 'iie', 'INTJ', 'N5', 'A1', NULL, 96, 'không', 'no'),
(@ja, 'すみません', 'すみません', 'sumimasen', 'PHRASE', 'N5', 'A1', NULL, 97, 'xin lỗi / cảm ơn', 'excuse me, sorry'),
(@ja, 'ありがとう', 'ありがとう', 'arigatou', 'PHRASE', 'N5', 'A1', NULL, 98, 'cảm ơn', 'thank you'),
(@ja, 'おはよう', 'おはよう', 'ohayou', 'PHRASE', 'N5', 'A1', NULL, 99, 'chào buổi sáng', 'good morning'),
(@ja, 'こんにちは', 'こんにちは', 'konnichiwa', 'PHRASE', 'N5', 'A1', NULL, 100, 'xin chào', 'hello');

-- ========== JLPT N4 (≈80 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '世界', 'せかい', 'sekai', 'NOUN', 'N4', 'A2', 200, 'thế giới', 'world'),
(@ja, '社会', 'しゃかい', 'shakai', 'NOUN', 'N4', 'A2', 201, 'xã hội', 'society'),
(@ja, '経済', 'けいざい', 'keizai', 'NOUN', 'N4', 'A2', 202, 'kinh tế', 'economy'),
(@ja, '文化', 'ぶんか', 'bunka', 'NOUN', 'N4', 'A2', 203, 'văn hóa', 'culture'),
(@ja, '歴史', 'れきし', 'rekishi', 'NOUN', 'N4', 'A2', 204, 'lịch sử', 'history'),
(@ja, '政治', 'せいじ', 'seiji', 'NOUN', 'N4', 'A2', 205, 'chính trị', 'politics'),
(@ja, '法律', 'ほうりつ', 'houritsu', 'NOUN', 'N4', 'A2', 206, 'pháp luật', 'law'),
(@ja, '科学', 'かがく', 'kagaku', 'NOUN', 'N4', 'A2', 207, 'khoa học', 'science'),
(@ja, '技術', 'ぎじゅつ', 'gijutsu', 'NOUN', 'N4', 'A2', 208, 'kỹ thuật', 'technology'),
(@ja, '研究', 'けんきゅう', 'kenkyuu', 'NOUN', 'N4', 'A2', 209, 'nghiên cứu', 'research'),
(@ja, '計画', 'けいかく', 'keikaku', 'NOUN', 'N4', 'A2', 210, 'kế hoạch', 'plan'),
(@ja, '会議', 'かいぎ', 'kaigi', 'NOUN', 'N4', 'A2', 211, 'cuộc họp', 'meeting'),
(@ja, '質問', 'しつもん', 'shitsumon', 'NOUN', 'N4', 'A2', 212, 'câu hỏi', 'question'),
(@ja, '答え', 'こたえ', 'kotae', 'NOUN', 'N4', 'A2', 213, 'câu trả lời', 'answer'),
(@ja, '意見', 'いけん', 'iken', 'NOUN', 'N4', 'A2', 214, 'ý kiến', 'opinion'),
(@ja, '気持ち', 'きもち', 'kimochi', 'NOUN', 'N4', 'A2', 215, 'tâm trạng', 'feeling'),
(@ja, '考える', 'かんがえる', 'kangaeru', 'VERB', 'N4', 'A2', 216, 'suy nghĩ', 'to think'),
(@ja, '答える', 'こたえる', 'kotaeru', 'VERB', 'N4', 'A2', 217, 'trả lời', 'to answer'),
(@ja, '伝える', 'つたえる', 'tsutaeru', 'VERB', 'N4', 'A2', 218, 'truyền đạt', 'to convey'),
(@ja, '使う', 'つかう', 'tsukau', 'VERB', 'N4', 'A2', 219, 'sử dụng', 'to use'),
(@ja, '作る', 'つくる', 'tsukuru', 'VERB', 'N4', 'A2', 220, 'làm, tạo', 'to make'),
(@ja, '直す', 'なおす', 'naosu', 'VERB', 'N4', 'A2', 221, 'sửa', 'to fix'),
(@ja, '始める', 'はじめる', 'hajimeru', 'VERB', 'N4', 'A2', 222, 'bắt đầu', 'to begin'),
(@ja, '終わる', 'おわる', 'owaru', 'VERB', 'N4', 'A2', 223, 'kết thúc', 'to end'),
(@ja, '続く', 'つづく', 'tsuduku', 'VERB', 'N4', 'A2', 224, 'tiếp tục', 'to continue'),
(@ja, '止まる', 'とまる', 'tomaru', 'VERB', 'N4', 'A2', 225, 'dừng lại', 'to stop'),
(@ja, '走る', 'はしる', 'hashiru', 'VERB', 'N4', 'A2', 226, 'chạy', 'to run'),
(@ja, '歩く', 'あるく', 'aruku', 'VERB', 'N4', 'A2', 227, 'đi bộ', 'to walk'),
(@ja, '泳ぐ', 'およぐ', 'oyogu', 'VERB', 'N4', 'A2', 228, 'bơi', 'to swim'),
(@ja, '飛ぶ', 'とぶ', 'tobu', 'VERB', 'N4', 'A2', 229, 'bay', 'to fly'),
(@ja, '便利', 'べんり', 'benri', 'ADJ', 'N4', 'A2', 230, 'tiện lợi', 'convenient'),
(@ja, '不便', 'ふべん', 'fuben', 'ADJ', 'N4', 'A2', 231, 'bất tiện', 'inconvenient'),
(@ja, '簡単', 'かんたん', 'kantan', 'ADJ', 'N4', 'A2', 232, 'đơn giản', 'simple'),
(@ja, '複雑', 'ふくざつ', 'fukuzatsu', 'ADJ', 'N4', 'A2', 233, 'phức tạp', 'complex'),
(@ja, '安全', 'あんぜん', 'anzen', 'ADJ', 'N4', 'A2', 234, 'an toàn', 'safe'),
(@ja, '危険', 'きけん', 'kiken', 'ADJ', 'N4', 'A2', 235, 'nguy hiểm', 'dangerous'),
(@ja, '元気', 'げんき', 'genki', 'ADJ', 'N4', 'A2', 236, 'khỏe mạnh', 'healthy, energetic'),
(@ja, '有名', 'ゆうめい', 'yuumei', 'ADJ', 'N4', 'A2', 237, 'nổi tiếng', 'famous'),
(@ja, '親切', 'しんせつ', 'shinsetsu', 'ADJ', 'N4', 'A2', 238, 'tử tế', 'kind'),
(@ja, '大切', 'たいせつ', 'taisetsu', 'ADJ', 'N4', 'A2', 239, 'quan trọng', 'important'),
(@ja, '必要', 'ひつよう', 'hitsuyou', 'ADJ', 'N4', 'A2', 240, 'cần thiết', 'necessary'),
(@ja, '不思議', 'ふしぎ', 'fushigi', 'ADJ', 'N4', 'A2', 241, 'kỳ lạ', 'mysterious'),
(@ja, '空港', 'くうこう', 'kuukou', 'NOUN', 'N4', 'A2', 242, 'sân bay', 'airport'),
(@ja, '飛行機', 'ひこうき', 'hikouki', 'NOUN', 'N4', 'A2', 243, 'máy bay', 'airplane'),
(@ja, '地下鉄', 'ちかてつ', 'chikatetsu', 'NOUN', 'N4', 'A2', 244, 'tàu điện ngầm', 'subway'),
(@ja, '病院', 'びょういん', 'byouin', 'NOUN', 'N4', 'A2', 245, 'bệnh viện', 'hospital'),
(@ja, '医者', 'いしゃ', 'isha', 'NOUN', 'N4', 'A2', 246, 'bác sĩ', 'doctor'),
(@ja, '薬', 'くすり', 'kusuri', 'NOUN', 'N4', 'A2', 247, 'thuốc', 'medicine'),
(@ja, '銀行', 'ぎんこう', 'ginkou', 'NOUN', 'N4', 'A2', 248, 'ngân hàng', 'bank'),
(@ja, '郵便局', 'ゆうびんきょく', 'yuubinkyoku', 'NOUN', 'N4', 'A2', 249, 'bưu điện', 'post office'),
(@ja, '図書館', 'としょかん', 'toshokan', 'NOUN', 'N4', 'A2', 250, 'thư viện', 'library'),
(@ja, '公園', 'こうえん', 'kouen', 'NOUN', 'N4', 'A2', 251, 'công viên', 'park'),
(@ja, '映画', 'えいが', 'eiga', 'NOUN', 'N4', 'A2', 252, 'phim', 'movie'),
(@ja, '音楽', 'おんがく', 'ongaku', 'NOUN', 'N4', 'A2', 253, 'âm nhạc', 'music'),
(@ja, '料理', 'りょうり', 'ryouri', 'NOUN', 'N4', 'A2', 254, 'món ăn, nấu ăn', 'cooking'),
(@ja, 'お茶', 'おちゃ', 'ocha', 'NOUN', 'N4', 'A2', 255, 'trà', 'tea'),
(@ja, 'コーヒー', 'こーひー', 'koohii', 'NOUN', 'N4', 'A2', 256, 'cà phê', 'coffee'),
(@ja, 'パン', 'ぱん', 'pan', 'NOUN', 'N4', 'A2', 257, 'bánh mì', 'bread'),
(@ja, 'お米', 'おこめ', 'okome', 'NOUN', 'N4', 'A2', 258, 'gạo', 'rice (uncooked)'),
(@ja, '果物', 'くだもの', 'kudamono', 'NOUN', 'N4', 'A2', 259, 'trái cây', 'fruit'),
(@ja, '野菜', 'やさい', 'yasai', 'NOUN', 'N4', 'A2', 260, 'rau củ', 'vegetables'),
(@ja, '肉', 'にく', 'niku', 'NOUN', 'N4', 'A2', 261, 'thịt', 'meat'),
(@ja, '昨日', 'きのう', 'kinou', 'NOUN', 'N4', 'A2', 262, 'hôm qua', 'yesterday'),
(@ja, '今日', 'きょう', 'kyou', 'NOUN', 'N4', 'A2', 263, 'hôm nay', 'today'),
(@ja, '明日', 'あした', 'ashita', 'NOUN', 'N4', 'A2', 264, 'ngày mai', 'tomorrow'),
(@ja, '来週', 'らいしゅう', 'raishuu', 'NOUN', 'N4', 'A2', 265, 'tuần sau', 'next week'),
(@ja, '先週', 'せんしゅう', 'senshuu', 'NOUN', 'N4', 'A2', 266, 'tuần trước', 'last week'),
(@ja, '今月', 'こんげつ', 'kongetsu', 'NOUN', 'N4', 'A2', 267, 'tháng này', 'this month'),
(@ja, '来月', 'らいげつ', 'raigetsu', 'NOUN', 'N4', 'A2', 268, 'tháng sau', 'next month'),
(@ja, '今年', 'ことし', 'kotoshi', 'NOUN', 'N4', 'A2', 269, 'năm nay', 'this year'),
(@ja, '春', 'はる', 'haru', 'NOUN', 'N4', 'A2', 270, 'mùa xuân', 'spring'),
(@ja, '夏', 'なつ', 'natsu', 'NOUN', 'N4', 'A2', 271, 'mùa hè', 'summer'),
(@ja, '秋', 'あき', 'aki', 'NOUN', 'N4', 'A2', 272, 'mùa thu', 'autumn'),
(@ja, '冬', 'ふゆ', 'fuyu', 'NOUN', 'N4', 'A2', 273, 'mùa đông', 'winter'),
(@ja, '天気', 'てんき', 'tenki', 'NOUN', 'N4', 'A2', 274, 'thời tiết', 'weather'),
(@ja, '雨', 'あめ', 'ame', 'NOUN', 'N4', 'A2', 275, 'mưa', 'rain'),
(@ja, '雪', 'ゆき', 'yuki', 'NOUN', 'N4', 'A2', 276, 'tuyết', 'snow'),
(@ja, '風', 'かぜ', 'kaze', 'NOUN', 'N4', 'A2', 277, 'gió', 'wind'),
(@ja, '雲', 'くも', 'kumo', 'NOUN', 'N4', 'A2', 278, 'mây', 'cloud'),
(@ja, '夢', 'ゆめ', 'yume', 'NOUN', 'N4', 'A2', 279, 'giấc mơ', 'dream');

-- ========== JLPT N3 (≈70 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '影響', 'えいきょう', 'eikyou', 'NOUN', 'N3', 'B1', 400, 'ảnh hưởng', 'influence'),
(@ja, '関係', 'かんけい', 'kankei', 'NOUN', 'N3', 'B1', 401, 'mối quan hệ', 'relationship'),
(@ja, '結果', 'けっか', 'kekka', 'NOUN', 'N3', 'B1', 402, 'kết quả', 'result'),
(@ja, '原因', 'げんいん', 'genin', 'NOUN', 'N3', 'B1', 403, 'nguyên nhân', 'cause'),
(@ja, '理由', 'りゆう', 'riyuu', 'NOUN', 'N3', 'B1', 404, 'lý do', 'reason'),
(@ja, '目的', 'もくてき', 'mokuteki', 'NOUN', 'N3', 'B1', 405, 'mục đích', 'purpose'),
(@ja, '内容', 'ないよう', 'naiyou', 'NOUN', 'N3', 'B1', 406, 'nội dung', 'content'),
(@ja, '情報', 'じょうほう', 'jouhou', 'NOUN', 'N3', 'B1', 407, 'thông tin', 'information'),
(@ja, '意味', 'いみ', 'imi', 'NOUN', 'N3', 'B1', 408, 'ý nghĩa', 'meaning'),
(@ja, '希望', 'きぼう', 'kibou', 'NOUN', 'N3', 'B1', 409, 'hy vọng', 'hope'),
(@ja, '感情', 'かんじょう', 'kanjou', 'NOUN', 'N3', 'B1', 410, 'cảm xúc', 'emotion'),
(@ja, '記憶', 'きおく', 'kioku', 'NOUN', 'N3', 'B1', 411, 'ký ức', 'memory'),
(@ja, '想像', 'そうぞう', 'souzou', 'NOUN', 'N3', 'B1', 412, 'tưởng tượng', 'imagination'),
(@ja, '経験', 'けいけん', 'keiken', 'NOUN', 'N3', 'B1', 413, 'kinh nghiệm', 'experience'),
(@ja, '能力', 'のうりょく', 'nouryoku', 'NOUN', 'N3', 'B1', 414, 'năng lực', 'ability'),
(@ja, '才能', 'さいのう', 'sainou', 'NOUN', 'N3', 'B1', 415, 'tài năng', 'talent'),
(@ja, '知識', 'ちしき', 'chishiki', 'NOUN', 'N3', 'B1', 416, 'kiến thức', 'knowledge'),
(@ja, '伝統', 'でんとう', 'dentou', 'NOUN', 'N3', 'B1', 417, 'truyền thống', 'tradition'),
(@ja, '習慣', 'しゅうかん', 'shuukan', 'NOUN', 'N3', 'B1', 418, 'thói quen', 'habit'),
(@ja, '生活', 'せいかつ', 'seikatsu', 'NOUN', 'N3', 'B1', 419, 'cuộc sống', 'life'),
(@ja, '環境', 'かんきょう', 'kankyou', 'NOUN', 'N3', 'B1', 420, 'môi trường', 'environment'),
(@ja, '自然', 'しぜん', 'shizen', 'NOUN', 'N3', 'B1', 421, 'tự nhiên', 'nature'),
(@ja, '人口', 'じんこう', 'jinkou', 'NOUN', 'N3', 'B1', 422, 'dân số', 'population'),
(@ja, '産業', 'さんぎょう', 'sangyou', 'NOUN', 'N3', 'B1', 423, 'công nghiệp', 'industry'),
(@ja, '商品', 'しょうひん', 'shouhin', 'NOUN', 'N3', 'B1', 424, 'sản phẩm', 'product'),
(@ja, '価格', 'かかく', 'kakaku', 'NOUN', 'N3', 'B1', 425, 'giá cả', 'price'),
(@ja, '比較', 'ひかく', 'hikaku', 'NOUN', 'N3', 'B1', 426, 'so sánh', 'comparison'),
(@ja, '賛成', 'さんせい', 'sansei', 'NOUN', 'N3', 'B1', 427, 'tán thành', 'agreement'),
(@ja, '反対', 'はんたい', 'hantai', 'NOUN', 'N3', 'B1', 428, 'phản đối', 'opposition'),
(@ja, '解決', 'かいけつ', 'kaiketsu', 'NOUN', 'N3', 'B1', 429, 'giải quyết', 'solution'),
(@ja, '増える', 'ふえる', 'fueru', 'VERB', 'N3', 'B1', 430, 'tăng lên', 'to increase'),
(@ja, '減る', 'へる', 'heru', 'VERB', 'N3', 'B1', 431, 'giảm đi', 'to decrease'),
(@ja, '変わる', 'かわる', 'kawaru', 'VERB', 'N3', 'B1', 432, 'thay đổi', 'to change'),
(@ja, '比べる', 'くらべる', 'kuraberu', 'VERB', 'N3', 'B1', 433, 'so sánh', 'to compare'),
(@ja, '選ぶ', 'えらぶ', 'erabu', 'VERB', 'N3', 'B1', 434, 'lựa chọn', 'to choose'),
(@ja, '決める', 'きめる', 'kimeru', 'VERB', 'N3', 'B1', 435, 'quyết định', 'to decide'),
(@ja, '守る', 'まもる', 'mamoru', 'VERB', 'N3', 'B1', 436, 'bảo vệ, giữ', 'to protect'),
(@ja, '認める', 'みとめる', 'mitomeru', 'VERB', 'N3', 'B1', 437, 'thừa nhận', 'to admit'),
(@ja, '勧める', 'すすめる', 'susumeru', 'VERB', 'N3', 'B1', 438, 'khuyến khích', 'to recommend'),
(@ja, '断る', 'ことわる', 'kotowaru', 'VERB', 'N3', 'B1', 439, 'từ chối', 'to decline'),
(@ja, '支払う', 'しはらう', 'shiharau', 'VERB', 'N3', 'B1', 440, 'thanh toán', 'to pay'),
(@ja, '届ける', 'とどける', 'todokeru', 'VERB', 'N3', 'B1', 441, 'giao đến', 'to deliver'),
(@ja, '預ける', 'あずける', 'azukeru', 'VERB', 'N3', 'B1', 442, 'gửi (đồ)', 'to deposit'),
(@ja, '訪ねる', 'たずねる', 'tazuneru', 'VERB', 'N3', 'B1', 443, 'thăm hỏi', 'to visit'),
(@ja, '迎える', 'むかえる', 'mukaeru', 'VERB', 'N3', 'B1', 444, 'đón tiếp', 'to welcome'),
(@ja, '見送る', 'みおくる', 'miokuru', 'VERB', 'N3', 'B1', 445, 'tiễn', 'to see off'),
(@ja, '間違える', 'まちがえる', 'machigaeru', 'VERB', 'N3', 'B1', 446, 'nhầm lẫn', 'to make mistake'),
(@ja, '正しい', 'ただしい', 'tadashii', 'ADJ', 'N3', 'B1', 447, 'đúng đắn', 'correct'),
(@ja, '優しい', 'やさしい', 'yasashii', 'ADJ', 'N3', 'B1', 448, 'dịu dàng', 'gentle'),
(@ja, '厳しい', 'きびしい', 'kibishii', 'ADJ', 'N3', 'B1', 449, 'nghiêm khắc', 'strict'),
(@ja, '激しい', 'はげしい', 'hageshii', 'ADJ', 'N3', 'B1', 450, 'mãnh liệt', 'intense'),
(@ja, '寂しい', 'さびしい', 'sabishii', 'ADJ', 'N3', 'B1', 451, 'cô đơn', 'lonely'),
(@ja, '恥ずかしい', 'はずかしい', 'hazukashii', 'ADJ', 'N3', 'B1', 452, 'xấu hổ', 'embarrassing'),
(@ja, '申し訳ない', 'もうしわけない', 'moushiwakenai', 'PHRASE', 'N3', 'B1', 453, 'rất xin lỗi', 'sorry (formal)'),
(@ja, '突然', 'とつぜん', 'totsuzen', 'ADV', 'N3', 'B1', 454, 'đột nhiên', 'suddenly'),
(@ja, '結局', 'けっきょく', 'kekkyoku', 'ADV', 'N3', 'B1', 455, 'cuối cùng', 'in the end'),
(@ja, '最近', 'さいきん', 'saikin', 'ADV', 'N3', 'B1', 456, 'gần đây', 'recently'),
(@ja, '将来', 'しょうらい', 'shourai', 'NOUN', 'N3', 'B1', 457, 'tương lai', 'future'),
(@ja, '過去', 'かこ', 'kako', 'NOUN', 'N3', 'B1', 458, 'quá khứ', 'past'),
(@ja, '現在', 'げんざい', 'genzai', 'NOUN', 'N3', 'B1', 459, 'hiện tại', 'present'),
(@ja, '一生懸命', 'いっしょうけんめい', 'isshoukenmei', 'ADV', 'N3', 'B1', 460, 'hết sức', 'very hard'),
(@ja, '丁寧', 'ていねい', 'teinei', 'ADJ', 'N3', 'B1', 461, 'lịch sự, cẩn thận', 'polite'),
(@ja, '失敗', 'しっぱい', 'shippai', 'NOUN', 'N3', 'B1', 462, 'thất bại', 'failure'),
(@ja, '成功', 'せいこう', 'seikou', 'NOUN', 'N3', 'B1', 463, 'thành công', 'success'),
(@ja, '努力', 'どりょく', 'doryoku', 'NOUN', 'N3', 'B1', 464, 'nỗ lực', 'effort'),
(@ja, '責任', 'せきにん', 'sekinin', 'NOUN', 'N3', 'B1', 465, 'trách nhiệm', 'responsibility'),
(@ja, '機会', 'きかい', 'kikai', 'NOUN', 'N3', 'B1', 466, 'cơ hội', 'opportunity'),
(@ja, '事情', 'じじょう', 'jijou', 'NOUN', 'N3', 'B1', 467, 'tình hình', 'circumstances'),
(@ja, '状況', 'じょうきょう', 'joukyou', 'NOUN', 'N3', 'B1', 468, 'tình huống', 'situation'),
(@ja, '進歩', 'しんぽ', 'shinpo', 'NOUN', 'N3', 'B1', 469, 'tiến bộ', 'progress'),
(@ja, '発展', 'はってん', 'hatten', 'NOUN', 'N3', 'B1', 470, 'phát triển', 'development');

-- ========== JLPT N2 (≈40 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '抽象', 'ちゅうしょう', 'chuushou', 'NOUN', 'N2', 'B2', 600, 'trừu tượng', 'abstract'),
(@ja, '具体', 'ぐたい', 'gutai', 'NOUN', 'N2', 'B2', 601, 'cụ thể', 'concrete'),
(@ja, '概念', 'がいねん', 'gainen', 'NOUN', 'N2', 'B2', 602, 'khái niệm', 'concept'),
(@ja, '意義', 'いぎ', 'igi', 'NOUN', 'N2', 'B2', 603, 'ý nghĩa, giá trị', 'significance'),
(@ja, '本質', 'ほんしつ', 'honshitsu', 'NOUN', 'N2', 'B2', 604, 'bản chất', 'essence'),
(@ja, '価値', 'かち', 'kachi', 'NOUN', 'N2', 'B2', 605, 'giá trị', 'value'),
(@ja, '効果', 'こうか', 'kouka', 'NOUN', 'N2', 'B2', 606, 'hiệu quả', 'effect'),
(@ja, '効率', 'こうりつ', 'kouritsu', 'NOUN', 'N2', 'B2', 607, 'hiệu suất', 'efficiency'),
(@ja, '構造', 'こうぞう', 'kouzou', 'NOUN', 'N2', 'B2', 608, 'cấu trúc', 'structure'),
(@ja, '機能', 'きのう', 'kinou', 'NOUN', 'N2', 'B2', 609, 'chức năng', 'function'),
(@ja, '需要', 'じゅよう', 'juyou', 'NOUN', 'N2', 'B2', 610, 'nhu cầu', 'demand'),
(@ja, '供給', 'きょうきゅう', 'kyoukyuu', 'NOUN', 'N2', 'B2', 611, 'cung cấp', 'supply'),
(@ja, '輸出', 'ゆしゅつ', 'yushutsu', 'NOUN', 'N2', 'B2', 612, 'xuất khẩu', 'export'),
(@ja, '輸入', 'ゆにゅう', 'yunyuu', 'NOUN', 'N2', 'B2', 613, 'nhập khẩu', 'import'),
(@ja, '製品', 'せいひん', 'seihin', 'NOUN', 'N2', 'B2', 614, 'sản phẩm chế tạo', 'manufactured product'),
(@ja, '従業員', 'じゅうぎょういん', 'juugyouin', 'NOUN', 'N2', 'B2', 615, 'nhân viên', 'employee'),
(@ja, '上司', 'じょうし', 'joushi', 'NOUN', 'N2', 'B2', 616, 'cấp trên', 'superior'),
(@ja, '部下', 'ぶか', 'buka', 'NOUN', 'N2', 'B2', 617, 'cấp dưới', 'subordinate'),
(@ja, '同僚', 'どうりょう', 'douryou', 'NOUN', 'N2', 'B2', 618, 'đồng nghiệp', 'colleague'),
(@ja, '取引', 'とりひき', 'torihiki', 'NOUN', 'N2', 'B2', 619, 'giao dịch', 'transaction'),
(@ja, '契約', 'けいやく', 'keiyaku', 'NOUN', 'N2', 'B2', 620, 'hợp đồng', 'contract'),
(@ja, '条件', 'じょうけん', 'jouken', 'NOUN', 'N2', 'B2', 621, 'điều kiện', 'condition'),
(@ja, '提案', 'ていあん', 'teian', 'NOUN', 'N2', 'B2', 622, 'đề xuất', 'proposal'),
(@ja, '判断', 'はんだん', 'handan', 'NOUN', 'N2', 'B2', 623, 'phán đoán', 'judgment'),
(@ja, '評価', 'ひょうか', 'hyouka', 'NOUN', 'N2', 'B2', 624, 'đánh giá', 'evaluation'),
(@ja, '改善', 'かいぜん', 'kaizen', 'NOUN', 'N2', 'B2', 625, 'cải thiện', 'improvement'),
(@ja, '改革', 'かいかく', 'kaikaku', 'NOUN', 'N2', 'B2', 626, 'cải cách', 'reform'),
(@ja, '促進', 'そくしん', 'sokushin', 'NOUN', 'N2', 'B2', 627, 'thúc đẩy', 'promotion'),
(@ja, '実施', 'じっし', 'jisshi', 'NOUN', 'N2', 'B2', 628, 'thực thi', 'implementation'),
(@ja, '達成', 'たっせい', 'tassei', 'NOUN', 'N2', 'B2', 629, 'đạt được', 'achievement'),
(@ja, '抑える', 'おさえる', 'osaeru', 'VERB', 'N2', 'B2', 630, 'kiềm chế', 'to suppress'),
(@ja, '逃げる', 'にげる', 'nigeru', 'VERB', 'N2', 'B2', 631, 'chạy trốn', 'to escape'),
(@ja, '溶ける', 'とける', 'tokeru', 'VERB', 'N2', 'B2', 632, 'tan chảy', 'to melt'),
(@ja, '凍る', 'こおる', 'kooru', 'VERB', 'N2', 'B2', 633, 'đóng băng', 'to freeze'),
(@ja, '燃える', 'もえる', 'moeru', 'VERB', 'N2', 'B2', 634, 'cháy', 'to burn'),
(@ja, '濡れる', 'ぬれる', 'nureru', 'VERB', 'N2', 'B2', 635, 'bị ướt', 'to get wet'),
(@ja, '汚れる', 'よごれる', 'yogoreru', 'VERB', 'N2', 'B2', 636, 'bị bẩn', 'to get dirty'),
(@ja, '懐かしい', 'なつかしい', 'natsukashii', 'ADJ', 'N2', 'B2', 637, 'gợi nhớ', 'nostalgic'),
(@ja, '羨ましい', 'うらやましい', 'urayamashii', 'ADJ', 'N2', 'B2', 638, 'ghen tị', 'envious'),
(@ja, '相当', 'そうとう', 'soutou', 'ADV', 'N2', 'B2', 639, 'tương đương', 'considerably');

-- ========== JLPT N1 (≈25 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '滞在', 'たいざい', 'taizai', 'NOUN', 'N1', 'C1', 800, 'lưu trú', 'stay (lodging)'),
(@ja, '把握', 'はあく', 'haaku', 'NOUN', 'N1', 'C1', 801, 'nắm bắt', 'grasp, comprehension'),
(@ja, '貢献', 'こうけん', 'kouken', 'NOUN', 'N1', 'C1', 802, 'cống hiến', 'contribution'),
(@ja, '矛盾', 'むじゅん', 'mujun', 'NOUN', 'N1', 'C1', 803, 'mâu thuẫn', 'contradiction'),
(@ja, '葛藤', 'かっとう', 'kattou', 'NOUN', 'N1', 'C1', 804, 'xung đột nội tâm', 'conflict'),
(@ja, '皮肉', 'ひにく', 'hiniku', 'NOUN', 'N1', 'C1', 805, 'mỉa mai', 'sarcasm, irony'),
(@ja, '偏見', 'へんけん', 'henken', 'NOUN', 'N1', 'C1', 806, 'thành kiến', 'prejudice'),
(@ja, '配慮', 'はいりょ', 'hairyo', 'NOUN', 'N1', 'C1', 807, 'sự quan tâm', 'consideration'),
(@ja, '慎重', 'しんちょう', 'shinchou', 'ADJ', 'N1', 'C1', 808, 'thận trọng', 'careful'),
(@ja, '頻繁', 'ひんぱん', 'hinpan', 'ADJ', 'N1', 'C1', 809, 'thường xuyên', 'frequent'),
(@ja, '巧妙', 'こうみょう', 'koumyou', 'ADJ', 'N1', 'C1', 810, 'khéo léo', 'skillful'),
(@ja, '微妙', 'びみょう', 'bimyou', 'ADJ', 'N1', 'C1', 811, 'tinh tế', 'subtle, delicate'),
(@ja, '曖昧', 'あいまい', 'aimai', 'ADJ', 'N1', 'C1', 812, 'mơ hồ', 'ambiguous'),
(@ja, '率直', 'そっちょく', 'socchoku', 'ADJ', 'N1', 'C1', 813, 'thẳng thắn', 'frank'),
(@ja, '謙虚', 'けんきょ', 'kenkyo', 'ADJ', 'N1', 'C1', 814, 'khiêm tốn', 'humble'),
(@ja, '傲慢', 'ごうまん', 'gouman', 'ADJ', 'N1', 'C1', 815, 'kiêu ngạo', 'arrogant'),
(@ja, '譲る', 'ゆずる', 'yuzuru', 'VERB', 'N1', 'C1', 816, 'nhường', 'to yield'),
(@ja, '怠る', 'おこたる', 'okotaru', 'VERB', 'N1', 'C1', 817, 'lơ là', 'to neglect'),
(@ja, '陥る', 'おちいる', 'ochiiru', 'VERB', 'N1', 'C1', 818, 'rơi vào', 'to fall into'),
(@ja, '潜む', 'ひそむ', 'hisomu', 'VERB', 'N1', 'C1', 819, 'ẩn chứa', 'to lurk'),
(@ja, '滞る', 'とどこおる', 'todokooru', 'VERB', 'N1', 'C1', 820, 'đình trệ', 'to be delayed'),
(@ja, '促す', 'うながす', 'unagasu', 'VERB', 'N1', 'C1', 821, 'thúc giục', 'to urge'),
(@ja, '阻む', 'はばむ', 'habamu', 'VERB', 'N1', 'C1', 822, 'cản trở', 'to obstruct'),
(@ja, '隔てる', 'へだてる', 'hedateru', 'VERB', 'N1', 'C1', 823, 'cách ly', 'to separate'),
(@ja, '忌々しい', 'いまいましい', 'imaimashii', 'ADJ', 'N1', 'C1', 824, 'phiền phức', 'annoying');

-- ----- Câu ví dụ cho một số từ N5 (Shadowing) -----
INSERT INTO word_examples (word_id, sentence, reading, translation, level_code, source) VALUES
((SELECT id FROM words WHERE `text`='食べる' AND language_id=@ja LIMIT 1),
 '私は朝ご飯を食べます。', 'わたしはあさごはんをたべます。', 'Tôi ăn bữa sáng.', 'N5', 'curated'),
((SELECT id FROM words WHERE `text`='食べる' AND language_id=@ja LIMIT 1),
 '何を食べたいですか。', 'なにをたべたいですか。', 'Bạn muốn ăn gì?', 'N5', 'curated'),
((SELECT id FROM words WHERE `text`='飲む' AND language_id=@ja LIMIT 1),
 'コーヒーを飲みます。', 'こーひーをのみます。', 'Tôi uống cà phê.', 'N5', 'curated'),
((SELECT id FROM words WHERE `text`='行く' AND language_id=@ja LIMIT 1),
 '明日学校へ行きます。', 'あしたがっこうへいきます。', 'Ngày mai tôi sẽ đến trường.', 'N5', 'curated'),
((SELECT id FROM words WHERE `text`='本' AND language_id=@ja LIMIT 1),
 'この本はとても面白いです。', 'このほんはとてもおもしろいです。', 'Cuốn sách này rất thú vị.', 'N5', 'curated'),
((SELECT id FROM words WHERE `text`='天気' AND language_id=@ja LIMIT 1),
 '今日は天気がいいです。', 'きょうはてんきがいいです。', 'Hôm nay thời tiết đẹp.', 'N4', 'curated'),
((SELECT id FROM words WHERE `text`='経験' AND language_id=@ja LIMIT 1),
 '日本で働いた経験があります。', 'にほんではたらいたけいけんがあります。', 'Tôi có kinh nghiệm làm việc ở Nhật.', 'N3', 'curated'),
((SELECT id FROM words WHERE `text`='契約' AND language_id=@ja LIMIT 1),
 '来週、契約に署名する予定です。', 'らいしゅう、けいやくにしょめいするよていです。', 'Tuần sau tôi dự định ký hợp đồng.', 'N2', 'curated'),
((SELECT id FROM words WHERE `text`='貢献' AND language_id=@ja LIMIT 1),
 '彼は会社の発展に大きな貢献をした。', 'かれはかいしゃのはってんにおおきなこうけんをした。', 'Anh ấy đã đóng góp lớn cho sự phát triển của công ty.', 'N1', 'curated');
