-- =====================================================
-- SEED: Vocabulary - Chinese (HSK 1 → HSK 6)
-- Nguồn tham khảo: drkameleon/complete-hsk-vocabulary (CC0/MIT),
-- ivankra/hsk30, oetia/new-hsk-csv. Dữ liệu rút gọn.
-- =====================================================

SET NAMES utf8mb4;
SET @zh := (SELECT id FROM languages WHERE code='zh');
SET @vi := (SELECT id FROM languages WHERE code='vi');

-- ========== HSK 1 (≈60 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '我', 'wǒ', 'wo', 'PRON', 'HSK1', 'A1', 1, 'tôi', 'I, me'),
(@zh, '你', 'nǐ', 'ni', 'PRON', 'HSK1', 'A1', 2, 'bạn', 'you'),
(@zh, '他', 'tā', 'ta', 'PRON', 'HSK1', 'A1', 3, 'anh ấy', 'he, him'),
(@zh, '她', 'tā', 'ta', 'PRON', 'HSK1', 'A1', 4, 'cô ấy', 'she, her'),
(@zh, '们', 'men', 'men', 'PARTICLE', 'HSK1', 'A1', 5, '(số nhiều)', 'plural marker'),
(@zh, '是', 'shì', 'shi', 'VERB', 'HSK1', 'A1', 6, 'là', 'to be'),
(@zh, '有', 'yǒu', 'you', 'VERB', 'HSK1', 'A1', 7, 'có', 'to have'),
(@zh, '不', 'bù', 'bu', 'ADV', 'HSK1', 'A1', 8, 'không', 'not'),
(@zh, '很', 'hěn', 'hen', 'ADV', 'HSK1', 'A1', 9, 'rất', 'very'),
(@zh, '都', 'dōu', 'dou', 'ADV', 'HSK1', 'A1', 10, 'đều', 'all'),
(@zh, '人', 'rén', 'ren', 'NOUN', 'HSK1', 'A1', 11, 'người', 'person'),
(@zh, '中国', 'Zhōngguó', 'zhongguo', 'NOUN', 'HSK1', 'A1', 12, 'Trung Quốc', 'China'),
(@zh, '日本', 'Rìběn', 'riben', 'NOUN', 'HSK1', 'A1', 13, 'Nhật Bản', 'Japan'),
(@zh, '老师', 'lǎoshī', 'laoshi', 'NOUN', 'HSK1', 'A1', 14, 'giáo viên', 'teacher'),
(@zh, '学生', 'xuésheng', 'xuesheng', 'NOUN', 'HSK1', 'A1', 15, 'học sinh', 'student'),
(@zh, '朋友', 'péngyou', 'pengyou', 'NOUN', 'HSK1', 'A1', 16, 'bạn', 'friend'),
(@zh, '爸爸', 'bàba', 'baba', 'NOUN', 'HSK1', 'A1', 17, 'bố', 'dad'),
(@zh, '妈妈', 'māma', 'mama', 'NOUN', 'HSK1', 'A1', 18, 'mẹ', 'mom'),
(@zh, '儿子', 'érzi', 'erzi', 'NOUN', 'HSK1', 'A1', 19, 'con trai', 'son'),
(@zh, '女儿', 'nǚ''ér', 'nuer', 'NOUN', 'HSK1', 'A1', 20, 'con gái', 'daughter'),
(@zh, '家', 'jiā', 'jia', 'NOUN', 'HSK1', 'A1', 21, 'nhà, gia đình', 'home, family'),
(@zh, '学校', 'xuéxiào', 'xuexiao', 'NOUN', 'HSK1', 'A1', 22, 'trường học', 'school'),
(@zh, '医院', 'yīyuàn', 'yiyuan', 'NOUN', 'HSK1', 'A1', 23, 'bệnh viện', 'hospital'),
(@zh, '商店', 'shāngdiàn', 'shangdian', 'NOUN', 'HSK1', 'A1', 24, 'cửa hàng', 'shop'),
(@zh, '饭店', 'fàndiàn', 'fandian', 'NOUN', 'HSK1', 'A1', 25, 'nhà hàng', 'restaurant'),
(@zh, '北京', 'Běijīng', 'beijing', 'NOUN', 'HSK1', 'A1', 26, 'Bắc Kinh', 'Beijing'),
(@zh, '今天', 'jīntiān', 'jintian', 'NOUN', 'HSK1', 'A1', 27, 'hôm nay', 'today'),
(@zh, '明天', 'míngtiān', 'mingtian', 'NOUN', 'HSK1', 'A1', 28, 'ngày mai', 'tomorrow'),
(@zh, '昨天', 'zuótiān', 'zuotian', 'NOUN', 'HSK1', 'A1', 29, 'hôm qua', 'yesterday'),
(@zh, '上午', 'shàngwǔ', 'shangwu', 'NOUN', 'HSK1', 'A1', 30, 'buổi sáng', 'morning'),
(@zh, '下午', 'xiàwǔ', 'xiawu', 'NOUN', 'HSK1', 'A1', 31, 'buổi chiều', 'afternoon'),
(@zh, '中午', 'zhōngwǔ', 'zhongwu', 'NOUN', 'HSK1', 'A1', 32, 'buổi trưa', 'noon'),
(@zh, '吃', 'chī', 'chi', 'VERB', 'HSK1', 'A1', 33, 'ăn', 'to eat'),
(@zh, '喝', 'hē', 'he', 'VERB', 'HSK1', 'A1', 34, 'uống', 'to drink'),
(@zh, '看', 'kàn', 'kan', 'VERB', 'HSK1', 'A1', 35, 'xem, nhìn', 'to look, watch'),
(@zh, '听', 'tīng', 'ting', 'VERB', 'HSK1', 'A1', 36, 'nghe', 'to listen'),
(@zh, '说', 'shuō', 'shuo', 'VERB', 'HSK1', 'A1', 37, 'nói', 'to speak'),
(@zh, '读', 'dú', 'du', 'VERB', 'HSK1', 'A1', 38, 'đọc', 'to read'),
(@zh, '写', 'xiě', 'xie', 'VERB', 'HSK1', 'A1', 39, 'viết', 'to write'),
(@zh, '去', 'qù', 'qu', 'VERB', 'HSK1', 'A1', 40, 'đi', 'to go'),
(@zh, '来', 'lái', 'lai', 'VERB', 'HSK1', 'A1', 41, 'đến', 'to come'),
(@zh, '回', 'huí', 'hui', 'VERB', 'HSK1', 'A1', 42, 'trở về', 'to return'),
(@zh, '买', 'mǎi', 'mai', 'VERB', 'HSK1', 'A1', 43, 'mua', 'to buy'),
(@zh, '爱', 'ài', 'ai', 'VERB', 'HSK1', 'A1', 44, 'yêu', 'to love'),
(@zh, '工作', 'gōngzuò', 'gongzuo', 'VERB', 'HSK1', 'A1', 45, 'làm việc', 'to work'),
(@zh, '学习', 'xuéxí', 'xuexi', 'VERB', 'HSK1', 'A1', 46, 'học tập', 'to study'),
(@zh, '大', 'dà', 'da', 'ADJ', 'HSK1', 'A1', 47, 'to', 'big'),
(@zh, '小', 'xiǎo', 'xiao', 'ADJ', 'HSK1', 'A1', 48, 'nhỏ', 'small'),
(@zh, '多', 'duō', 'duo', 'ADJ', 'HSK1', 'A1', 49, 'nhiều', 'many'),
(@zh, '少', 'shǎo', 'shao', 'ADJ', 'HSK1', 'A1', 50, 'ít', 'few'),
(@zh, '好', 'hǎo', 'hao', 'ADJ', 'HSK1', 'A1', 51, 'tốt', 'good'),
(@zh, '热', 'rè', 're', 'ADJ', 'HSK1', 'A1', 52, 'nóng', 'hot'),
(@zh, '冷', 'lěng', 'leng', 'ADJ', 'HSK1', 'A1', 53, 'lạnh', 'cold'),
(@zh, '一', 'yī', 'yi', 'NUM', 'HSK1', 'A1', 54, 'một', 'one'),
(@zh, '二', 'èr', 'er', 'NUM', 'HSK1', 'A1', 55, 'hai', 'two'),
(@zh, '三', 'sān', 'san', 'NUM', 'HSK1', 'A1', 56, 'ba', 'three'),
(@zh, '十', 'shí', 'shi', 'NUM', 'HSK1', 'A1', 57, 'mười', 'ten'),
(@zh, '百', 'bǎi', 'bai', 'NUM', 'HSK1', 'A1', 58, 'trăm', 'hundred'),
(@zh, '谢谢', 'xièxie', 'xiexie', 'PHRASE', 'HSK1', 'A1', 59, 'cảm ơn', 'thank you'),
(@zh, '再见', 'zàijiàn', 'zaijian', 'PHRASE', 'HSK1', 'A1', 60, 'tạm biệt', 'goodbye');

-- ========== HSK 2 (≈40 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '时间', 'shíjiān', 'shijian', 'NOUN', 'HSK2', 'A2', 100, 'thời gian', 'time'),
(@zh, '问题', 'wèntí', 'wenti', 'NOUN', 'HSK2', 'A2', 101, 'vấn đề', 'question, problem'),
(@zh, '事情', 'shìqing', 'shiqing', 'NOUN', 'HSK2', 'A2', 102, 'việc, sự việc', 'matter, affair'),
(@zh, '机场', 'jīchǎng', 'jichang', 'NOUN', 'HSK2', 'A2', 103, 'sân bay', 'airport'),
(@zh, '火车', 'huǒchē', 'huoche', 'NOUN', 'HSK2', 'A2', 104, 'tàu hỏa', 'train'),
(@zh, '出租车', 'chūzūchē', 'chuzuche', 'NOUN', 'HSK2', 'A2', 105, 'taxi', 'taxi'),
(@zh, '公司', 'gōngsī', 'gongsi', 'NOUN', 'HSK2', 'A2', 106, 'công ty', 'company'),
(@zh, '雪', 'xuě', 'xue', 'NOUN', 'HSK2', 'A2', 107, 'tuyết', 'snow'),
(@zh, '颜色', 'yánsè', 'yanse', 'NOUN', 'HSK2', 'A2', 108, 'màu sắc', 'color'),
(@zh, '黑', 'hēi', 'hei', 'ADJ', 'HSK2', 'A2', 109, 'đen', 'black'),
(@zh, '白', 'bái', 'bai', 'ADJ', 'HSK2', 'A2', 110, 'trắng', 'white'),
(@zh, '红', 'hóng', 'hong', 'ADJ', 'HSK2', 'A2', 111, 'đỏ', 'red'),
(@zh, '帮助', 'bāngzhù', 'bangzhu', 'VERB', 'HSK2', 'A2', 112, 'giúp đỡ', 'to help'),
(@zh, '介绍', 'jièshào', 'jieshao', 'VERB', 'HSK2', 'A2', 113, 'giới thiệu', 'to introduce'),
(@zh, '认识', 'rènshi', 'renshi', 'VERB', 'HSK2', 'A2', 114, 'biết, quen', 'to know'),
(@zh, '希望', 'xīwàng', 'xiwang', 'VERB', 'HSK2', 'A2', 115, 'hy vọng', 'to hope'),
(@zh, '欢迎', 'huānyíng', 'huanying', 'VERB', 'HSK2', 'A2', 116, 'hoan nghênh', 'to welcome'),
(@zh, '回答', 'huídá', 'huida', 'VERB', 'HSK2', 'A2', 117, 'trả lời', 'to answer'),
(@zh, '准备', 'zhǔnbèi', 'zhunbei', 'VERB', 'HSK2', 'A2', 118, 'chuẩn bị', 'to prepare'),
(@zh, '运动', 'yùndòng', 'yundong', 'VERB', 'HSK2', 'A2', 119, 'thể thao', 'sports'),
(@zh, '旅游', 'lǚyóu', 'lvyou', 'VERB', 'HSK2', 'A2', 120, 'du lịch', 'travel'),
(@zh, '便宜', 'piányi', 'pianyi', 'ADJ', 'HSK2', 'A2', 121, 'rẻ', 'cheap'),
(@zh, '贵', 'guì', 'gui', 'ADJ', 'HSK2', 'A2', 122, 'đắt', 'expensive'),
(@zh, '快', 'kuài', 'kuai', 'ADJ', 'HSK2', 'A2', 123, 'nhanh', 'fast'),
(@zh, '慢', 'màn', 'man', 'ADJ', 'HSK2', 'A2', 124, 'chậm', 'slow'),
(@zh, '近', 'jìn', 'jin', 'ADJ', 'HSK2', 'A2', 125, 'gần', 'near'),
(@zh, '远', 'yuǎn', 'yuan', 'ADJ', 'HSK2', 'A2', 126, 'xa', 'far'),
(@zh, '高', 'gāo', 'gao', 'ADJ', 'HSK2', 'A2', 127, 'cao', 'tall'),
(@zh, '长', 'cháng', 'chang', 'ADJ', 'HSK2', 'A2', 128, 'dài', 'long'),
(@zh, '新', 'xīn', 'xin', 'ADJ', 'HSK2', 'A2', 129, 'mới', 'new'),
(@zh, '忙', 'máng', 'mang', 'ADJ', 'HSK2', 'A2', 130, 'bận', 'busy'),
(@zh, '累', 'lèi', 'lei', 'ADJ', 'HSK2', 'A2', 131, 'mệt', 'tired'),
(@zh, '高兴', 'gāoxìng', 'gaoxing', 'ADJ', 'HSK2', 'A2', 132, 'vui', 'happy'),
(@zh, '漂亮', 'piàoliang', 'piaoliang', 'ADJ', 'HSK2', 'A2', 133, 'đẹp', 'pretty'),
(@zh, '可能', 'kěnéng', 'keneng', 'ADV', 'HSK2', 'A2', 134, 'có thể', 'maybe'),
(@zh, '一起', 'yìqǐ', 'yiqi', 'ADV', 'HSK2', 'A2', 135, 'cùng nhau', 'together'),
(@zh, '已经', 'yǐjīng', 'yijing', 'ADV', 'HSK2', 'A2', 136, 'đã, đã rồi', 'already'),
(@zh, '正在', 'zhèngzài', 'zhengzai', 'ADV', 'HSK2', 'A2', 137, 'đang', 'in progress'),
(@zh, '因为', 'yīnwèi', 'yinwei', 'CONJ', 'HSK2', 'A2', 138, 'bởi vì', 'because'),
(@zh, '所以', 'suǒyǐ', 'suoyi', 'CONJ', 'HSK2', 'A2', 139, 'cho nên', 'therefore');

-- ========== HSK 3 (≈30 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '世界', 'shìjiè', 'shijie', 'NOUN', 'HSK3', 'B1', 200, 'thế giới', 'world'),
(@zh, '故事', 'gùshi', 'gushi', 'NOUN', 'HSK3', 'B1', 201, 'câu chuyện', 'story'),
(@zh, '关系', 'guānxì', 'guanxi', 'NOUN', 'HSK3', 'B1', 202, 'mối quan hệ', 'relationship'),
(@zh, '机会', 'jīhuì', 'jihui', 'NOUN', 'HSK3', 'B1', 203, 'cơ hội', 'opportunity'),
(@zh, '环境', 'huánjìng', 'huanjing', 'NOUN', 'HSK3', 'B1', 204, 'môi trường', 'environment'),
(@zh, '感冒', 'gǎnmào', 'ganmao', 'NOUN', 'HSK3', 'B1', 205, 'cảm cúm', 'cold (illness)'),
(@zh, '健康', 'jiànkāng', 'jiankang', 'ADJ', 'HSK3', 'B1', 206, 'khỏe mạnh', 'healthy'),
(@zh, '安全', 'ānquán', 'anquan', 'ADJ', 'HSK3', 'B1', 207, 'an toàn', 'safe'),
(@zh, '简单', 'jiǎndān', 'jiandan', 'ADJ', 'HSK3', 'B1', 208, 'đơn giản', 'simple'),
(@zh, '安静', 'ānjìng', 'anjing', 'ADJ', 'HSK3', 'B1', 209, 'yên tĩnh', 'quiet'),
(@zh, '认真', 'rènzhēn', 'renzhen', 'ADJ', 'HSK3', 'B1', 210, 'nghiêm túc', 'serious'),
(@zh, '聪明', 'cōngming', 'congming', 'ADJ', 'HSK3', 'B1', 211, 'thông minh', 'smart'),
(@zh, '满意', 'mǎnyì', 'manyi', 'ADJ', 'HSK3', 'B1', 212, 'hài lòng', 'satisfied'),
(@zh, '解决', 'jiějué', 'jiejue', 'VERB', 'HSK3', 'B1', 213, 'giải quyết', 'to solve'),
(@zh, '决定', 'juédìng', 'jueding', 'VERB', 'HSK3', 'B1', 214, 'quyết định', 'to decide'),
(@zh, '同意', 'tóngyì', 'tongyi', 'VERB', 'HSK3', 'B1', 215, 'đồng ý', 'to agree'),
(@zh, '相信', 'xiāngxìn', 'xiangxin', 'VERB', 'HSK3', 'B1', 216, 'tin tưởng', 'to believe'),
(@zh, '担心', 'dānxīn', 'danxin', 'VERB', 'HSK3', 'B1', 217, 'lo lắng', 'to worry'),
(@zh, '感谢', 'gǎnxiè', 'ganxie', 'VERB', 'HSK3', 'B1', 218, 'cảm ơn', 'to thank'),
(@zh, '了解', 'liǎojiě', 'liaojie', 'VERB', 'HSK3', 'B1', 219, 'hiểu rõ', 'to understand'),
(@zh, '提高', 'tígāo', 'tigao', 'VERB', 'HSK3', 'B1', 220, 'nâng cao', 'to improve'),
(@zh, '比较', 'bǐjiào', 'bijiao', 'ADV', 'HSK3', 'B1', 221, 'tương đối', 'relatively'),
(@zh, '其实', 'qíshí', 'qishi', 'ADV', 'HSK3', 'B1', 222, 'thật ra', 'actually'),
(@zh, '一般', 'yìbān', 'yiban', 'ADJ', 'HSK3', 'B1', 223, 'bình thường', 'general'),
(@zh, '特别', 'tèbié', 'tebie', 'ADJ', 'HSK3', 'B1', 224, 'đặc biệt', 'special'),
(@zh, '终于', 'zhōngyú', 'zhongyu', 'ADV', 'HSK3', 'B1', 225, 'cuối cùng', 'finally'),
(@zh, '突然', 'tūrán', 'turan', 'ADV', 'HSK3', 'B1', 226, 'đột nhiên', 'suddenly'),
(@zh, '当然', 'dāngrán', 'dangran', 'ADV', 'HSK3', 'B1', 227, 'đương nhiên', 'of course'),
(@zh, '虽然', 'suīrán', 'suiran', 'CONJ', 'HSK3', 'B1', 228, 'mặc dù', 'although'),
(@zh, '但是', 'dànshì', 'danshi', 'CONJ', 'HSK3', 'B1', 229, 'nhưng', 'but');

-- ========== HSK 4-6 (≈25 từ) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '矛盾', 'máodùn', 'maodun', 'NOUN', 'HSK4', 'B2', 400, 'mâu thuẫn', 'contradiction'),
(@zh, '观点', 'guāndiǎn', 'guandian', 'NOUN', 'HSK4', 'B2', 401, 'quan điểm', 'viewpoint'),
(@zh, '态度', 'tàidu', 'taidu', 'NOUN', 'HSK4', 'B2', 402, 'thái độ', 'attitude'),
(@zh, '能力', 'nénglì', 'nengli', 'NOUN', 'HSK4', 'B2', 403, 'năng lực', 'ability'),
(@zh, '经验', 'jīngyàn', 'jingyan', 'NOUN', 'HSK4', 'B2', 404, 'kinh nghiệm', 'experience'),
(@zh, '过程', 'guòchéng', 'guocheng', 'NOUN', 'HSK4', 'B2', 405, 'quá trình', 'process'),
(@zh, '影响', 'yǐngxiǎng', 'yingxiang', 'NOUN', 'HSK4', 'B2', 406, 'ảnh hưởng', 'influence'),
(@zh, '原因', 'yuányīn', 'yuanyin', 'NOUN', 'HSK4', 'B2', 407, 'nguyên nhân', 'cause'),
(@zh, '困难', 'kùnnan', 'kunnan', 'ADJ', 'HSK4', 'B2', 408, 'khó khăn', 'difficult'),
(@zh, '严重', 'yánzhòng', 'yanzhong', 'ADJ', 'HSK4', 'B2', 409, 'nghiêm trọng', 'serious'),
(@zh, '复杂', 'fùzá', 'fuza', 'ADJ', 'HSK4', 'B2', 410, 'phức tạp', 'complex'),
(@zh, '成功', 'chénggōng', 'chenggong', 'VERB', 'HSK4', 'B2', 411, 'thành công', 'to succeed'),
(@zh, '改变', 'gǎibiàn', 'gaibian', 'VERB', 'HSK4', 'B2', 412, 'thay đổi', 'to change'),
(@zh, '发展', 'fāzhǎn', 'fazhan', 'VERB', 'HSK4', 'B2', 413, 'phát triển', 'to develop'),
(@zh, '坚持', 'jiānchí', 'jianchi', 'VERB', 'HSK4', 'B2', 414, 'kiên trì', 'to persist'),
(@zh, '建议', 'jiànyì', 'jianyi', 'VERB', 'HSK4', 'B2', 415, 'đề nghị', 'to suggest'),
(@zh, '采取', 'cǎiqǔ', 'caiqu', 'VERB', 'HSK5', 'B2', 500, 'áp dụng', 'to adopt'),
(@zh, '充满', 'chōngmǎn', 'chongman', 'VERB', 'HSK5', 'C1', 501, 'tràn đầy', 'to be full of'),
(@zh, '促进', 'cùjìn', 'cujin', 'VERB', 'HSK5', 'C1', 502, 'thúc đẩy', 'to promote'),
(@zh, '制定', 'zhìdìng', 'zhiding', 'VERB', 'HSK5', 'C1', 503, 'lập (kế hoạch)', 'to formulate'),
(@zh, '逐渐', 'zhújiàn', 'zhujian', 'ADV', 'HSK5', 'C1', 504, 'dần dần', 'gradually'),
(@zh, '彼此', 'bǐcǐ', 'bici', 'PRON', 'HSK5', 'C1', 505, 'lẫn nhau', 'each other'),
(@zh, '蕴含', 'yùnhán', 'yunhan', 'VERB', 'HSK6', 'C2', 600, 'hàm chứa', 'to contain'),
(@zh, '渊博', 'yuānbó', 'yuanbo', 'ADJ', 'HSK6', 'C2', 601, 'uyên bác', 'erudite'),
(@zh, '凝聚', 'níngjù', 'ningju', 'VERB', 'HSK6', 'C2', 602, 'cô đọng', 'to condense');

-- ----- Câu ví dụ tiếng Trung -----
INSERT INTO word_examples (word_id, sentence, reading, translation, level_code, source) VALUES
((SELECT id FROM words WHERE `text`='吃' AND language_id=@zh LIMIT 1),
 '我喜欢吃中国菜。', 'Wǒ xǐhuan chī Zhōngguó cài.', 'Tôi thích ăn món Trung Quốc.', 'HSK1', 'curated'),
((SELECT id FROM words WHERE `text`='学习' AND language_id=@zh LIMIT 1),
 '我每天学习汉语。', 'Wǒ měitiān xuéxí Hànyǔ.', 'Tôi học tiếng Hán mỗi ngày.', 'HSK1', 'curated'),
((SELECT id FROM words WHERE `text`='帮助' AND language_id=@zh LIMIT 1),
 '谢谢你的帮助。', 'Xièxie nǐ de bāngzhù.', 'Cảm ơn sự giúp đỡ của bạn.', 'HSK2', 'curated'),
((SELECT id FROM words WHERE `text`='经验' AND language_id=@zh LIMIT 1),
 '他有丰富的工作经验。', 'Tā yǒu fēngfù de gōngzuò jīngyàn.', 'Anh ấy có kinh nghiệm làm việc phong phú.', 'HSK4', 'curated');
