-- =====================================================
-- SEED: Vocabulary - Korean (TOPIK I → TOPIK II)
-- Nguồn: TOPIK official wordlist (Beginner/Intermediate/Advanced)
-- =====================================================

SET NAMES utf8mb4;
SET @ko := (SELECT id FROM languages WHERE code='ko');

-- ========== TOPIK I — Level 1-2 (Beginner) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, topik_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ko, '저', '저', 'jeo', 'PRON', 'TOPIK1', 'A1', 1, 'tôi (lịch sự)', 'I (polite)'),
(@ko, '나', '나', 'na', 'PRON', 'TOPIK1', 'A1', 2, 'tôi (thân mật)', 'I (casual)'),
(@ko, '당신', '당신', 'dangsin', 'PRON', 'TOPIK1', 'A1', 3, 'bạn', 'you'),
(@ko, '사람', '사람', 'saram', 'NOUN', 'TOPIK1', 'A1', 4, 'người', 'person'),
(@ko, '이름', '이름', 'ireum', 'NOUN', 'TOPIK1', 'A1', 5, 'tên', 'name'),
(@ko, '나라', '나라', 'nara', 'NOUN', 'TOPIK1', 'A1', 6, 'đất nước', 'country'),
(@ko, '한국', '한국', 'hanguk', 'NOUN', 'TOPIK1', 'A1', 7, 'Hàn Quốc', 'Korea'),
(@ko, '학교', '학교', 'hakgyo', 'NOUN', 'TOPIK1', 'A1', 8, 'trường học', 'school'),
(@ko, '집', '집', 'jip', 'NOUN', 'TOPIK1', 'A1', 9, 'nhà', 'house, home'),
(@ko, '회사', '회사', 'hoesa', 'NOUN', 'TOPIK1', 'A1', 10, 'công ty', 'company'),
(@ko, '친구', '친구', 'chingu', 'NOUN', 'TOPIK1', 'A1', 11, 'bạn bè', 'friend'),
(@ko, '가족', '가족', 'gajok', 'NOUN', 'TOPIK1', 'A1', 12, 'gia đình', 'family'),
(@ko, '선생님', '선생님', 'seonsaengnim', 'NOUN', 'TOPIK1', 'A1', 13, 'giáo viên', 'teacher'),
(@ko, '학생', '학생', 'haksaeng', 'NOUN', 'TOPIK1', 'A1', 14, 'học sinh', 'student'),
(@ko, '아버지', '아버지', 'abeoji', 'NOUN', 'TOPIK1', 'A1', 15, 'bố', 'father'),
(@ko, '어머니', '어머니', 'eomeoni', 'NOUN', 'TOPIK1', 'A1', 16, 'mẹ', 'mother'),
(@ko, '오빠', '오빠', 'oppa', 'NOUN', 'TOPIK1', 'A1', 17, 'anh trai (em gái gọi)', 'older brother (girl''s)'),
(@ko, '언니', '언니', 'eonni', 'NOUN', 'TOPIK1', 'A1', 18, 'chị (em gái gọi)', 'older sister (girl''s)'),
(@ko, '형', '형', 'hyeong', 'NOUN', 'TOPIK1', 'A1', 19, 'anh trai (em trai gọi)', 'older brother (boy''s)'),
(@ko, '누나', '누나', 'nuna', 'NOUN', 'TOPIK1', 'A1', 20, 'chị (em trai gọi)', 'older sister (boy''s)'),
(@ko, '동생', '동생', 'dongsaeng', 'NOUN', 'TOPIK1', 'A1', 21, 'em', 'younger sibling'),
(@ko, '오늘', '오늘', 'oneul', 'NOUN', 'TOPIK1', 'A1', 22, 'hôm nay', 'today'),
(@ko, '어제', '어제', 'eoje', 'NOUN', 'TOPIK1', 'A1', 23, 'hôm qua', 'yesterday'),
(@ko, '내일', '내일', 'naeil', 'NOUN', 'TOPIK1', 'A1', 24, 'ngày mai', 'tomorrow'),
(@ko, '아침', '아침', 'achim', 'NOUN', 'TOPIK1', 'A1', 25, 'buổi sáng', 'morning'),
(@ko, '점심', '점심', 'jeomsim', 'NOUN', 'TOPIK1', 'A1', 26, 'bữa trưa', 'lunch'),
(@ko, '저녁', '저녁', 'jeonyeok', 'NOUN', 'TOPIK1', 'A1', 27, 'buổi tối', 'evening'),
(@ko, '밥', '밥', 'bap', 'NOUN', 'TOPIK1', 'A1', 28, 'cơm', 'rice'),
(@ko, '물', '물', 'mul', 'NOUN', 'TOPIK1', 'A1', 29, 'nước', 'water'),
(@ko, '음식', '음식', 'eumsik', 'NOUN', 'TOPIK1', 'A1', 30, 'thức ăn', 'food'),
(@ko, '책', '책', 'chaek', 'NOUN', 'TOPIK1', 'A1', 31, 'sách', 'book'),
(@ko, '가다', '가다', 'gada', 'VERB', 'TOPIK1', 'A1', 32, 'đi', 'to go'),
(@ko, '오다', '오다', 'oda', 'VERB', 'TOPIK1', 'A1', 33, 'đến', 'to come'),
(@ko, '먹다', '먹다', 'meokda', 'VERB', 'TOPIK1', 'A1', 34, 'ăn', 'to eat'),
(@ko, '마시다', '마시다', 'masida', 'VERB', 'TOPIK1', 'A1', 35, 'uống', 'to drink'),
(@ko, '보다', '보다', 'boda', 'VERB', 'TOPIK1', 'A1', 36, 'xem', 'to see'),
(@ko, '듣다', '듣다', 'deutda', 'VERB', 'TOPIK1', 'A1', 37, 'nghe', 'to listen'),
(@ko, '말하다', '말하다', 'malhada', 'VERB', 'TOPIK1', 'A1', 38, 'nói', 'to speak'),
(@ko, '읽다', '읽다', 'ikda', 'VERB', 'TOPIK1', 'A1', 39, 'đọc', 'to read'),
(@ko, '쓰다', '쓰다', 'sseuda', 'VERB', 'TOPIK1', 'A1', 40, 'viết', 'to write'),
(@ko, '사다', '사다', 'sada', 'VERB', 'TOPIK1', 'A1', 41, 'mua', 'to buy'),
(@ko, '공부하다', '공부하다', 'gongbuhada', 'VERB', 'TOPIK1', 'A1', 42, 'học', 'to study'),
(@ko, '일하다', '일하다', 'ilhada', 'VERB', 'TOPIK1', 'A1', 43, 'làm việc', 'to work'),
(@ko, '자다', '자다', 'jada', 'VERB', 'TOPIK1', 'A1', 44, 'ngủ', 'to sleep'),
(@ko, '크다', '크다', 'keuda', 'ADJ', 'TOPIK1', 'A1', 45, 'to', 'big'),
(@ko, '작다', '작다', 'jakda', 'ADJ', 'TOPIK1', 'A1', 46, 'nhỏ', 'small'),
(@ko, '많다', '많다', 'manta', 'ADJ', 'TOPIK1', 'A2', 47, 'nhiều', 'many'),
(@ko, '적다', '적다', 'jeokda', 'ADJ', 'TOPIK1', 'A2', 48, 'ít', 'few'),
(@ko, '좋다', '좋다', 'jota', 'ADJ', 'TOPIK1', 'A1', 49, 'tốt', 'good'),
(@ko, '나쁘다', '나쁘다', 'nappeuda', 'ADJ', 'TOPIK1', 'A2', 50, 'xấu', 'bad'),
(@ko, '예쁘다', '예쁘다', 'yeppeuda', 'ADJ', 'TOPIK1', 'A2', 51, 'đẹp', 'pretty'),
(@ko, '재미있다', '재미있다', 'jaemiitda', 'ADJ', 'TOPIK1', 'A2', 52, 'thú vị', 'interesting'),
(@ko, '안녕하세요', '안녕하세요', 'annyeonghaseyo', 'PHRASE', 'TOPIK1', 'A1', 53, 'xin chào', 'hello'),
(@ko, '감사합니다', '감사합니다', 'gamsahamnida', 'PHRASE', 'TOPIK1', 'A1', 54, 'cảm ơn (lịch sự)', 'thank you'),
(@ko, '미안합니다', '미안합니다', 'mianhamnida', 'PHRASE', 'TOPIK1', 'A1', 55, 'xin lỗi', 'sorry'),
(@ko, '하나', '하나', 'hana', 'NUM', 'TOPIK1', 'A1', 56, 'một', 'one (native)'),
(@ko, '둘', '둘', 'dul', 'NUM', 'TOPIK1', 'A1', 57, 'hai', 'two (native)'),
(@ko, '셋', '셋', 'set', 'NUM', 'TOPIK1', 'A1', 58, 'ba', 'three (native)'),
(@ko, '일', '일', 'il', 'NUM', 'TOPIK1', 'A1', 59, 'một (Hán)', 'one (Sino)'),
(@ko, '이', '이', 'i', 'NUM', 'TOPIK1', 'A1', 60, 'hai (Hán)', 'two (Sino)');

-- ========== TOPIK II — Level 3-6 (Intermediate / Advanced) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, topik_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ko, '사회', '사회', 'sahoe', 'NOUN', 'TOPIK3', 'B1', 200, 'xã hội', 'society'),
(@ko, '경제', '경제', 'gyeongje', 'NOUN', 'TOPIK3', 'B1', 201, 'kinh tế', 'economy'),
(@ko, '문화', '문화', 'munhwa', 'NOUN', 'TOPIK3', 'B1', 202, 'văn hóa', 'culture'),
(@ko, '교육', '교육', 'gyoyuk', 'NOUN', 'TOPIK3', 'B1', 203, 'giáo dục', 'education'),
(@ko, '환경', '환경', 'hwangyeong', 'NOUN', 'TOPIK3', 'B1', 204, 'môi trường', 'environment'),
(@ko, '관계', '관계', 'gwangye', 'NOUN', 'TOPIK3', 'B1', 205, 'mối quan hệ', 'relationship'),
(@ko, '경험', '경험', 'gyeongheom', 'NOUN', 'TOPIK3', 'B1', 206, 'kinh nghiệm', 'experience'),
(@ko, '기회', '기회', 'gihoe', 'NOUN', 'TOPIK3', 'B1', 207, 'cơ hội', 'opportunity'),
(@ko, '결과', '결과', 'gyeolgwa', 'NOUN', 'TOPIK3', 'B1', 208, 'kết quả', 'result'),
(@ko, '원인', '원인', 'wonin', 'NOUN', 'TOPIK3', 'B1', 209, 'nguyên nhân', 'cause'),
(@ko, '문제', '문제', 'munje', 'NOUN', 'TOPIK3', 'B1', 210, 'vấn đề', 'problem'),
(@ko, '해결하다', '해결하다', 'haegyeolhada', 'VERB', 'TOPIK3', 'B1', 211, 'giải quyết', 'to solve'),
(@ko, '결정하다', '결정하다', 'gyeoljeonghada', 'VERB', 'TOPIK3', 'B1', 212, 'quyết định', 'to decide'),
(@ko, '발전하다', '발전하다', 'baljeonhada', 'VERB', 'TOPIK3', 'B1', 213, 'phát triển', 'to develop'),
(@ko, '제안하다', '제안하다', 'jeanhada', 'VERB', 'TOPIK4', 'B2', 214, 'đề xuất', 'to suggest'),
(@ko, '향상되다', '향상되다', 'hyangsangdoeda', 'VERB', 'TOPIK4', 'B2', 215, 'được cải thiện', 'to be improved'),
(@ko, '필요하다', '필요하다', 'piryohada', 'ADJ', 'TOPIK3', 'B1', 216, 'cần thiết', 'necessary'),
(@ko, '중요하다', '중요하다', 'jungyohada', 'ADJ', 'TOPIK3', 'B1', 217, 'quan trọng', 'important'),
(@ko, '편리하다', '편리하다', 'pyeollihada', 'ADJ', 'TOPIK3', 'B1', 218, 'tiện lợi', 'convenient'),
(@ko, '효율적', '효율적', 'hyoyuljeok', 'ADJ', 'TOPIK4', 'B2', 219, 'hiệu quả', 'efficient'),
(@ko, '심각하다', '심각하다', 'simgakhada', 'ADJ', 'TOPIK4', 'B2', 220, 'nghiêm trọng', 'serious'),
(@ko, '구체적', '구체적', 'guchejeok', 'ADJ', 'TOPIK4', 'B2', 221, 'cụ thể', 'concrete'),
(@ko, '추상적', '추상적', 'chusangjeok', 'ADJ', 'TOPIK5', 'C1', 222, 'trừu tượng', 'abstract'),
(@ko, '모순', '모순', 'mosun', 'NOUN', 'TOPIK5', 'C1', 223, 'mâu thuẫn', 'contradiction'),
(@ko, '본질', '본질', 'bonjil', 'NOUN', 'TOPIK5', 'C1', 224, 'bản chất', 'essence'),
(@ko, '관점', '관점', 'gwanjeom', 'NOUN', 'TOPIK5', 'C1', 225, 'quan điểm', 'viewpoint'),
(@ko, '편견', '편견', 'pyeongyeon', 'NOUN', 'TOPIK5', 'C1', 226, 'thành kiến', 'prejudice'),
(@ko, '기여하다', '기여하다', 'giyeohada', 'VERB', 'TOPIK5', 'C1', 227, 'đóng góp', 'to contribute'),
(@ko, '극복하다', '극복하다', 'geukbokhada', 'VERB', 'TOPIK5', 'C1', 228, 'khắc phục', 'to overcome'),
(@ko, '추구하다', '추구하다', 'chuguhada', 'VERB', 'TOPIK6', 'C2', 229, 'theo đuổi', 'to pursue');

-- ----- Câu ví dụ tiếng Hàn -----
INSERT INTO word_examples (word_id, sentence, reading, translation, level_code, source) VALUES
((SELECT id FROM words WHERE `text`='먹다' AND language_id=@ko LIMIT 1),
 '저는 한국 음식을 좋아합니다.', 'jeoneun hanguk eumsigeul joahamnida.', 'Tôi thích món ăn Hàn Quốc.', 'TOPIK1', 'curated'),
((SELECT id FROM words WHERE `text`='공부하다' AND language_id=@ko LIMIT 1),
 '매일 한국어를 공부해요.', 'maeil hangugeoreul gongbuhaeyo.', 'Tôi học tiếng Hàn mỗi ngày.', 'TOPIK1', 'curated'),
((SELECT id FROM words WHERE `text`='경험' AND language_id=@ko LIMIT 1),
 '저는 한국에서 일한 경험이 있어요.', 'jeoneun hangugeseo ilhan gyeongheomi isseoyo.', 'Tôi có kinh nghiệm làm việc ở Hàn Quốc.', 'TOPIK3', 'curated'),
((SELECT id FROM words WHERE `text`='기여하다' AND language_id=@ko LIMIT 1),
 '그는 회사 발전에 크게 기여했다.', 'geuneun hoesa baljeone keuge giyeohaetda.', 'Anh ấy đã đóng góp lớn cho sự phát triển công ty.', 'TOPIK5', 'curated');
