-- =====================================================
-- SEED EXT: Japanese JLPT vocabulary - Extended
-- Sources: jamsinclair/open-anki-jlpt-decks (CC0),
--          stephenmk/yomitan-jlpt-vocab (CC-BY),
--          elzup/jlpt-word-list, JMDict (edrdg.org, CC-BY-SA)
-- Adds: more N5/N4/N3/N2/N1 vocab + example sentences from Tatoeba (CC-BY 2.0 FR)
-- =====================================================

SET NAMES utf8mb4;
SET @ja := (SELECT id FROM languages WHERE code='ja');

-- ========== JLPT N5 - Extended (~120 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '一', 'いち', 'ichi', 'NUM', 'N5', 'A1', 50, 'một', 'one'),
(@ja, '二', 'に', 'ni', 'NUM', 'N5', 'A1', 51, 'hai', 'two'),
(@ja, '三', 'さん', 'san', 'NUM', 'N5', 'A1', 52, 'ba', 'three'),
(@ja, '四', 'よん', 'yon', 'NUM', 'N5', 'A1', 53, 'bốn', 'four'),
(@ja, '五', 'ご', 'go', 'NUM', 'N5', 'A1', 54, 'năm', 'five'),
(@ja, '六', 'ろく', 'roku', 'NUM', 'N5', 'A1', 55, 'sáu', 'six'),
(@ja, '七', 'なな', 'nana', 'NUM', 'N5', 'A1', 56, 'bảy', 'seven'),
(@ja, '八', 'はち', 'hachi', 'NUM', 'N5', 'A1', 57, 'tám', 'eight'),
(@ja, '九', 'きゅう', 'kyuu', 'NUM', 'N5', 'A1', 58, 'chín', 'nine'),
(@ja, '十', 'じゅう', 'juu', 'NUM', 'N5', 'A1', 59, 'mười', 'ten'),
(@ja, '百', 'ひゃく', 'hyaku', 'NUM', 'N5', 'A1', 60, 'trăm', 'hundred'),
(@ja, '千', 'せん', 'sen', 'NUM', 'N5', 'A1', 61, 'nghìn', 'thousand'),
(@ja, '万', 'まん', 'man', 'NUM', 'N5', 'A1', 62, 'vạn', 'ten thousand'),
(@ja, '円', 'えん', 'en', 'NOUN', 'N5', 'A1', 63, 'yên (tiền)', 'yen'),
(@ja, '時間', 'じかん', 'jikan', 'NOUN', 'N5', 'A1', 64, 'thời gian', 'time, hour'),
(@ja, '分', 'ふん', 'fun', 'NOUN', 'N5', 'A1', 65, 'phút', 'minute'),
(@ja, '秒', 'びょう', 'byou', 'NOUN', 'N5', 'A1', 66, 'giây', 'second'),
(@ja, '午前', 'ごぜん', 'gozen', 'NOUN', 'N5', 'A1', 67, 'sáng', 'AM'),
(@ja, '午後', 'ごご', 'gogo', 'NOUN', 'N5', 'A1', 68, 'chiều', 'PM'),
(@ja, '朝', 'あさ', 'asa', 'NOUN', 'N5', 'A1', 69, 'buổi sáng', 'morning'),
(@ja, '昼', 'ひる', 'hiru', 'NOUN', 'N5', 'A1', 70, 'buổi trưa', 'noon, daytime'),
(@ja, '夜', 'よる', 'yoru', 'NOUN', 'N5', 'A1', 71, 'buổi tối', 'night'),
(@ja, '今日', 'きょう', 'kyou', 'NOUN', 'N5', 'A1', 72, 'hôm nay', 'today'),
(@ja, '昨日', 'きのう', 'kinou', 'NOUN', 'N5', 'A1', 73, 'hôm qua', 'yesterday'),
(@ja, '明日', 'あした', 'ashita', 'NOUN', 'N5', 'A1', 74, 'ngày mai', 'tomorrow'),
(@ja, '今週', 'こんしゅう', 'konshuu', 'NOUN', 'N5', 'A1', 75, 'tuần này', 'this week'),
(@ja, '来週', 'らいしゅう', 'raishuu', 'NOUN', 'N5', 'A1', 76, 'tuần sau', 'next week'),
(@ja, '先週', 'せんしゅう', 'senshuu', 'NOUN', 'N5', 'A1', 77, 'tuần trước', 'last week'),
(@ja, '春', 'はる', 'haru', 'NOUN', 'N5', 'A1', 78, 'mùa xuân', 'spring'),
(@ja, '夏', 'なつ', 'natsu', 'NOUN', 'N5', 'A1', 79, 'mùa hè', 'summer'),
(@ja, '秋', 'あき', 'aki', 'NOUN', 'N5', 'A1', 80, 'mùa thu', 'autumn'),
(@ja, '冬', 'ふゆ', 'fuyu', 'NOUN', 'N5', 'A1', 81, 'mùa đông', 'winter'),
(@ja, '右', 'みぎ', 'migi', 'NOUN', 'N5', 'A1', 82, 'phải', 'right'),
(@ja, '左', 'ひだり', 'hidari', 'NOUN', 'N5', 'A1', 83, 'trái', 'left'),
(@ja, '上', 'うえ', 'ue', 'NOUN', 'N5', 'A1', 84, 'trên', 'above'),
(@ja, '下', 'した', 'shita', 'NOUN', 'N5', 'A1', 85, 'dưới', 'below'),
(@ja, '前', 'まえ', 'mae', 'NOUN', 'N5', 'A1', 86, 'phía trước', 'in front of'),
(@ja, '後ろ', 'うしろ', 'ushiro', 'NOUN', 'N5', 'A1', 87, 'phía sau', 'behind'),
(@ja, '中', 'なか', 'naka', 'NOUN', 'N5', 'A1', 88, 'bên trong', 'inside'),
(@ja, '外', 'そと', 'soto', 'NOUN', 'N5', 'A1', 89, 'bên ngoài', 'outside'),
(@ja, '近く', 'ちかく', 'chikaku', 'NOUN', 'N5', 'A1', 90, 'gần', 'nearby'),
(@ja, '遠く', 'とおく', 'tooku', 'NOUN', 'N5', 'A1', 91, 'xa', 'far'),
(@ja, '高い', 'たかい', 'takai', 'ADJ', 'N5', 'A1', 92, 'cao, đắt', 'tall, expensive'),
(@ja, '低い', 'ひくい', 'hikui', 'ADJ', 'N5', 'A1', 93, 'thấp', 'low, short'),
(@ja, '安い', 'やすい', 'yasui', 'ADJ', 'N5', 'A1', 94, 'rẻ', 'cheap'),
(@ja, '広い', 'ひろい', 'hiroi', 'ADJ', 'N5', 'A1', 95, 'rộng', 'wide'),
(@ja, '狭い', 'せまい', 'semai', 'ADJ', 'N5', 'A1', 96, 'hẹp', 'narrow'),
(@ja, '長い', 'ながい', 'nagai', 'ADJ', 'N5', 'A1', 97, 'dài', 'long'),
(@ja, '短い', 'みじかい', 'mijikai', 'ADJ', 'N5', 'A1', 98, 'ngắn', 'short'),
(@ja, '熱い', 'あつい', 'atsui', 'ADJ', 'N5', 'A1', 99, 'nóng (đồ vật)', 'hot'),
(@ja, '寒い', 'さむい', 'samui', 'ADJ', 'N5', 'A1', 100, 'lạnh (thời tiết)', 'cold (weather)'),
(@ja, '冷たい', 'つめたい', 'tsumetai', 'ADJ', 'N5', 'A1', 101, 'lạnh (vật)', 'cold (object)'),
(@ja, '新しい', 'あたらしい', 'atarashii', 'ADJ', 'N5', 'A1', 102, 'mới', 'new'),
(@ja, '古い', 'ふるい', 'furui', 'ADJ', 'N5', 'A1', 103, 'cũ', 'old'),
(@ja, '若い', 'わかい', 'wakai', 'ADJ', 'N5', 'A1', 104, 'trẻ', 'young'),
(@ja, '元気', 'げんき', 'genki', 'ADJ', 'N5', 'A1', 105, 'khỏe', 'healthy, energetic'),
(@ja, '静か', 'しずか', 'shizuka', 'ADJ', 'N5', 'A1', 106, 'yên tĩnh', 'quiet'),
(@ja, 'にぎやか', 'にぎやか', 'nigiyaka', 'ADJ', 'N5', 'A1', 107, 'náo nhiệt', 'lively'),
(@ja, 'きれい', 'きれい', 'kirei', 'ADJ', 'N5', 'A1', 108, 'đẹp, sạch', 'beautiful, clean'),
(@ja, '汚い', 'きたない', 'kitanai', 'ADJ', 'N5', 'A1', 109, 'bẩn', 'dirty'),
(@ja, '好き', 'すき', 'suki', 'ADJ', 'N5', 'A1', 110, 'thích', 'to like'),
(@ja, '嫌い', 'きらい', 'kirai', 'ADJ', 'N5', 'A1', 111, 'ghét', 'to dislike'),
(@ja, '上手', 'じょうず', 'jouzu', 'ADJ', 'N5', 'A1', 112, 'giỏi', 'skillful'),
(@ja, '下手', 'へた', 'heta', 'ADJ', 'N5', 'A1', 113, 'kém', 'unskillful'),
(@ja, '読む', 'よむ', 'yomu', 'VERB', 'N5', 'A1', 114, 'đọc', 'to read'),
(@ja, '書く', 'かく', 'kaku', 'VERB', 'N5', 'A1', 115, 'viết', 'to write'),
(@ja, '聞く', 'きく', 'kiku', 'VERB', 'N5', 'A1', 116, 'nghe, hỏi', 'to listen, ask'),
(@ja, '話す', 'はなす', 'hanasu', 'VERB', 'N5', 'A1', 117, 'nói chuyện', 'to speak'),
(@ja, '見る', 'みる', 'miru', 'VERB', 'N5', 'A1', 118, 'xem, nhìn', 'to see'),
(@ja, '買う', 'かう', 'kau', 'VERB', 'N5', 'A1', 119, 'mua', 'to buy'),
(@ja, '売る', 'うる', 'uru', 'VERB', 'N5', 'A1', 120, 'bán', 'to sell'),
(@ja, '作る', 'つくる', 'tsukuru', 'VERB', 'N5', 'A1', 121, 'làm, tạo', 'to make'),
(@ja, '使う', 'つかう', 'tsukau', 'VERB', 'N5', 'A1', 122, 'sử dụng', 'to use'),
(@ja, '帰る', 'かえる', 'kaeru', 'VERB', 'N5', 'A1', 123, 'trở về', 'to return home'),
(@ja, '出る', 'でる', 'deru', 'VERB', 'N5', 'A1', 124, 'ra ngoài', 'to leave, exit'),
(@ja, '入る', 'はいる', 'hairu', 'VERB', 'N5', 'A1', 125, 'vào', 'to enter'),
(@ja, '立つ', 'たつ', 'tatsu', 'VERB', 'N5', 'A1', 126, 'đứng', 'to stand'),
(@ja, '座る', 'すわる', 'suwaru', 'VERB', 'N5', 'A1', 127, 'ngồi', 'to sit'),
(@ja, '起きる', 'おきる', 'okiru', 'VERB', 'N5', 'A1', 128, 'thức dậy', 'to wake up'),
(@ja, '寝る', 'ねる', 'neru', 'VERB', 'N5', 'A1', 129, 'ngủ', 'to sleep'),
(@ja, '休む', 'やすむ', 'yasumu', 'VERB', 'N5', 'A1', 130, 'nghỉ', 'to rest'),
(@ja, '働く', 'はたらく', 'hataraku', 'VERB', 'N5', 'A1', 131, 'làm việc', 'to work'),
(@ja, '勉強', 'べんきょう', 'benkyou', 'NOUN', 'N5', 'A1', 132, 'học tập', 'study'),
(@ja, '宿題', 'しゅくだい', 'shukudai', 'NOUN', 'N5', 'A1', 133, 'bài tập về nhà', 'homework'),
(@ja, '試験', 'しけん', 'shiken', 'NOUN', 'N5', 'A1', 134, 'kỳ thi', 'exam'),
(@ja, '質問', 'しつもん', 'shitsumon', 'NOUN', 'N5', 'A1', 135, 'câu hỏi', 'question'),
(@ja, '答え', 'こたえ', 'kotae', 'NOUN', 'N5', 'A1', 136, 'câu trả lời', 'answer'),
(@ja, '名前', 'なまえ', 'namae', 'NOUN', 'N5', 'A1', 137, 'tên', 'name'),
(@ja, '番号', 'ばんごう', 'bangou', 'NOUN', 'N5', 'A1', 138, 'số', 'number'),
(@ja, '住所', 'じゅうしょ', 'juusho', 'NOUN', 'N5', 'A1', 139, 'địa chỉ', 'address'),
(@ja, '電話', 'でんわ', 'denwa', 'NOUN', 'N5', 'A1', 140, 'điện thoại', 'telephone'),
(@ja, '手紙', 'てがみ', 'tegami', 'NOUN', 'N5', 'A1', 141, 'thư', 'letter'),
(@ja, '新聞', 'しんぶん', 'shinbun', 'NOUN', 'N5', 'A1', 142, 'báo', 'newspaper'),
(@ja, '雑誌', 'ざっし', 'zasshi', 'NOUN', 'N5', 'A1', 143, 'tạp chí', 'magazine'),
(@ja, '辞書', 'じしょ', 'jisho', 'NOUN', 'N5', 'A1', 144, 'từ điển', 'dictionary'),
(@ja, '映画', 'えいが', 'eiga', 'NOUN', 'N5', 'A1', 145, 'phim', 'movie'),
(@ja, '音楽', 'おんがく', 'ongaku', 'NOUN', 'N5', 'A1', 146, 'âm nhạc', 'music'),
(@ja, '歌', 'うた', 'uta', 'NOUN', 'N5', 'A1', 147, 'bài hát', 'song'),
(@ja, '写真', 'しゃしん', 'shashin', 'NOUN', 'N5', 'A1', 148, 'ảnh', 'photograph'),
(@ja, '料理', 'りょうり', 'ryouri', 'NOUN', 'N5', 'A1', 149, 'món ăn, nấu ăn', 'cooking'),
(@ja, '仕事', 'しごと', 'shigoto', 'NOUN', 'N5', 'A1', 150, 'công việc', 'work, job');

-- ========== JLPT N4 - Extended (~80 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '案内', 'あんない', 'annai', 'NOUN', 'N4', 'A2', 200, 'hướng dẫn', 'guidance'),
(@ja, '以上', 'いじょう', 'ijou', 'NOUN', 'N4', 'A2', 201, 'trở lên', 'more than'),
(@ja, '以下', 'いか', 'ika', 'NOUN', 'N4', 'A2', 202, 'trở xuống', 'less than'),
(@ja, '意見', 'いけん', 'iken', 'NOUN', 'N4', 'A2', 203, 'ý kiến', 'opinion'),
(@ja, '医者', 'いしゃ', 'isha', 'NOUN', 'N4', 'A2', 204, 'bác sĩ', 'doctor'),
(@ja, '一生懸命', 'いっしょうけんめい', 'isshoukenmei', 'ADV', 'N4', 'A2', 205, 'cố gắng hết sức', 'with all efforts'),
(@ja, '受付', 'うけつけ', 'uketsuke', 'NOUN', 'N4', 'A2', 206, 'lễ tân', 'reception'),
(@ja, '運転', 'うんてん', 'unten', 'NOUN', 'N4', 'A2', 207, 'lái xe', 'driving'),
(@ja, '運動', 'うんどう', 'undou', 'NOUN', 'N4', 'A2', 208, 'vận động', 'exercise'),
(@ja, '映画館', 'えいがかん', 'eigakan', 'NOUN', 'N4', 'A2', 209, 'rạp chiếu phim', 'cinema'),
(@ja, '英語', 'えいご', 'eigo', 'NOUN', 'N4', 'A2', 210, 'tiếng Anh', 'English language'),
(@ja, '駅員', 'えきいん', 'ekiin', 'NOUN', 'N4', 'A2', 211, 'nhân viên ga', 'station staff'),
(@ja, '遠慮', 'えんりょ', 'enryo', 'NOUN', 'N4', 'A2', 212, 'khách sáo, e ngại', 'restraint'),
(@ja, '大勢', 'おおぜい', 'oozei', 'NOUN', 'N4', 'A2', 213, 'đông người', 'many people'),
(@ja, '屋上', 'おくじょう', 'okujou', 'NOUN', 'N4', 'A2', 214, 'sân thượng', 'rooftop'),
(@ja, '贈り物', 'おくりもの', 'okurimono', 'NOUN', 'N4', 'A2', 215, 'quà tặng', 'present, gift'),
(@ja, '夫', 'おっと', 'otto', 'NOUN', 'N4', 'A2', 216, 'chồng', 'husband'),
(@ja, '思い出', 'おもいで', 'omoide', 'NOUN', 'N4', 'A2', 217, 'kỉ niệm', 'memory'),
(@ja, '親切', 'しんせつ', 'shinsetsu', 'ADJ', 'N4', 'A2', 218, 'tử tế', 'kind'),
(@ja, '簡単', 'かんたん', 'kantan', 'ADJ', 'N4', 'A2', 219, 'đơn giản', 'simple'),
(@ja, '危険', 'きけん', 'kiken', 'ADJ', 'N4', 'A2', 220, 'nguy hiểm', 'dangerous'),
(@ja, '機会', 'きかい', 'kikai', 'NOUN', 'N4', 'A2', 221, 'cơ hội', 'chance'),
(@ja, '気分', 'きぶん', 'kibun', 'NOUN', 'N4', 'A2', 222, 'tâm trạng', 'mood'),
(@ja, '希望', 'きぼう', 'kibou', 'NOUN', 'N4', 'A2', 223, 'hy vọng', 'hope'),
(@ja, '急行', 'きゅうこう', 'kyuukou', 'NOUN', 'N4', 'A2', 224, 'tàu nhanh', 'express train'),
(@ja, '計画', 'けいかく', 'keikaku', 'NOUN', 'N4', 'A2', 225, 'kế hoạch', 'plan'),
(@ja, '経済', 'けいざい', 'keizai', 'NOUN', 'N4', 'A2', 226, 'kinh tế', 'economy'),
(@ja, '景色', 'けしき', 'keshiki', 'NOUN', 'N4', 'A2', 227, 'phong cảnh', 'scenery'),
(@ja, '結果', 'けっか', 'kekka', 'NOUN', 'N4', 'A2', 228, 'kết quả', 'result'),
(@ja, '結婚', 'けっこん', 'kekkon', 'NOUN', 'N4', 'A2', 229, 'kết hôn', 'marriage'),
(@ja, '原因', 'げんいん', 'genin', 'NOUN', 'N4', 'A2', 230, 'nguyên nhân', 'cause'),
(@ja, '故障', 'こしょう', 'koshou', 'NOUN', 'N4', 'A2', 231, 'hỏng hóc', 'breakdown'),
(@ja, '今度', 'こんど', 'kondo', 'NOUN', 'N4', 'A2', 232, 'lần này, lần tới', 'this time, next time'),
(@ja, '事故', 'じこ', 'jiko', 'NOUN', 'N4', 'A2', 233, 'tai nạn', 'accident'),
(@ja, '地震', 'じしん', 'jishin', 'NOUN', 'N4', 'A2', 234, 'động đất', 'earthquake'),
(@ja, '時代', 'じだい', 'jidai', 'NOUN', 'N4', 'A2', 235, 'thời đại', 'era'),
(@ja, '失敗', 'しっぱい', 'shippai', 'NOUN', 'N4', 'A2', 236, 'thất bại', 'failure'),
(@ja, '社会', 'しゃかい', 'shakai', 'NOUN', 'N4', 'A2', 237, 'xã hội', 'society'),
(@ja, '住所', 'じゅうしょ', 'juusho', 'NOUN', 'N4', 'A2', 238, 'địa chỉ', 'address'),
(@ja, '招待', 'しょうたい', 'shoutai', 'NOUN', 'N4', 'A2', 239, 'lời mời', 'invitation'),
(@ja, '将来', 'しょうらい', 'shourai', 'NOUN', 'N4', 'A2', 240, 'tương lai', 'future'),
(@ja, '人口', 'じんこう', 'jinkou', 'NOUN', 'N4', 'A2', 241, 'dân số', 'population'),
(@ja, '生活', 'せいかつ', 'seikatsu', 'NOUN', 'N4', 'A2', 242, 'cuộc sống', 'life'),
(@ja, '世界', 'せかい', 'sekai', 'NOUN', 'N4', 'A2', 243, 'thế giới', 'world'),
(@ja, '専門', 'せんもん', 'senmon', 'NOUN', 'N4', 'A2', 244, 'chuyên môn', 'specialty'),
(@ja, '相談', 'そうだん', 'soudan', 'NOUN', 'N4', 'A2', 245, 'tham vấn', 'consultation'),
(@ja, '退院', 'たいいん', 'taiin', 'NOUN', 'N4', 'A2', 246, 'xuất viện', 'leave hospital'),
(@ja, '大学', 'だいがく', 'daigaku', 'NOUN', 'N4', 'A2', 247, 'đại học', 'university'),
(@ja, '台風', 'たいふう', 'taifuu', 'NOUN', 'N4', 'A2', 248, 'bão', 'typhoon'),
(@ja, '違い', 'ちがい', 'chigai', 'NOUN', 'N4', 'A2', 249, 'sự khác biệt', 'difference'),
(@ja, '注意', 'ちゅうい', 'chuui', 'NOUN', 'N4', 'A2', 250, 'chú ý', 'attention'),
(@ja, '都合', 'つごう', 'tsugou', 'NOUN', 'N4', 'A2', 251, 'sự thuận tiện', 'convenience'),
(@ja, '都市', 'とし', 'toshi', 'NOUN', 'N4', 'A2', 252, 'thành phố', 'city'),
(@ja, '途中', 'とちゅう', 'tochuu', 'NOUN', 'N4', 'A2', 253, 'giữa đường', 'on the way'),
(@ja, '内容', 'ないよう', 'naiyou', 'NOUN', 'N4', 'A2', 254, 'nội dung', 'contents'),
(@ja, '値段', 'ねだん', 'nedan', 'NOUN', 'N4', 'A2', 255, 'giá cả', 'price'),
(@ja, '熱', 'ねつ', 'netsu', 'NOUN', 'N4', 'A2', 256, 'sốt, nhiệt', 'fever, heat'),
(@ja, '場合', 'ばあい', 'baai', 'NOUN', 'N4', 'A2', 257, 'trường hợp', 'case'),
(@ja, '場所', 'ばしょ', 'basho', 'NOUN', 'N4', 'A2', 258, 'địa điểm', 'place'),
(@ja, '番組', 'ばんぐみ', 'bangumi', 'NOUN', 'N4', 'A2', 259, 'chương trình TV', 'TV program'),
(@ja, '美術館', 'びじゅつかん', 'bijutsukan', 'NOUN', 'N4', 'A2', 260, 'bảo tàng nghệ thuật', 'art museum'),
(@ja, '必要', 'ひつよう', 'hitsuyou', 'ADJ', 'N4', 'A2', 261, 'cần thiết', 'necessary'),
(@ja, '不便', 'ふべん', 'fuben', 'ADJ', 'N4', 'A2', 262, 'bất tiện', 'inconvenient'),
(@ja, '文化', 'ぶんか', 'bunka', 'NOUN', 'N4', 'A2', 263, 'văn hóa', 'culture'),
(@ja, '文学', 'ぶんがく', 'bungaku', 'NOUN', 'N4', 'A2', 264, 'văn học', 'literature'),
(@ja, '貿易', 'ぼうえき', 'boueki', 'NOUN', 'N4', 'A2', 265, 'thương mại', 'trade'),
(@ja, '法律', 'ほうりつ', 'houritsu', 'NOUN', 'N4', 'A2', 266, 'pháp luật', 'law'),
(@ja, '翻訳', 'ほんやく', 'honyaku', 'NOUN', 'N4', 'A2', 267, 'dịch thuật', 'translation'),
(@ja, '間違い', 'まちがい', 'machigai', 'NOUN', 'N4', 'A2', 268, 'sai lầm', 'mistake'),
(@ja, '味', 'あじ', 'aji', 'NOUN', 'N4', 'A2', 269, 'vị', 'taste'),
(@ja, '昔', 'むかし', 'mukashi', 'NOUN', 'N4', 'A2', 270, 'ngày xưa', 'long ago'),
(@ja, '迷惑', 'めいわく', 'meiwaku', 'NOUN', 'N4', 'A2', 271, 'phiền hà', 'trouble'),
(@ja, '目的', 'もくてき', 'mokuteki', 'NOUN', 'N4', 'A2', 272, 'mục đích', 'purpose'),
(@ja, '約束', 'やくそく', 'yakusoku', 'NOUN', 'N4', 'A2', 273, 'lời hứa', 'promise'),
(@ja, '夕方', 'ゆうがた', 'yuugata', 'NOUN', 'N4', 'A2', 274, 'chiều tối', 'evening'),
(@ja, '用事', 'ようじ', 'youji', 'NOUN', 'N4', 'A2', 275, 'việc cần làm', 'errand'),
(@ja, '予定', 'よてい', 'yotei', 'NOUN', 'N4', 'A2', 276, 'dự định', 'schedule'),
(@ja, '理由', 'りゆう', 'riyuu', 'NOUN', 'N4', 'A2', 277, 'lý do', 'reason'),
(@ja, '料金', 'りょうきん', 'ryoukin', 'NOUN', 'N4', 'A2', 278, 'phí', 'fee'),
(@ja, '連絡', 'れんらく', 'renraku', 'NOUN', 'N4', 'A2', 279, 'liên lạc', 'contact');

-- ========== JLPT N3 - Extended (~80 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '相手', 'あいて', 'aite', 'NOUN', 'N3', 'B1', 400, 'đối phương', 'partner, opponent'),
(@ja, '改めて', 'あらためて', 'aratamete', 'ADV', 'N3', 'B1', 401, 'lại lần nữa', 'again'),
(@ja, '一般', 'いっぱん', 'ippan', 'NOUN', 'N3', 'B1', 402, 'thông thường', 'general'),
(@ja, '違反', 'いはん', 'ihan', 'NOUN', 'N3', 'B1', 403, 'vi phạm', 'violation'),
(@ja, '印象', 'いんしょう', 'inshou', 'NOUN', 'N3', 'B1', 404, 'ấn tượng', 'impression'),
(@ja, '影響', 'えいきょう', 'eikyou', 'NOUN', 'N3', 'B1', 405, 'ảnh hưởng', 'influence'),
(@ja, '応援', 'おうえん', 'ouen', 'NOUN', 'N3', 'B1', 406, 'cổ vũ', 'support'),
(@ja, '思い出す', 'おもいだす', 'omoidasu', 'VERB', 'N3', 'B1', 407, 'nhớ ra', 'to recall'),
(@ja, '解決', 'かいけつ', 'kaiketsu', 'NOUN', 'N3', 'B1', 408, 'giải quyết', 'solution'),
(@ja, '改善', 'かいぜん', 'kaizen', 'NOUN', 'N3', 'B1', 409, 'cải thiện', 'improvement'),
(@ja, '回復', 'かいふく', 'kaifuku', 'NOUN', 'N3', 'B1', 410, 'phục hồi', 'recovery'),
(@ja, '科学', 'かがく', 'kagaku', 'NOUN', 'N3', 'B1', 411, 'khoa học', 'science'),
(@ja, '確認', 'かくにん', 'kakunin', 'NOUN', 'N3', 'B1', 412, 'xác nhận', 'confirmation'),
(@ja, '価値', 'かち', 'kachi', 'NOUN', 'N3', 'B1', 413, 'giá trị', 'value'),
(@ja, '活動', 'かつどう', 'katsudou', 'NOUN', 'N3', 'B1', 414, 'hoạt động', 'activity'),
(@ja, '我慢', 'がまん', 'gaman', 'NOUN', 'N3', 'B1', 415, 'chịu đựng', 'patience'),
(@ja, '感覚', 'かんかく', 'kankaku', 'NOUN', 'N3', 'B1', 416, 'cảm giác', 'sensation'),
(@ja, '関係', 'かんけい', 'kankei', 'NOUN', 'N3', 'B1', 417, 'quan hệ', 'relationship'),
(@ja, '観光', 'かんこう', 'kankou', 'NOUN', 'N3', 'B1', 418, 'du lịch', 'sightseeing'),
(@ja, '感謝', 'かんしゃ', 'kansha', 'NOUN', 'N3', 'B1', 419, 'cảm ơn', 'gratitude'),
(@ja, '完成', 'かんせい', 'kansei', 'NOUN', 'N3', 'B1', 420, 'hoàn thành', 'completion'),
(@ja, '感想', 'かんそう', 'kansou', 'NOUN', 'N3', 'B1', 421, 'cảm tưởng', 'impressions'),
(@ja, '感動', 'かんどう', 'kandou', 'NOUN', 'N3', 'B1', 422, 'cảm động', 'being moved'),
(@ja, '記憶', 'きおく', 'kioku', 'NOUN', 'N3', 'B1', 423, 'ký ức', 'memory'),
(@ja, '期間', 'きかん', 'kikan', 'NOUN', 'N3', 'B1', 424, 'thời kỳ', 'period'),
(@ja, '記事', 'きじ', 'kiji', 'NOUN', 'N3', 'B1', 425, 'bài báo', 'article'),
(@ja, '技術', 'ぎじゅつ', 'gijutsu', 'NOUN', 'N3', 'B1', 426, 'kỹ thuật', 'technology'),
(@ja, '基本', 'きほん', 'kihon', 'NOUN', 'N3', 'B1', 427, 'cơ bản', 'basics'),
(@ja, '休日', 'きゅうじつ', 'kyuujitsu', 'NOUN', 'N3', 'B1', 428, 'ngày nghỉ', 'holiday'),
(@ja, '行事', 'ぎょうじ', 'gyouji', 'NOUN', 'N3', 'B1', 429, 'sự kiện', 'event'),
(@ja, '緊張', 'きんちょう', 'kinchou', 'NOUN', 'N3', 'B1', 430, 'căng thẳng', 'tension'),
(@ja, '空気', 'くうき', 'kuuki', 'NOUN', 'N3', 'B1', 431, 'không khí', 'air'),
(@ja, '苦労', 'くろう', 'kurou', 'NOUN', 'N3', 'B1', 432, 'vất vả', 'hardships'),
(@ja, '訓練', 'くんれん', 'kunren', 'NOUN', 'N3', 'B1', 433, 'huấn luyện', 'training'),
(@ja, '経営', 'けいえい', 'keiei', 'NOUN', 'N3', 'B1', 434, 'kinh doanh', 'management'),
(@ja, '欠席', 'けっせき', 'kesseki', 'NOUN', 'N3', 'B1', 435, 'vắng mặt', 'absence'),
(@ja, '見学', 'けんがく', 'kengaku', 'NOUN', 'N3', 'B1', 436, 'tham quan', 'study tour'),
(@ja, '健康', 'けんこう', 'kenkou', 'NOUN', 'N3', 'B1', 437, 'sức khỏe', 'health'),
(@ja, '言語', 'げんご', 'gengo', 'NOUN', 'N3', 'B1', 438, 'ngôn ngữ', 'language'),
(@ja, '現在', 'げんざい', 'genzai', 'NOUN', 'N3', 'B1', 439, 'hiện tại', 'now'),
(@ja, '現実', 'げんじつ', 'genjitsu', 'NOUN', 'N3', 'B1', 440, 'hiện thực', 'reality'),
(@ja, '効果', 'こうか', 'kouka', 'NOUN', 'N3', 'B1', 441, 'hiệu quả', 'effect'),
(@ja, '工事', 'こうじ', 'kouji', 'NOUN', 'N3', 'B1', 442, 'thi công', 'construction'),
(@ja, '構造', 'こうぞう', 'kouzou', 'NOUN', 'N3', 'B1', 443, 'cấu trúc', 'structure'),
(@ja, '行動', 'こうどう', 'koudou', 'NOUN', 'N3', 'B1', 444, 'hành động', 'action'),
(@ja, '公平', 'こうへい', 'kouhei', 'ADJ', 'N3', 'B1', 445, 'công bằng', 'fair'),
(@ja, '個人', 'こじん', 'kojin', 'NOUN', 'N3', 'B1', 446, 'cá nhân', 'individual'),
(@ja, '混乱', 'こんらん', 'konran', 'NOUN', 'N3', 'B1', 447, 'hỗn loạn', 'confusion'),
(@ja, '差', 'さ', 'sa', 'NOUN', 'N3', 'B1', 448, 'sự khác', 'difference'),
(@ja, '最近', 'さいきん', 'saikin', 'NOUN', 'N3', 'B1', 449, 'gần đây', 'recently'),
(@ja, '才能', 'さいのう', 'sainou', 'NOUN', 'N3', 'B1', 450, 'tài năng', 'talent'),
(@ja, '作業', 'さぎょう', 'sagyou', 'NOUN', 'N3', 'B1', 451, 'công việc, thao tác', 'task'),
(@ja, '参加', 'さんか', 'sanka', 'NOUN', 'N3', 'B1', 452, 'tham gia', 'participation'),
(@ja, '産業', 'さんぎょう', 'sangyou', 'NOUN', 'N3', 'B1', 453, 'công nghiệp', 'industry'),
(@ja, '指示', 'しじ', 'shiji', 'NOUN', 'N3', 'B1', 454, 'chỉ thị', 'instruction'),
(@ja, '事実', 'じじつ', 'jijitsu', 'NOUN', 'N3', 'B1', 455, 'sự thật', 'fact'),
(@ja, '自然', 'しぜん', 'shizen', 'NOUN', 'N3', 'B1', 456, 'tự nhiên', 'nature'),
(@ja, '実験', 'じっけん', 'jikken', 'NOUN', 'N3', 'B1', 457, 'thí nghiệm', 'experiment'),
(@ja, '実際', 'じっさい', 'jissai', 'NOUN', 'N3', 'B1', 458, 'thực tế', 'practical'),
(@ja, '実力', 'じつりょく', 'jitsuryoku', 'NOUN', 'N3', 'B1', 459, 'thực lực', 'real ability'),
(@ja, '指導', 'しどう', 'shidou', 'NOUN', 'N3', 'B1', 460, 'hướng dẫn', 'instruction'),
(@ja, '集中', 'しゅうちゅう', 'shuuchuu', 'NOUN', 'N3', 'B1', 461, 'tập trung', 'concentration'),
(@ja, '主張', 'しゅちょう', 'shuchou', 'NOUN', 'N3', 'B1', 462, 'chủ trương', 'assertion'),
(@ja, '出席', 'しゅっせき', 'shusseki', 'NOUN', 'N3', 'B1', 463, 'có mặt', 'attendance'),
(@ja, '受験', 'じゅけん', 'juken', 'NOUN', 'N3', 'B1', 464, 'thi tuyển', 'taking exam'),
(@ja, '主義', 'しゅぎ', 'shugi', 'NOUN', 'N3', 'B1', 465, 'chủ nghĩa', 'principle'),
(@ja, '種類', 'しゅるい', 'shurui', 'NOUN', 'N3', 'B1', 466, 'loại', 'kind'),
(@ja, '消費', 'しょうひ', 'shouhi', 'NOUN', 'N3', 'B1', 467, 'tiêu thụ', 'consumption'),
(@ja, '商品', 'しょうひん', 'shouhin', 'NOUN', 'N3', 'B1', 468, 'hàng hóa', 'goods'),
(@ja, '情報', 'じょうほう', 'jouhou', 'NOUN', 'N3', 'B1', 469, 'thông tin', 'information'),
(@ja, '職業', 'しょくぎょう', 'shokugyou', 'NOUN', 'N3', 'B1', 470, 'nghề nghiệp', 'occupation'),
(@ja, '進学', 'しんがく', 'shingaku', 'NOUN', 'N3', 'B1', 471, 'lên cấp học', 'entering higher school'),
(@ja, '人生', 'じんせい', 'jinsei', 'NOUN', 'N3', 'B1', 472, 'cuộc đời', 'life'),
(@ja, '心配', 'しんぱい', 'shinpai', 'NOUN', 'N3', 'B1', 473, 'lo lắng', 'worry'),
(@ja, '進歩', 'しんぽ', 'shinpo', 'NOUN', 'N3', 'B1', 474, 'tiến bộ', 'progress'),
(@ja, '信頼', 'しんらい', 'shinrai', 'NOUN', 'N3', 'B1', 475, 'tin tưởng', 'trust'),
(@ja, '推測', 'すいそく', 'suisoku', 'NOUN', 'N3', 'B1', 476, 'suy đoán', 'guess'),
(@ja, '生命', 'せいめい', 'seimei', 'NOUN', 'N3', 'B1', 477, 'sinh mệnh', 'life'),
(@ja, '責任', 'せきにん', 'sekinin', 'NOUN', 'N3', 'B1', 478, 'trách nhiệm', 'responsibility'),
(@ja, '節約', 'せつやく', 'setsuyaku', 'NOUN', 'N3', 'B1', 479, 'tiết kiệm', 'saving');

-- ========== JLPT N2 - Extended (~60 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '哀れ', 'あわれ', 'aware', 'ADJ', 'N2', 'B2', 600, 'tội nghiệp', 'pitiful'),
(@ja, '握手', 'あくしゅ', 'akushu', 'NOUN', 'N2', 'B2', 601, 'bắt tay', 'handshake'),
(@ja, '悪化', 'あっか', 'akka', 'NOUN', 'N2', 'B2', 602, 'xấu đi', 'worsening'),
(@ja, '圧力', 'あつりょく', 'atsuryoku', 'NOUN', 'N2', 'B2', 603, 'áp lực', 'pressure'),
(@ja, '安易', 'あんい', 'an_i', 'ADJ', 'N2', 'B2', 604, 'dễ dàng', 'easy'),
(@ja, '一致', 'いっち', 'icchi', 'NOUN', 'N2', 'B2', 605, 'phù hợp', 'agreement'),
(@ja, '違反', 'いはん', 'ihan', 'NOUN', 'N2', 'B2', 606, 'vi phạm', 'violation'),
(@ja, '違法', 'いほう', 'ihou', 'ADJ', 'N2', 'B2', 607, 'phi pháp', 'illegal'),
(@ja, '依頼', 'いらい', 'irai', 'NOUN', 'N2', 'B2', 608, 'yêu cầu', 'request'),
(@ja, '医療', 'いりょう', 'iryou', 'NOUN', 'N2', 'B2', 609, 'y tế', 'medical care'),
(@ja, '異論', 'いろん', 'iron', 'NOUN', 'N2', 'B2', 610, 'ý kiến khác', 'objection'),
(@ja, '隠居', 'いんきょ', 'inkyo', 'NOUN', 'N2', 'B2', 611, 'ẩn cư', 'retirement'),
(@ja, '陰謀', 'いんぼう', 'inbou', 'NOUN', 'N2', 'B2', 612, 'âm mưu', 'plot'),
(@ja, '英雄', 'えいゆう', 'eiyuu', 'NOUN', 'N2', 'B2', 613, 'anh hùng', 'hero'),
(@ja, '営業', 'えいぎょう', 'eigyou', 'NOUN', 'N2', 'B2', 614, 'kinh doanh', 'business'),
(@ja, '映像', 'えいぞう', 'eizou', 'NOUN', 'N2', 'B2', 615, 'hình ảnh', 'image'),
(@ja, '演技', 'えんぎ', 'engi', 'NOUN', 'N2', 'B2', 616, 'diễn xuất', 'acting'),
(@ja, '延期', 'えんき', 'enki', 'NOUN', 'N2', 'B2', 617, 'hoãn', 'postponement'),
(@ja, '援助', 'えんじょ', 'enjo', 'NOUN', 'N2', 'B2', 618, 'viện trợ', 'aid'),
(@ja, '応募', 'おうぼ', 'oubo', 'NOUN', 'N2', 'B2', 619, 'ứng tuyển', 'application'),
(@ja, '汚染', 'おせん', 'osen', 'NOUN', 'N2', 'B2', 620, 'ô nhiễm', 'pollution'),
(@ja, '主に', 'おもに', 'omoni', 'ADV', 'N2', 'B2', 621, 'chủ yếu', 'mainly'),
(@ja, '温暖', 'おんだん', 'ondan', 'ADJ', 'N2', 'B2', 622, 'ấm áp', 'warm'),
(@ja, '解釈', 'かいしゃく', 'kaishaku', 'NOUN', 'N2', 'B2', 623, 'giải thích', 'interpretation'),
(@ja, '改正', 'かいせい', 'kaisei', 'NOUN', 'N2', 'B2', 624, 'sửa đổi', 'revision'),
(@ja, '怪しい', 'あやしい', 'ayashii', 'ADJ', 'N2', 'B2', 625, 'đáng ngờ', 'suspicious'),
(@ja, '抱える', 'かかえる', 'kakaeru', 'VERB', 'N2', 'B2', 626, 'ôm', 'to hold'),
(@ja, '輝く', 'かがやく', 'kagayaku', 'VERB', 'N2', 'B2', 627, 'sáng chói', 'to shine'),
(@ja, '隠す', 'かくす', 'kakusu', 'VERB', 'N2', 'B2', 628, 'che giấu', 'to hide'),
(@ja, '稼ぐ', 'かせぐ', 'kasegu', 'VERB', 'N2', 'B2', 629, 'kiếm tiền', 'to earn'),
(@ja, '勝手', 'かって', 'katte', 'ADJ', 'N2', 'B2', 630, 'tự ý', 'selfish'),
(@ja, '活躍', 'かつやく', 'katsuyaku', 'NOUN', 'N2', 'B2', 631, 'hoạt động tích cực', 'activity'),
(@ja, '可能性', 'かのうせい', 'kanousei', 'NOUN', 'N2', 'B2', 632, 'khả năng', 'possibility'),
(@ja, '我慢', 'がまん', 'gaman', 'NOUN', 'N2', 'B2', 633, 'nhẫn nại', 'endurance'),
(@ja, '気軽', 'きがる', 'kigaru', 'ADJ', 'N2', 'B2', 634, 'thoải mái', 'casually'),
(@ja, '貴重', 'きちょう', 'kichou', 'ADJ', 'N2', 'B2', 635, 'quý giá', 'precious'),
(@ja, '基準', 'きじゅん', 'kijun', 'NOUN', 'N2', 'B2', 636, 'tiêu chuẩn', 'standard'),
(@ja, '規則', 'きそく', 'kisoku', 'NOUN', 'N2', 'B2', 637, 'quy tắc', 'rule'),
(@ja, '気配', 'けはい', 'kehai', 'NOUN', 'N2', 'B2', 638, 'dấu hiệu', 'sign'),
(@ja, '貢献', 'こうけん', 'kouken', 'NOUN', 'N2', 'B2', 639, 'cống hiến', 'contribution'),
(@ja, '広告', 'こうこく', 'koukoku', 'NOUN', 'N2', 'B2', 640, 'quảng cáo', 'advertisement'),
(@ja, '交渉', 'こうしょう', 'koushou', 'NOUN', 'N2', 'B2', 641, 'đàm phán', 'negotiation'),
(@ja, '構成', 'こうせい', 'kousei', 'NOUN', 'N2', 'B2', 642, 'cấu trúc', 'composition'),
(@ja, '光景', 'こうけい', 'koukei', 'NOUN', 'N2', 'B2', 643, 'cảnh tượng', 'scene'),
(@ja, '効率', 'こうりつ', 'kouritsu', 'NOUN', 'N2', 'B2', 644, 'hiệu suất', 'efficiency'),
(@ja, '克服', 'こくふく', 'kokufuku', 'NOUN', 'N2', 'B2', 645, 'vượt qua', 'overcoming'),
(@ja, '混雑', 'こんざつ', 'konzatsu', 'NOUN', 'N2', 'B2', 646, 'đông đúc', 'congestion'),
(@ja, '財産', 'ざいさん', 'zaisan', 'NOUN', 'N2', 'B2', 647, 'tài sản', 'property'),
(@ja, '採用', 'さいよう', 'saiyou', 'NOUN', 'N2', 'B2', 648, 'tuyển dụng', 'employment'),
(@ja, '錯覚', 'さっかく', 'sakkaku', 'NOUN', 'N2', 'B2', 649, 'ảo giác', 'illusion'),
(@ja, '差別', 'さべつ', 'sabetsu', 'NOUN', 'N2', 'B2', 650, 'phân biệt đối xử', 'discrimination'),
(@ja, '産業', 'さんぎょう', 'sangyou', 'NOUN', 'N2', 'B2', 651, 'công nghiệp', 'industry'),
(@ja, '事件', 'じけん', 'jiken', 'NOUN', 'N2', 'B2', 652, 'sự kiện', 'incident'),
(@ja, '辞職', 'じしょく', 'jishoku', 'NOUN', 'N2', 'B2', 653, 'từ chức', 'resignation'),
(@ja, '実施', 'じっし', 'jisshi', 'NOUN', 'N2', 'B2', 654, 'thực hiện', 'enforcement'),
(@ja, '指摘', 'してき', 'shiteki', 'NOUN', 'N2', 'B2', 655, 'chỉ ra', 'pointing out'),
(@ja, '渋滞', 'じゅうたい', 'juutai', 'NOUN', 'N2', 'B2', 656, 'kẹt xe', 'traffic jam'),
(@ja, '柔軟', 'じゅうなん', 'juunan', 'ADJ', 'N2', 'B2', 657, 'mềm dẻo', 'flexible'),
(@ja, '需要', 'じゅよう', 'juyou', 'NOUN', 'N2', 'B2', 658, 'nhu cầu', 'demand'),
(@ja, '順番', 'じゅんばん', 'junban', 'NOUN', 'N2', 'B2', 659, 'thứ tự', 'turn'),
(@ja, '巡る', 'めぐる', 'meguru', 'VERB', 'N2', 'B2', 660, 'xoay quanh', 'to revolve'),
(@ja, '消極的', 'しょうきょくてき', 'shoukyokuteki', 'ADJ', 'N2', 'B2', 661, 'tiêu cực', 'passive');

-- ========== JLPT N1 - Extended (~50 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, jlpt_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@ja, '曖昧', 'あいまい', 'aimai', 'ADJ', 'N1', 'C1', 900, 'mơ hồ', 'vague'),
(@ja, '愛着', 'あいちゃく', 'aichaku', 'NOUN', 'N1', 'C1', 901, 'sự gắn bó', 'attachment'),
(@ja, '相次ぐ', 'あいつぐ', 'aitsugu', 'VERB', 'N1', 'C1', 902, 'liên tiếp', 'to follow in succession'),
(@ja, '青ざめる', 'あおざめる', 'aozameru', 'VERB', 'N1', 'C1', 903, 'tái mặt', 'to turn pale'),
(@ja, '崇める', 'あがめる', 'agameru', 'VERB', 'N1', 'C1', 904, 'tôn kính', 'to revere'),
(@ja, '足取り', 'あしどり', 'ashidori', 'NOUN', 'N1', 'C1', 905, 'bước chân', 'gait'),
(@ja, '焦る', 'あせる', 'aseru', 'VERB', 'N1', 'C1', 906, 'sốt ruột', 'to be impatient'),
(@ja, '値する', 'あたいする', 'ataisuru', 'VERB', 'N1', 'C1', 907, 'xứng đáng', 'to be worthy'),
(@ja, '当て', 'あて', 'ate', 'NOUN', 'N1', 'C1', 908, 'hi vọng', 'expectations'),
(@ja, '操る', 'あやつる', 'ayatsuru', 'VERB', 'N1', 'C1', 909, 'điều khiển', 'to manipulate'),
(@ja, '誤り', 'あやまり', 'ayamari', 'NOUN', 'N1', 'C1', 910, 'sai lầm', 'error'),
(@ja, '案じる', 'あんじる', 'anjiru', 'VERB', 'N1', 'C1', 911, 'lo lắng', 'to be anxious'),
(@ja, '依然', 'いぜん', 'izen', 'ADV', 'N1', 'C1', 912, 'vẫn', 'still'),
(@ja, '偽る', 'いつわる', 'itsuwaru', 'VERB', 'N1', 'C1', 913, 'lừa dối', 'to lie'),
(@ja, '挑む', 'いどむ', 'idomu', 'VERB', 'N1', 'C1', 914, 'thách thức', 'to challenge'),
(@ja, '営む', 'いとなむ', 'itonamu', 'VERB', 'N1', 'C1', 915, 'kinh doanh', 'to run a business'),
(@ja, '遺憾', 'いかん', 'ikan', 'NOUN', 'N1', 'C1', 916, 'tiếc nuối', 'regret'),
(@ja, '威厳', 'いげん', 'igen', 'NOUN', 'N1', 'C1', 917, 'uy nghiêm', 'dignity'),
(@ja, '異彩', 'いさい', 'isai', 'NOUN', 'N1', 'C1', 918, 'sự xuất sắc', 'distinction'),
(@ja, '畏敬', 'いけい', 'ikei', 'NOUN', 'N1', 'C1', 919, 'kính sợ', 'reverence'),
(@ja, '医薬品', 'いやくひん', 'iyakuhin', 'NOUN', 'N1', 'C1', 920, 'thuốc men', 'medicine'),
(@ja, '宇宙', 'うちゅう', 'uchuu', 'NOUN', 'N1', 'C1', 921, 'vũ trụ', 'universe'),
(@ja, '促す', 'うながす', 'unagasu', 'VERB', 'N1', 'C1', 922, 'thúc giục', 'to urge'),
(@ja, '羨ましい', 'うらやましい', 'urayamashii', 'ADJ', 'N1', 'C1', 923, 'ghen tị', 'enviable'),
(@ja, '老いる', 'おいる', 'oiru', 'VERB', 'N1', 'C1', 924, 'già đi', 'to grow old'),
(@ja, '臆病', 'おくびょう', 'okubyou', 'ADJ', 'N1', 'C1', 925, 'nhút nhát', 'cowardice'),
(@ja, '陥る', 'おちいる', 'ochiiru', 'VERB', 'N1', 'C1', 926, 'rơi vào', 'to fall into'),
(@ja, '思惑', 'おもわく', 'omowaku', 'NOUN', 'N1', 'C1', 927, 'dự đoán', 'expectation'),
(@ja, '及ぼす', 'およぼす', 'oyobosu', 'VERB', 'N1', 'C1', 928, 'gây ra', 'to exert'),
(@ja, '解消', 'かいしょう', 'kaishou', 'NOUN', 'N1', 'C1', 929, 'giải tỏa', 'cancellation'),
(@ja, '介入', 'かいにゅう', 'kainyuu', 'NOUN', 'N1', 'C1', 930, 'can thiệp', 'intervention'),
(@ja, '概念', 'がいねん', 'gainen', 'NOUN', 'N1', 'C1', 931, 'khái niệm', 'concept'),
(@ja, '革新', 'かくしん', 'kakushin', 'NOUN', 'N1', 'C1', 932, 'cải cách', 'innovation'),
(@ja, '葛藤', 'かっとう', 'kattou', 'NOUN', 'N1', 'C1', 933, 'mâu thuẫn', 'conflict'),
(@ja, '勘弁', 'かんべん', 'kanben', 'NOUN', 'N1', 'C1', 934, 'tha thứ', 'forgiveness'),
(@ja, '緩和', 'かんわ', 'kanwa', 'NOUN', 'N1', 'C1', 935, 'làm dịu', 'easing'),
(@ja, '危惧', 'きぐ', 'kigu', 'NOUN', 'N1', 'C1', 936, 'lo ngại', 'concern'),
(@ja, '帰属', 'きぞく', 'kizoku', 'NOUN', 'N1', 'C1', 937, 'thuộc về', 'belonging'),
(@ja, '機微', 'きび', 'kibi', 'NOUN', 'N1', 'C1', 938, 'tinh tế', 'subtleties'),
(@ja, '驚異', 'きょうい', 'kyoui', 'NOUN', 'N1', 'C1', 939, 'kỳ diệu', 'wonder'),
(@ja, '凝縮', 'ぎょうしゅく', 'gyoushuku', 'NOUN', 'N1', 'C1', 940, 'cô đặc', 'condensation'),
(@ja, '駆使', 'くし', 'kushi', 'NOUN', 'N1', 'C1', 941, 'sử dụng thành thạo', 'making full use of'),
(@ja, '苦悩', 'くのう', 'kunou', 'NOUN', 'N1', 'C1', 942, 'khổ não', 'distress'),
(@ja, '群衆', 'ぐんしゅう', 'gunshuu', 'NOUN', 'N1', 'C1', 943, 'đám đông', 'crowd'),
(@ja, '兼業', 'けんぎょう', 'kengyou', 'NOUN', 'N1', 'C1', 944, 'kiêm nghiệp', 'side business'),
(@ja, '謙虚', 'けんきょ', 'kenkyo', 'ADJ', 'N1', 'C1', 945, 'khiêm tốn', 'modest'),
(@ja, '権限', 'けんげん', 'kengen', 'NOUN', 'N1', 'C1', 946, 'quyền hạn', 'authority'),
(@ja, '献身', 'けんしん', 'kenshin', 'NOUN', 'N1', 'C1', 947, 'hiến thân', 'devotion'),
(@ja, '幻想', 'げんそう', 'gensou', 'NOUN', 'N1', 'C1', 948, 'ảo tưởng', 'illusion'),
(@ja, '傲慢', 'ごうまん', 'gouman', 'ADJ', 'N1', 'C1', 949, 'kiêu ngạo', 'arrogance'),
(@ja, '酷使', 'こくし', 'kokushi', 'NOUN', 'N1', 'C1', 950, 'lao động cực khổ', 'overworking');

-- ----- Word examples (Tatoeba-style) for N4-N1 -----
INSERT INTO word_examples (word_id, sentence, reading, translation, level_code, source) VALUES
((SELECT id FROM words WHERE `text`='機会' AND language_id=@ja LIMIT 1),
 'これは絶好の機会です。', 'これはぜっこうのきかいです。', 'Đây là cơ hội tuyệt vời.', 'N4', 'tatoeba'),
((SELECT id FROM words WHERE `text`='計画' AND language_id=@ja LIMIT 1),
 '来週の計画を立てましょう。', 'らいしゅうのけいかくをたてましょう。', 'Hãy lập kế hoạch cho tuần sau.', 'N4', 'tatoeba'),
((SELECT id FROM words WHERE `text`='影響' AND language_id=@ja LIMIT 1),
 '天気が農業に影響を与える。', 'てんきがのうぎょうにえいきょうをあたえる。', 'Thời tiết ảnh hưởng đến nông nghiệp.', 'N3', 'tatoeba'),
((SELECT id FROM words WHERE `text`='確認' AND language_id=@ja LIMIT 1),
 'メールの内容を確認してください。', 'めーるのないようをかくにんしてください。', 'Hãy xác nhận nội dung email.', 'N3', 'tatoeba'),
((SELECT id FROM words WHERE `text`='交渉' AND language_id=@ja LIMIT 1),
 '価格について交渉中です。', 'かかくについてこうしょうちゅうです。', 'Đang đàm phán về giá.', 'N2', 'tatoeba'),
((SELECT id FROM words WHERE `text`='可能性' AND language_id=@ja LIMIT 1),
 '雨の可能性が高い。', 'あめのかのうせいがたかい。', 'Khả năng mưa rất cao.', 'N2', 'tatoeba'),
((SELECT id FROM words WHERE `text`='概念' AND language_id=@ja LIMIT 1),
 '彼はこの概念を理解できない。', 'かれはこのがいねんをりかいできない。', 'Anh ấy không thể hiểu được khái niệm này.', 'N1', 'tatoeba'),
((SELECT id FROM words WHERE `text`='葛藤' AND language_id=@ja LIMIT 1),
 '彼女は心の葛藤を抱えている。', 'かのじょはこころのかっとうをかかえている。', 'Cô ấy đang đối diện với mâu thuẫn nội tâm.', 'N1', 'tatoeba');
