-- =====================================================
-- SEED EXT: Chinese HSK vocabulary - Extended
-- Sources: drkameleon/complete-hsk-vocabulary (CC0),
--          ivankra/hsk30, oetia/new-hsk-csv,
--          plaktos/hsk_csv, LiudmilaLV/json_hsk,
--          sawcordwell/HSK-Vocab
-- Adds: more HSK 1-6 (old) + HSK 3.0 hints (Levels 1-9)
-- =====================================================

SET NAMES utf8mb4;
SET @zh := (SELECT id FROM languages WHERE code='zh');

-- ========== HSK 1 - Extended (~80 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '看', 'kàn', 'kan', 'VERB', 'HSK1', 'A1', 100, 'xem, nhìn', 'to see, to look'),
(@zh, '听', 'tīng', 'ting', 'VERB', 'HSK1', 'A1', 101, 'nghe', 'to listen'),
(@zh, '说', 'shuō', 'shuo', 'VERB', 'HSK1', 'A1', 102, 'nói', 'to speak'),
(@zh, '读', 'dú', 'du', 'VERB', 'HSK1', 'A1', 103, 'đọc', 'to read'),
(@zh, '写', 'xiě', 'xie', 'VERB', 'HSK1', 'A1', 104, 'viết', 'to write'),
(@zh, '吃', 'chī', 'chi', 'VERB', 'HSK1', 'A1', 105, 'ăn', 'to eat'),
(@zh, '喝', 'hē', 'he', 'VERB', 'HSK1', 'A1', 106, 'uống', 'to drink'),
(@zh, '去', 'qù', 'qu', 'VERB', 'HSK1', 'A1', 107, 'đi', 'to go'),
(@zh, '来', 'lái', 'lai', 'VERB', 'HSK1', 'A1', 108, 'đến', 'to come'),
(@zh, '回', 'huí', 'hui', 'VERB', 'HSK1', 'A1', 109, 'quay về', 'to return'),
(@zh, '坐', 'zuò', 'zuo', 'VERB', 'HSK1', 'A1', 110, 'ngồi', 'to sit'),
(@zh, '住', 'zhù', 'zhu', 'VERB', 'HSK1', 'A1', 111, 'ở, sống', 'to live'),
(@zh, '工作', 'gōngzuò', 'gongzuo', 'VERB', 'HSK1', 'A1', 112, 'làm việc', 'to work'),
(@zh, '学习', 'xuéxí', 'xuexi', 'VERB', 'HSK1', 'A1', 113, 'học', 'to study'),
(@zh, '认识', 'rènshi', 'renshi', 'VERB', 'HSK1', 'A1', 114, 'quen biết', 'to know'),
(@zh, '叫', 'jiào', 'jiao', 'VERB', 'HSK1', 'A1', 115, 'gọi', 'to call'),
(@zh, '请', 'qǐng', 'qing', 'VERB', 'HSK1', 'A1', 116, 'mời', 'please'),
(@zh, '谢谢', 'xièxie', 'xiexie', 'PHRASE', 'HSK1', 'A1', 117, 'cảm ơn', 'thank you'),
(@zh, '不客气', 'bú kèqi', 'bukeqi', 'PHRASE', 'HSK1', 'A1', 118, 'không có gì', 'you are welcome'),
(@zh, '对不起', 'duìbuqǐ', 'duibuqi', 'PHRASE', 'HSK1', 'A1', 119, 'xin lỗi', 'sorry'),
(@zh, '没关系', 'méi guānxi', 'meiguanxi', 'PHRASE', 'HSK1', 'A1', 120, 'không sao', 'never mind'),
(@zh, '再见', 'zàijiàn', 'zaijian', 'PHRASE', 'HSK1', 'A1', 121, 'tạm biệt', 'goodbye'),
(@zh, '你好', 'nǐ hǎo', 'nihao', 'PHRASE', 'HSK1', 'A1', 122, 'xin chào', 'hello'),
(@zh, '什么', 'shénme', 'shenme', 'PRON', 'HSK1', 'A1', 123, 'cái gì', 'what'),
(@zh, '哪儿', 'nǎr', 'nar', 'PRON', 'HSK1', 'A1', 124, 'đâu', 'where'),
(@zh, '谁', 'shéi', 'shei', 'PRON', 'HSK1', 'A1', 125, 'ai', 'who'),
(@zh, '怎么', 'zěnme', 'zenme', 'PRON', 'HSK1', 'A1', 126, 'làm thế nào', 'how'),
(@zh, '多少', 'duōshao', 'duoshao', 'PRON', 'HSK1', 'A1', 127, 'bao nhiêu', 'how many/much'),
(@zh, '几', 'jǐ', 'ji', 'PRON', 'HSK1', 'A1', 128, 'mấy', 'how many'),
(@zh, '一', 'yī', 'yi', 'NUM', 'HSK1', 'A1', 129, 'một', 'one'),
(@zh, '二', 'èr', 'er', 'NUM', 'HSK1', 'A1', 130, 'hai', 'two'),
(@zh, '三', 'sān', 'san', 'NUM', 'HSK1', 'A1', 131, 'ba', 'three'),
(@zh, '四', 'sì', 'si', 'NUM', 'HSK1', 'A1', 132, 'bốn', 'four'),
(@zh, '五', 'wǔ', 'wu', 'NUM', 'HSK1', 'A1', 133, 'năm', 'five'),
(@zh, '六', 'liù', 'liu', 'NUM', 'HSK1', 'A1', 134, 'sáu', 'six'),
(@zh, '七', 'qī', 'qi', 'NUM', 'HSK1', 'A1', 135, 'bảy', 'seven'),
(@zh, '八', 'bā', 'ba', 'NUM', 'HSK1', 'A1', 136, 'tám', 'eight'),
(@zh, '九', 'jiǔ', 'jiu', 'NUM', 'HSK1', 'A1', 137, 'chín', 'nine'),
(@zh, '十', 'shí', 'shi', 'NUM', 'HSK1', 'A1', 138, 'mười', 'ten'),
(@zh, '零', 'líng', 'ling', 'NUM', 'HSK1', 'A1', 139, 'không', 'zero'),
(@zh, '块', 'kuài', 'kuai', 'NOUN', 'HSK1', 'A1', 140, 'tệ (đơn vị tiền)', 'yuan'),
(@zh, '点', 'diǎn', 'dian', 'NOUN', 'HSK1', 'A1', 141, 'giờ', 'oclock, point'),
(@zh, '现在', 'xiànzài', 'xianzai', 'NOUN', 'HSK1', 'A1', 142, 'bây giờ', 'now'),
(@zh, '上午', 'shàngwǔ', 'shangwu', 'NOUN', 'HSK1', 'A1', 143, 'buổi sáng', 'morning'),
(@zh, '中午', 'zhōngwǔ', 'zhongwu', 'NOUN', 'HSK1', 'A1', 144, 'buổi trưa', 'noon'),
(@zh, '下午', 'xiàwǔ', 'xiawu', 'NOUN', 'HSK1', 'A1', 145, 'buổi chiều', 'afternoon'),
(@zh, '晚上', 'wǎnshang', 'wanshang', 'NOUN', 'HSK1', 'A1', 146, 'buổi tối', 'evening'),
(@zh, '年', 'nián', 'nian', 'NOUN', 'HSK1', 'A1', 147, 'năm', 'year'),
(@zh, '月', 'yuè', 'yue', 'NOUN', 'HSK1', 'A1', 148, 'tháng', 'month'),
(@zh, '日', 'rì', 'ri', 'NOUN', 'HSK1', 'A1', 149, 'ngày', 'day'),
(@zh, '号', 'hào', 'hao', 'NOUN', 'HSK1', 'A1', 150, 'số (ngày)', 'date number'),
(@zh, '星期', 'xīngqī', 'xingqi', 'NOUN', 'HSK1', 'A1', 151, 'tuần', 'week'),
(@zh, '苹果', 'píngguǒ', 'pingguo', 'NOUN', 'HSK1', 'A1', 152, 'táo', 'apple'),
(@zh, '茶', 'chá', 'cha', 'NOUN', 'HSK1', 'A1', 153, 'trà', 'tea'),
(@zh, '米饭', 'mǐfàn', 'mifan', 'NOUN', 'HSK1', 'A1', 154, 'cơm', 'cooked rice'),
(@zh, '菜', 'cài', 'cai', 'NOUN', 'HSK1', 'A1', 155, 'rau, món ăn', 'dish'),
(@zh, '杯子', 'bēizi', 'beizi', 'NOUN', 'HSK1', 'A1', 156, 'cái cốc', 'cup'),
(@zh, '钱', 'qián', 'qian', 'NOUN', 'HSK1', 'A1', 157, 'tiền', 'money'),
(@zh, '飞机', 'fēijī', 'feiji', 'NOUN', 'HSK1', 'A1', 158, 'máy bay', 'airplane'),
(@zh, '出租车', 'chūzūchē', 'chuzuche', 'NOUN', 'HSK1', 'A1', 159, 'taxi', 'taxi'),
(@zh, '电视', 'diànshì', 'dianshi', 'NOUN', 'HSK1', 'A1', 160, 'tivi', 'TV'),
(@zh, '电脑', 'diànnǎo', 'diannao', 'NOUN', 'HSK1', 'A1', 161, 'máy tính', 'computer'),
(@zh, '电影', 'diànyǐng', 'dianying', 'NOUN', 'HSK1', 'A1', 162, 'phim', 'movie'),
(@zh, '书', 'shū', 'shu', 'NOUN', 'HSK1', 'A1', 163, 'sách', 'book'),
(@zh, '汉语', 'Hànyǔ', 'hanyu', 'NOUN', 'HSK1', 'A1', 164, 'tiếng Hán', 'Chinese language'),
(@zh, '字', 'zì', 'zi', 'NOUN', 'HSK1', 'A1', 165, 'chữ', 'character'),
(@zh, '名字', 'míngzi', 'mingzi', 'NOUN', 'HSK1', 'A1', 166, 'tên', 'name'),
(@zh, '小', 'xiǎo', 'xiao', 'ADJ', 'HSK1', 'A1', 167, 'nhỏ', 'small'),
(@zh, '大', 'dà', 'da', 'ADJ', 'HSK1', 'A1', 168, 'lớn', 'big'),
(@zh, '多', 'duō', 'duo', 'ADJ', 'HSK1', 'A1', 169, 'nhiều', 'many'),
(@zh, '少', 'shǎo', 'shao', 'ADJ', 'HSK1', 'A1', 170, 'ít', 'few'),
(@zh, '冷', 'lěng', 'leng', 'ADJ', 'HSK1', 'A1', 171, 'lạnh', 'cold'),
(@zh, '热', 'rè', 're', 'ADJ', 'HSK1', 'A1', 172, 'nóng', 'hot'),
(@zh, '高兴', 'gāoxìng', 'gaoxing', 'ADJ', 'HSK1', 'A1', 173, 'vui', 'happy'),
(@zh, '漂亮', 'piàoliang', 'piaoliang', 'ADJ', 'HSK1', 'A1', 174, 'đẹp', 'pretty'),
(@zh, '好', 'hǎo', 'hao', 'ADJ', 'HSK1', 'A1', 175, 'tốt', 'good'),
(@zh, '在', 'zài', 'zai', 'PARTICLE', 'HSK1', 'A1', 176, 'ở, đang', 'at, in'),
(@zh, '和', 'hé', 'he', 'CONJ', 'HSK1', 'A1', 177, 'và', 'and'),
(@zh, '的', 'de', 'de', 'PARTICLE', 'HSK1', 'A1', 178, 'của (sở hữu)', 'possessive'),
(@zh, '了', 'le', 'le', 'PARTICLE', 'HSK1', 'A1', 179, '(thì hoàn thành)', 'aspect marker'),
(@zh, '吗', 'ma', 'ma', 'PARTICLE', 'HSK1', 'A1', 180, '(nghi vấn)', 'question marker'),
(@zh, '呢', 'ne', 'ne', 'PARTICLE', 'HSK1', 'A1', 181, '(còn... thì sao)', 'particle'),
(@zh, '岁', 'suì', 'sui', 'NOUN', 'HSK1', 'A1', 182, 'tuổi', 'years old'),
(@zh, '本', 'běn', 'ben', 'NOUN', 'HSK1', 'A1', 183, '(quyển)', 'volume'),
(@zh, '个', 'gè', 'ge', 'NOUN', 'HSK1', 'A1', 184, '(cái, người)', 'general classifier');

-- ========== HSK 2 - Extended (~50 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '帮助', 'bāngzhù', 'bangzhu', 'VERB', 'HSK2', 'A2', 200, 'giúp đỡ', 'to help'),
(@zh, '别', 'bié', 'bie', 'ADV', 'HSK2', 'A2', 201, 'đừng', 'do not'),
(@zh, '宾馆', 'bīnguǎn', 'binguan', 'NOUN', 'HSK2', 'A2', 202, 'khách sạn', 'hotel'),
(@zh, '长', 'cháng', 'chang', 'ADJ', 'HSK2', 'A2', 203, 'dài', 'long'),
(@zh, '唱歌', 'chànggē', 'changge', 'VERB', 'HSK2', 'A2', 204, 'hát', 'to sing'),
(@zh, '出', 'chū', 'chu', 'VERB', 'HSK2', 'A2', 205, 'ra', 'to go out'),
(@zh, '穿', 'chuān', 'chuan', 'VERB', 'HSK2', 'A2', 206, 'mặc', 'to wear'),
(@zh, '次', 'cì', 'ci', 'NOUN', 'HSK2', 'A2', 207, 'lần', 'time'),
(@zh, '从', 'cóng', 'cong', 'PARTICLE', 'HSK2', 'A2', 208, 'từ', 'from'),
(@zh, '错', 'cuò', 'cuo', 'ADJ', 'HSK2', 'A2', 209, 'sai', 'wrong'),
(@zh, '打篮球', 'dǎ lánqiú', 'dalanqiu', 'VERB', 'HSK2', 'A2', 210, 'chơi bóng rổ', 'to play basketball'),
(@zh, '到', 'dào', 'dao', 'VERB', 'HSK2', 'A2', 211, 'đến', 'to arrive'),
(@zh, '得', 'děi', 'dei', 'VERB', 'HSK2', 'A2', 212, 'phải', 'must'),
(@zh, '等', 'děng', 'deng', 'VERB', 'HSK2', 'A2', 213, 'đợi', 'to wait'),
(@zh, '弟弟', 'dìdi', 'didi', 'NOUN', 'HSK2', 'A2', 214, 'em trai', 'younger brother'),
(@zh, '懂', 'dǒng', 'dong', 'VERB', 'HSK2', 'A2', 215, 'hiểu', 'to understand'),
(@zh, '对', 'duì', 'dui', 'ADJ', 'HSK2', 'A2', 216, 'đúng', 'correct'),
(@zh, '房间', 'fángjiān', 'fangjian', 'NOUN', 'HSK2', 'A2', 217, 'phòng', 'room'),
(@zh, '非常', 'fēicháng', 'feichang', 'ADV', 'HSK2', 'A2', 218, 'rất, vô cùng', 'extremely'),
(@zh, '服务员', 'fúwùyuán', 'fuwuyuan', 'NOUN', 'HSK2', 'A2', 219, 'nhân viên phục vụ', 'waiter'),
(@zh, '高', 'gāo', 'gao', 'ADJ', 'HSK2', 'A2', 220, 'cao', 'tall'),
(@zh, '告诉', 'gàosu', 'gaosu', 'VERB', 'HSK2', 'A2', 221, 'cho biết', 'to tell'),
(@zh, '哥哥', 'gēge', 'gege', 'NOUN', 'HSK2', 'A2', 222, 'anh trai', 'older brother'),
(@zh, '给', 'gěi', 'gei', 'VERB', 'HSK2', 'A2', 223, 'cho', 'to give'),
(@zh, '公共汽车', 'gōnggòng qìchē', 'gonggongqiche', 'NOUN', 'HSK2', 'A2', 224, 'xe buýt', 'bus'),
(@zh, '公司', 'gōngsī', 'gongsi', 'NOUN', 'HSK2', 'A2', 225, 'công ty', 'company'),
(@zh, '贵', 'guì', 'gui', 'ADJ', 'HSK2', 'A2', 226, 'đắt', 'expensive'),
(@zh, '过', 'guò', 'guo', 'VERB', 'HSK2', 'A2', 227, '(đã từng)', 'experiential'),
(@zh, '还', 'hái', 'hai', 'ADV', 'HSK2', 'A2', 228, 'còn, vẫn', 'still'),
(@zh, '孩子', 'háizi', 'haizi', 'NOUN', 'HSK2', 'A2', 229, 'đứa trẻ', 'child'),
(@zh, '红', 'hóng', 'hong', 'ADJ', 'HSK2', 'A2', 230, 'đỏ', 'red'),
(@zh, '火车站', 'huǒchēzhàn', 'huochezhan', 'NOUN', 'HSK2', 'A2', 231, 'ga tàu', 'train station'),
(@zh, '机场', 'jīchǎng', 'jichang', 'NOUN', 'HSK2', 'A2', 232, 'sân bay', 'airport'),
(@zh, '鸡蛋', 'jīdàn', 'jidan', 'NOUN', 'HSK2', 'A2', 233, 'trứng gà', 'egg'),
(@zh, '件', 'jiàn', 'jian', 'NOUN', 'HSK2', 'A2', 234, '(cái — đồ vật)', 'piece'),
(@zh, '教室', 'jiàoshì', 'jiaoshi', 'NOUN', 'HSK2', 'A2', 235, 'phòng học', 'classroom'),
(@zh, '姐姐', 'jiějie', 'jiejie', 'NOUN', 'HSK2', 'A2', 236, 'chị gái', 'older sister'),
(@zh, '介绍', 'jièshào', 'jieshao', 'VERB', 'HSK2', 'A2', 237, 'giới thiệu', 'to introduce'),
(@zh, '近', 'jìn', 'jin', 'ADJ', 'HSK2', 'A2', 238, 'gần', 'near'),
(@zh, '进', 'jìn', 'jin', 'VERB', 'HSK2', 'A2', 239, 'vào', 'to enter'),
(@zh, '就', 'jiù', 'jiu', 'ADV', 'HSK2', 'A2', 240, 'liền, ngay', 'just'),
(@zh, '咖啡', 'kāfēi', 'kafei', 'NOUN', 'HSK2', 'A2', 241, 'cà phê', 'coffee'),
(@zh, '开始', 'kāishǐ', 'kaishi', 'VERB', 'HSK2', 'A2', 242, 'bắt đầu', 'to begin'),
(@zh, '考试', 'kǎoshì', 'kaoshi', 'NOUN', 'HSK2', 'A2', 243, 'kỳ thi', 'exam'),
(@zh, '可能', 'kěnéng', 'keneng', 'VERB', 'HSK2', 'A2', 244, 'có thể', 'maybe'),
(@zh, '可以', 'kěyǐ', 'keyi', 'VERB', 'HSK2', 'A2', 245, 'có thể', 'can'),
(@zh, '快', 'kuài', 'kuai', 'ADJ', 'HSK2', 'A2', 246, 'nhanh', 'fast'),
(@zh, '快乐', 'kuàilè', 'kuaile', 'ADJ', 'HSK2', 'A2', 247, 'vui vẻ', 'happy'),
(@zh, '累', 'lèi', 'lei', 'ADJ', 'HSK2', 'A2', 248, 'mệt', 'tired'),
(@zh, '里', 'lǐ', 'li', 'NOUN', 'HSK2', 'A2', 249, 'bên trong', 'inside'),
(@zh, '路', 'lù', 'lu', 'NOUN', 'HSK2', 'A2', 250, 'đường', 'road'),
(@zh, '旅游', 'lǚyóu', 'lvyou', 'VERB', 'HSK2', 'A2', 251, 'du lịch', 'to travel');

-- ========== HSK 3 - Extended (~50 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '阿姨', 'āyí', 'ayi', 'NOUN', 'HSK3', 'B1', 300, 'cô, dì', 'auntie'),
(@zh, '啊', 'a', 'a', 'INTJ', 'HSK3', 'B1', 301, 'à', 'oh'),
(@zh, '矮', 'ǎi', 'ai', 'ADJ', 'HSK3', 'B1', 302, 'thấp', 'short (height)'),
(@zh, '爱好', 'àihào', 'aihao', 'NOUN', 'HSK3', 'B1', 303, 'sở thích', 'hobby'),
(@zh, '安静', 'ānjìng', 'anjing', 'ADJ', 'HSK3', 'B1', 304, 'yên tĩnh', 'quiet'),
(@zh, '把', 'bǎ', 'ba', 'PARTICLE', 'HSK3', 'B1', 305, '(cấu trúc 把)', 'preposition'),
(@zh, '班', 'bān', 'ban', 'NOUN', 'HSK3', 'B1', 306, 'lớp', 'class'),
(@zh, '搬', 'bān', 'ban', 'VERB', 'HSK3', 'B1', 307, 'chuyển, vác', 'to move'),
(@zh, '办法', 'bànfǎ', 'banfa', 'NOUN', 'HSK3', 'B1', 308, 'cách', 'way'),
(@zh, '办公室', 'bàngōngshì', 'bangongshi', 'NOUN', 'HSK3', 'B1', 309, 'văn phòng', 'office'),
(@zh, '半', 'bàn', 'ban', 'NUM', 'HSK3', 'B1', 310, 'một nửa', 'half'),
(@zh, '帮忙', 'bāngmáng', 'bangmang', 'VERB', 'HSK3', 'B1', 311, 'giúp đỡ', 'to help'),
(@zh, '包', 'bāo', 'bao', 'NOUN', 'HSK3', 'B1', 312, 'túi xách', 'bag'),
(@zh, '饱', 'bǎo', 'bao', 'ADJ', 'HSK3', 'B1', 313, 'no', 'full'),
(@zh, '北方', 'běifāng', 'beifang', 'NOUN', 'HSK3', 'B1', 314, 'phía bắc', 'north'),
(@zh, '被', 'bèi', 'bei', 'PARTICLE', 'HSK3', 'B1', 315, 'bị', 'passive marker'),
(@zh, '鼻子', 'bízi', 'bizi', 'NOUN', 'HSK3', 'B1', 316, 'mũi', 'nose'),
(@zh, '比较', 'bǐjiào', 'bijiao', 'ADV', 'HSK3', 'B1', 317, 'tương đối', 'relatively'),
(@zh, '比赛', 'bǐsài', 'bisai', 'NOUN', 'HSK3', 'B1', 318, 'thi đấu', 'competition'),
(@zh, '必须', 'bìxū', 'bixu', 'VERB', 'HSK3', 'B1', 319, 'bắt buộc', 'must'),
(@zh, '变化', 'biànhuà', 'bianhua', 'VERB', 'HSK3', 'B1', 320, 'thay đổi', 'to change'),
(@zh, '表示', 'biǎoshì', 'biaoshi', 'VERB', 'HSK3', 'B1', 321, 'biểu thị', 'to indicate'),
(@zh, '表演', 'biǎoyǎn', 'biaoyan', 'VERB', 'HSK3', 'B1', 322, 'biểu diễn', 'to perform'),
(@zh, '别人', 'biérén', 'bieren', 'PRON', 'HSK3', 'B1', 323, 'người khác', 'others'),
(@zh, '宾馆', 'bīnguǎn', 'binguan', 'NOUN', 'HSK3', 'B1', 324, 'khách sạn', 'hotel'),
(@zh, '冰箱', 'bīngxiāng', 'bingxiang', 'NOUN', 'HSK3', 'B1', 325, 'tủ lạnh', 'refrigerator'),
(@zh, '不但', 'búdàn', 'budan', 'CONJ', 'HSK3', 'B1', 326, 'không những', 'not only'),
(@zh, '菜单', 'càidān', 'caidan', 'NOUN', 'HSK3', 'B1', 327, 'thực đơn', 'menu'),
(@zh, '参加', 'cānjiā', 'canjia', 'VERB', 'HSK3', 'B1', 328, 'tham gia', 'to attend'),
(@zh, '草', 'cǎo', 'cao', 'NOUN', 'HSK3', 'B1', 329, 'cỏ', 'grass'),
(@zh, '层', 'céng', 'ceng', 'NOUN', 'HSK3', 'B1', 330, 'tầng', 'floor'),
(@zh, '差', 'chà', 'cha', 'ADJ', 'HSK3', 'B1', 331, 'kém', 'lacking'),
(@zh, '超市', 'chāoshì', 'chaoshi', 'NOUN', 'HSK3', 'B1', 332, 'siêu thị', 'supermarket'),
(@zh, '衬衫', 'chènshān', 'chenshan', 'NOUN', 'HSK3', 'B1', 333, 'áo sơ mi', 'shirt'),
(@zh, '成绩', 'chéngjì', 'chengji', 'NOUN', 'HSK3', 'B1', 334, 'thành tích', 'achievement'),
(@zh, '城市', 'chéngshì', 'chengshi', 'NOUN', 'HSK3', 'B1', 335, 'thành phố', 'city'),
(@zh, '迟到', 'chídào', 'chidao', 'VERB', 'HSK3', 'B1', 336, 'đến muộn', 'to be late'),
(@zh, '出现', 'chūxiàn', 'chuxian', 'VERB', 'HSK3', 'B1', 337, 'xuất hiện', 'to appear'),
(@zh, '厨房', 'chúfáng', 'chufang', 'NOUN', 'HSK3', 'B1', 338, 'nhà bếp', 'kitchen'),
(@zh, '春', 'chūn', 'chun', 'NOUN', 'HSK3', 'B1', 339, 'mùa xuân', 'spring'),
(@zh, '词典', 'cídiǎn', 'cidian', 'NOUN', 'HSK3', 'B1', 340, 'từ điển', 'dictionary'),
(@zh, '聪明', 'cōngming', 'congming', 'ADJ', 'HSK3', 'B1', 341, 'thông minh', 'clever'),
(@zh, '打扫', 'dǎsǎo', 'dasao', 'VERB', 'HSK3', 'B1', 342, 'quét dọn', 'to clean'),
(@zh, '打算', 'dǎsuàn', 'dasuan', 'VERB', 'HSK3', 'B1', 343, 'dự định', 'to plan'),
(@zh, '带', 'dài', 'dai', 'VERB', 'HSK3', 'B1', 344, 'mang', 'to bring'),
(@zh, '担心', 'dānxīn', 'danxin', 'VERB', 'HSK3', 'B1', 345, 'lo lắng', 'to worry'),
(@zh, '蛋糕', 'dàngāo', 'dangao', 'NOUN', 'HSK3', 'B1', 346, 'bánh ngọt', 'cake'),
(@zh, '当然', 'dāngrán', 'dangran', 'ADV', 'HSK3', 'B1', 347, 'đương nhiên', 'of course'),
(@zh, '地', 'de', 'de', 'PARTICLE', 'HSK3', 'B1', 348, '(trạng từ)', 'adverbial particle'),
(@zh, '灯', 'dēng', 'deng', 'NOUN', 'HSK3', 'B1', 349, 'đèn', 'lamp'),
(@zh, '地方', 'dìfāng', 'difang', 'NOUN', 'HSK3', 'B1', 350, 'nơi', 'place');

-- ========== HSK 5 - Extended (~50 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '哎', 'āi', 'ai', 'INTJ', 'HSK5', 'B2', 600, 'ơ, ôi', 'hey'),
(@zh, '爱护', 'àihù', 'aihu', 'VERB', 'HSK5', 'B2', 601, 'yêu quý', 'to cherish'),
(@zh, '爱惜', 'àixī', 'aixi', 'VERB', 'HSK5', 'B2', 602, 'tiếc rẻ', 'to treasure'),
(@zh, '安慰', 'ānwèi', 'anwei', 'VERB', 'HSK5', 'B2', 603, 'an ủi', 'to comfort'),
(@zh, '安装', 'ānzhuāng', 'anzhuang', 'VERB', 'HSK5', 'B2', 604, 'lắp đặt', 'to install'),
(@zh, '岸', 'àn', 'an', 'NOUN', 'HSK5', 'B2', 605, 'bờ', 'shore'),
(@zh, '把握', 'bǎwò', 'bawo', 'VERB', 'HSK5', 'B2', 606, 'nắm vững', 'to grasp'),
(@zh, '摆', 'bǎi', 'bai', 'VERB', 'HSK5', 'B2', 607, 'sắp xếp', 'to arrange'),
(@zh, '办理', 'bànlǐ', 'banli', 'VERB', 'HSK5', 'B2', 608, 'làm thủ tục', 'to handle'),
(@zh, '傍晚', 'bàngwǎn', 'bangwan', 'NOUN', 'HSK5', 'B2', 609, 'chiều tối', 'evening'),
(@zh, '包含', 'bāohán', 'baohan', 'VERB', 'HSK5', 'B2', 610, 'bao gồm', 'to contain'),
(@zh, '保持', 'bǎochí', 'baochi', 'VERB', 'HSK5', 'B2', 611, 'giữ', 'to maintain'),
(@zh, '保存', 'bǎocún', 'baocun', 'VERB', 'HSK5', 'B2', 612, 'bảo tồn', 'to preserve'),
(@zh, '保险', 'bǎoxiǎn', 'baoxian', 'NOUN', 'HSK5', 'B2', 613, 'bảo hiểm', 'insurance'),
(@zh, '报告', 'bàogào', 'baogao', 'NOUN', 'HSK5', 'B2', 614, 'báo cáo', 'report'),
(@zh, '抱怨', 'bàoyuàn', 'baoyuan', 'VERB', 'HSK5', 'B2', 615, 'phàn nàn', 'to complain'),
(@zh, '背景', 'bèijǐng', 'beijing', 'NOUN', 'HSK5', 'B2', 616, 'bối cảnh', 'background'),
(@zh, '比例', 'bǐlì', 'bili', 'NOUN', 'HSK5', 'B2', 617, 'tỷ lệ', 'proportion'),
(@zh, '彼此', 'bǐcǐ', 'bici', 'PRON', 'HSK5', 'B2', 618, 'lẫn nhau', 'each other'),
(@zh, '必然', 'bìrán', 'biran', 'ADJ', 'HSK5', 'B2', 619, 'tất nhiên', 'inevitable'),
(@zh, '必要', 'bìyào', 'biyao', 'ADJ', 'HSK5', 'B2', 620, 'cần thiết', 'necessary'),
(@zh, '编辑', 'biānjí', 'bianji', 'VERB', 'HSK5', 'B2', 621, 'biên tập', 'to edit'),
(@zh, '辩论', 'biànlùn', 'bianlun', 'VERB', 'HSK5', 'B2', 622, 'tranh luận', 'to debate'),
(@zh, '标志', 'biāozhì', 'biaozhi', 'NOUN', 'HSK5', 'B2', 623, 'biểu tượng', 'symbol'),
(@zh, '表面', 'biǎomiàn', 'biaomian', 'NOUN', 'HSK5', 'B2', 624, 'bề mặt', 'surface'),
(@zh, '表明', 'biǎomíng', 'biaoming', 'VERB', 'HSK5', 'B2', 625, 'biểu thị rõ', 'to make clear'),
(@zh, '冰激凌', 'bīngjīlíng', 'bingjiling', 'NOUN', 'HSK5', 'B2', 626, 'kem', 'ice cream'),
(@zh, '病毒', 'bìngdú', 'bingdu', 'NOUN', 'HSK5', 'B2', 627, 'virus', 'virus'),
(@zh, '播放', 'bōfàng', 'bofang', 'VERB', 'HSK5', 'B2', 628, 'phát sóng', 'to broadcast'),
(@zh, '不断', 'búduàn', 'buduan', 'ADV', 'HSK5', 'B2', 629, 'không ngừng', 'continuously'),
(@zh, '不见得', 'bú jiàndé', 'bujiande', 'PHRASE', 'HSK5', 'B2', 630, 'chưa chắc', 'not necessarily'),
(@zh, '不耐烦', 'bú nàifán', 'bunaifan', 'ADJ', 'HSK5', 'B2', 631, 'thiếu kiên nhẫn', 'impatient'),
(@zh, '不要紧', 'bú yàojǐn', 'buyaojin', 'PHRASE', 'HSK5', 'B2', 632, 'không sao', 'no problem'),
(@zh, '财产', 'cáichǎn', 'caichan', 'NOUN', 'HSK5', 'B2', 633, 'tài sản', 'property'),
(@zh, '采访', 'cǎifǎng', 'caifang', 'VERB', 'HSK5', 'B2', 634, 'phỏng vấn', 'to interview'),
(@zh, '彩虹', 'cǎihóng', 'caihong', 'NOUN', 'HSK5', 'B2', 635, 'cầu vồng', 'rainbow'),
(@zh, '操心', 'cāoxīn', 'caoxin', 'VERB', 'HSK5', 'B2', 636, 'lo nghĩ', 'to worry'),
(@zh, '册', 'cè', 'ce', 'NOUN', 'HSK5', 'B2', 637, 'cuốn', 'volume'),
(@zh, '测验', 'cèyàn', 'ceyan', 'NOUN', 'HSK5', 'B2', 638, 'kiểm tra', 'test'),
(@zh, '曾经', 'céngjīng', 'cengjing', 'ADV', 'HSK5', 'B2', 639, 'đã từng', 'once'),
(@zh, '差距', 'chājù', 'chaju', 'NOUN', 'HSK5', 'B2', 640, 'khoảng cách', 'gap'),
(@zh, '插', 'chā', 'cha', 'VERB', 'HSK5', 'B2', 641, 'cắm, chèn', 'to insert'),
(@zh, '产品', 'chǎnpǐn', 'chanpin', 'NOUN', 'HSK5', 'B2', 642, 'sản phẩm', 'product'),
(@zh, '产生', 'chǎnshēng', 'chansheng', 'VERB', 'HSK5', 'B2', 643, 'sản sinh', 'to produce'),
(@zh, '常识', 'chángshí', 'changshi', 'NOUN', 'HSK5', 'B2', 644, 'kiến thức thường thức', 'common sense'),
(@zh, '抄', 'chāo', 'chao', 'VERB', 'HSK5', 'B2', 645, 'sao chép', 'to copy'),
(@zh, '朝', 'cháo', 'chao', 'PARTICLE', 'HSK5', 'B2', 646, 'hướng', 'towards'),
(@zh, '潮湿', 'cháoshī', 'chaoshi', 'ADJ', 'HSK5', 'B2', 647, 'ẩm ướt', 'damp'),
(@zh, '吵', 'chǎo', 'chao', 'ADJ', 'HSK5', 'B2', 648, 'ồn ào', 'noisy'),
(@zh, '车库', 'chēkù', 'cheku', 'NOUN', 'HSK5', 'B2', 649, 'gara xe', 'garage');

-- ========== HSK 6 - Extended (~30 more) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, hsk_level, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@zh, '哀悼', 'āidào', 'aidao', 'VERB', 'HSK6', 'C1', 700, 'thương tiếc', 'to mourn'),
(@zh, '挨', 'āi', 'ai', 'VERB', 'HSK6', 'C1', 701, 'chịu đựng', 'to suffer'),
(@zh, '癌症', 'áizhèng', 'aizheng', 'NOUN', 'HSK6', 'C1', 702, 'ung thư', 'cancer'),
(@zh, '爱戴', 'àidài', 'aidai', 'VERB', 'HSK6', 'C1', 703, 'tôn kính', 'to esteem'),
(@zh, '昂贵', 'ángguì', 'anggui', 'ADJ', 'HSK6', 'C1', 704, 'đắt đỏ', 'expensive'),
(@zh, '凹凸', 'āotū', 'aotu', 'ADJ', 'HSK6', 'C1', 705, 'lồi lõm', 'uneven'),
(@zh, '懊悔', 'àohuǐ', 'aohui', 'VERB', 'HSK6', 'C1', 706, 'hối hận', 'to regret'),
(@zh, '奥秘', 'àomì', 'aomi', 'NOUN', 'HSK6', 'C1', 707, 'bí ẩn', 'mystery'),
(@zh, '巴不得', 'bābude', 'babude', 'VERB', 'HSK6', 'C1', 708, 'mong muốn', 'eager'),
(@zh, '把关', 'bǎguān', 'baguan', 'VERB', 'HSK6', 'C1', 709, 'kiểm soát', 'to check'),
(@zh, '霸道', 'bàdao', 'badao', 'ADJ', 'HSK6', 'C1', 710, 'độc đoán', 'overbearing'),
(@zh, '罢工', 'bàgōng', 'bagong', 'VERB', 'HSK6', 'C1', 711, 'đình công', 'to strike'),
(@zh, '掰', 'bāi', 'bai', 'VERB', 'HSK6', 'C1', 712, 'bẻ ra', 'to break off'),
(@zh, '颁布', 'bānbù', 'banbu', 'VERB', 'HSK6', 'C1', 713, 'ban bố', 'to promulgate'),
(@zh, '颁发', 'bānfā', 'banfa', 'VERB', 'HSK6', 'C1', 714, 'trao tặng', 'to issue'),
(@zh, '斑', 'bān', 'ban', 'NOUN', 'HSK6', 'C1', 715, 'đốm', 'spot'),
(@zh, '版本', 'bǎnběn', 'banben', 'NOUN', 'HSK6', 'C1', 716, 'phiên bản', 'version'),
(@zh, '半途而废', 'bàntú érfèi', 'bantuerfei', 'PHRASE', 'HSK6', 'C1', 717, 'bỏ dở giữa chừng', 'to give up halfway'),
(@zh, '伴侣', 'bànlǚ', 'banlv', 'NOUN', 'HSK6', 'C1', 718, 'bạn đồng hành', 'companion'),
(@zh, '伴随', 'bànsuí', 'bansui', 'VERB', 'HSK6', 'C1', 719, 'kèm theo', 'to accompany'),
(@zh, '榜样', 'bǎngyàng', 'bangyang', 'NOUN', 'HSK6', 'C1', 720, 'tấm gương', 'role model'),
(@zh, '磅', 'bàng', 'bang', 'NOUN', 'HSK6', 'C1', 721, 'pound (cân)', 'pound'),
(@zh, '包庇', 'bāobì', 'baobi', 'VERB', 'HSK6', 'C1', 722, 'bao che', 'to shield'),
(@zh, '包袱', 'bāofú', 'baofu', 'NOUN', 'HSK6', 'C1', 723, 'gánh nặng', 'burden'),
(@zh, '包围', 'bāowéi', 'baowei', 'VERB', 'HSK6', 'C1', 724, 'bao vây', 'to surround'),
(@zh, '保管', 'bǎoguǎn', 'baoguan', 'VERB', 'HSK6', 'C1', 725, 'bảo quản', 'to safeguard'),
(@zh, '保密', 'bǎomì', 'baomi', 'VERB', 'HSK6', 'C1', 726, 'giữ bí mật', 'to keep secret'),
(@zh, '保姆', 'bǎomǔ', 'baomu', 'NOUN', 'HSK6', 'C1', 727, 'bảo mẫu', 'nanny'),
(@zh, '饱和', 'bǎohé', 'baohe', 'ADJ', 'HSK6', 'C1', 728, 'bão hòa', 'saturated'),
(@zh, '饱经沧桑', 'bǎojīng cāngsāng', 'baojing', 'PHRASE', 'HSK6', 'C1', 729, 'từng trải', 'experienced'),
(@zh, '报酬', 'bàochou', 'baochou', 'NOUN', 'HSK6', 'C1', 730, 'tiền thù lao', 'reward');

-- ----- Word examples for Chinese -----
INSERT INTO word_examples (word_id, sentence, reading, translation, level_code, source) VALUES
((SELECT id FROM words WHERE `text`='高兴' AND language_id=@zh LIMIT 1),
 '认识你很高兴。', 'Rènshi nǐ hěn gāoxìng.', 'Rất vui được làm quen với bạn.', 'HSK1', 'tatoeba'),
((SELECT id FROM words WHERE `text`='帮助' AND language_id=@zh LIMIT 1),
 '我会帮助你。', 'Wǒ huì bāngzhù nǐ.', 'Tôi sẽ giúp bạn.', 'HSK2', 'tatoeba'),
((SELECT id FROM words WHERE `text`='参加' AND language_id=@zh LIMIT 1),
 '我想参加这个活动。', 'Wǒ xiǎng cānjiā zhège huódòng.', 'Tôi muốn tham gia hoạt động này.', 'HSK3', 'tatoeba'),
((SELECT id FROM words WHERE `text`='成绩' AND language_id=@zh LIMIT 1),
 '他的成绩很好。', 'Tā de chéngjì hěn hǎo.', 'Thành tích của anh ấy rất tốt.', 'HSK3', 'tatoeba'),
((SELECT id FROM words WHERE `text`='保持' AND language_id=@zh LIMIT 1),
 '请保持安静。', 'Qǐng bǎochí ānjìng.', 'Xin giữ trật tự.', 'HSK5', 'tatoeba'),
((SELECT id FROM words WHERE `text`='产品' AND language_id=@zh LIMIT 1),
 '这家公司的产品很受欢迎。', 'Zhè jiā gōngsī de chǎnpǐn hěn shòu huānyíng.', 'Sản phẩm của công ty này rất được ưa chuộng.', 'HSK5', 'tatoeba'),
((SELECT id FROM words WHERE `text`='伴随' AND language_id=@zh LIMIT 1),
 '幸福伴随着努力。', 'Xìngfú bànsuí zhe nǔlì.', 'Hạnh phúc đi kèm với nỗ lực.', 'HSK6', 'tatoeba');
