-- =====================================================
-- SEED EXT: English vocabulary - Extended for IELTS & TOEIC
-- Sources: Oxford 3000/5000 (CC-BY-NC-SA), CEFR-J wordlist,
--          COCA frequency, BNC corpus, Cambridge English
--          Vocabulary Profile, BarronTOEIC4000 lists.
-- =====================================================

SET NAMES utf8mb4;
SET @en := (SELECT id FROM languages WHERE code='en');

-- ========== Core A2/B1 (CEFR + general TOEIC 400-650) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@en, 'apply', '/əˈplaɪ/', 'apply', 'VERB', 'B1', 400, 'nộp đơn, áp dụng', 'to make a formal request; to use'),
(@en, 'arrange', '/əˈreɪndʒ/', 'arrange', 'VERB', 'B1', 401, 'sắp xếp', 'to put in order'),
(@en, 'attend', '/əˈtend/', 'attend', 'VERB', 'B1', 402, 'tham dự', 'to be present at'),
(@en, 'attract', '/əˈtrækt/', 'attract', 'VERB', 'B1', 403, 'thu hút', 'to make someone interested'),
(@en, 'avoid', '/əˈvɔɪd/', 'avoid', 'VERB', 'B1', 404, 'tránh', 'to keep away from'),
(@en, 'behavior', '/bɪˈheɪvjər/', 'behavior', 'NOUN', 'B1', 405, 'hành vi', 'how someone acts'),
(@en, 'benefit', '/ˈbenɪfɪt/', 'benefit', 'NOUN', 'B1', 406, 'lợi ích', 'an advantage'),
(@en, 'campaign', '/kæmˈpeɪn/', 'campaign', 'NOUN', 'B1', 407, 'chiến dịch', 'organized activities'),
(@en, 'cancel', '/ˈkænsl/', 'cancel', 'VERB', 'B1', 408, 'hủy', 'to call off'),
(@en, 'capacity', '/kəˈpæsəti/', 'capacity', 'NOUN', 'B1', 409, 'sức chứa, năng lực', 'ability to hold'),
(@en, 'category', '/ˈkætəɡɔːri/', 'category', 'NOUN', 'B1', 410, 'thể loại', 'a class of things'),
(@en, 'celebrate', '/ˈselɪbreɪt/', 'celebrate', 'VERB', 'B1', 411, 'kỷ niệm', 'to mark a special day'),
(@en, 'challenge', '/ˈtʃælɪndʒ/', 'challenge', 'NOUN', 'B1', 412, 'thử thách', 'a difficult task'),
(@en, 'characteristic', '/ˌkærəktəˈrɪstɪk/', 'characteristic', 'NOUN', 'B2', 413, 'đặc điểm', 'a typical feature'),
(@en, 'circumstance', '/ˈsɜːrkəmstæns/', 'circumstance', 'NOUN', 'B2', 414, 'hoàn cảnh', 'a condition or fact'),
(@en, 'commit', '/kəˈmɪt/', 'commit', 'VERB', 'B2', 415, 'cam kết, phạm', 'to promise; to do (a crime)'),
(@en, 'community', '/kəˈmjuːnəti/', 'community', 'NOUN', 'B1', 416, 'cộng đồng', 'a group of people'),
(@en, 'compete', '/kəmˈpiːt/', 'compete', 'VERB', 'B1', 417, 'cạnh tranh', 'to try to win'),
(@en, 'complain', '/kəmˈpleɪn/', 'complain', 'VERB', 'B1', 418, 'phàn nàn', 'to express dissatisfaction'),
(@en, 'concept', '/ˈkɑːnsept/', 'concept', 'NOUN', 'B2', 419, 'khái niệm', 'an idea'),
(@en, 'concentrate', '/ˈkɑːnsntreɪt/', 'concentrate', 'VERB', 'B1', 420, 'tập trung', 'to focus thoughts'),
(@en, 'conclude', '/kənˈkluːd/', 'conclude', 'VERB', 'B2', 421, 'kết luận', 'to bring to an end'),
(@en, 'condition', '/kənˈdɪʃn/', 'condition', 'NOUN', 'B1', 422, 'điều kiện', 'a state of being'),
(@en, 'conduct', '/kənˈdʌkt/', 'conduct', 'VERB', 'B2', 423, 'tiến hành', 'to organize and carry out'),
(@en, 'confidence', '/ˈkɑːnfɪdəns/', 'confidence', 'NOUN', 'B1', 424, 'sự tự tin', 'feeling of certainty'),
(@en, 'confirm', '/kənˈfɜːrm/', 'confirm', 'VERB', 'B1', 425, 'xác nhận', 'to make sure'),
(@en, 'conflict', '/ˈkɑːnflɪkt/', 'conflict', 'NOUN', 'B2', 426, 'xung đột', 'serious disagreement'),
(@en, 'connection', '/kəˈnekʃn/', 'connection', 'NOUN', 'B1', 427, 'kết nối', 'a link'),
(@en, 'consequence', '/ˈkɑːnsəkwens/', 'consequence', 'NOUN', 'B2', 428, 'hậu quả', 'a result'),
(@en, 'context', '/ˈkɑːntekst/', 'context', 'NOUN', 'B2', 429, 'ngữ cảnh', 'circumstances around'),
(@en, 'contrast', '/ˈkɑːntræst/', 'contrast', 'NOUN', 'B2', 430, 'tương phản', 'a difference'),
(@en, 'contribute', '/kənˈtrɪbjuːt/', 'contribute', 'VERB', 'B2', 431, 'đóng góp', 'to give to a cause'),
(@en, 'crisis', '/ˈkraɪsɪs/', 'crisis', 'NOUN', 'B2', 432, 'khủng hoảng', 'a difficult situation'),
(@en, 'criticize', '/ˈkrɪtɪsaɪz/', 'criticize', 'VERB', 'B2', 433, 'chỉ trích', 'to disapprove of'),
(@en, 'deal', '/diːl/', 'deal', 'VERB', 'B1', 434, 'giao dịch, đối phó', 'to handle'),
(@en, 'decade', '/ˈdekeɪd/', 'decade', 'NOUN', 'B1', 435, 'thập kỷ', 'ten years'),
(@en, 'decline', '/dɪˈklaɪn/', 'decline', 'VERB', 'B2', 436, 'giảm sút, từ chối', 'to decrease; refuse'),
(@en, 'define', '/dɪˈfaɪn/', 'define', 'VERB', 'B2', 437, 'định nghĩa', 'to state the meaning'),
(@en, 'demand', '/dɪˈmænd/', 'demand', 'NOUN', 'B1', 438, 'nhu cầu', 'a strong request'),
(@en, 'describe', '/dɪˈskraɪb/', 'describe', 'VERB', 'A2', 439, 'mô tả', 'to give details'),
(@en, 'design', '/dɪˈzaɪn/', 'design', 'VERB', 'B1', 440, 'thiết kế', 'to plan and create'),
(@en, 'destroy', '/dɪˈstrɔɪ/', 'destroy', 'VERB', 'B1', 441, 'phá hủy', 'to ruin completely'),
(@en, 'determine', '/dɪˈtɜːrmɪn/', 'determine', 'VERB', 'B2', 442, 'xác định', 'to decide'),
(@en, 'develop', '/dɪˈveləp/', 'develop', 'VERB', 'B1', 443, 'phát triển', 'to grow'),
(@en, 'differ', '/ˈdɪfər/', 'differ', 'VERB', 'B2', 444, 'khác biệt', 'to be unlike'),
(@en, 'distinguish', '/dɪˈstɪŋɡwɪʃ/', 'distinguish', 'VERB', 'B2', 445, 'phân biệt', 'to recognize a difference'),
(@en, 'distribute', '/dɪˈstrɪbjuːt/', 'distribute', 'VERB', 'B2', 446, 'phân phối', 'to give out'),
(@en, 'effect', '/ɪˈfekt/', 'effect', 'NOUN', 'B1', 447, 'hiệu ứng', 'a result'),
(@en, 'effective', '/ɪˈfektɪv/', 'effective', 'ADJ', 'B1', 448, 'hiệu quả', 'producing a result'),
(@en, 'emphasize', '/ˈemfəsaɪz/', 'emphasize', 'VERB', 'B2', 449, 'nhấn mạnh', 'to give importance to'),
(@en, 'encourage', '/ɪnˈkɜːrɪdʒ/', 'encourage', 'VERB', 'B1', 450, 'khuyến khích', 'to give support'),
(@en, 'engage', '/ɪnˈɡeɪdʒ/', 'engage', 'VERB', 'B2', 451, 'tham gia', 'to involve oneself'),
(@en, 'enhance', '/ɪnˈhæns/', 'enhance', 'VERB', 'B2', 452, 'nâng cao', 'to improve quality'),
(@en, 'ensure', '/ɪnˈʃʊr/', 'ensure', 'VERB', 'B2', 453, 'đảm bảo', 'to make certain'),
(@en, 'estimate', '/ˈestɪmeɪt/', 'estimate', 'VERB', 'B2', 454, 'ước tính', 'to give approximate value'),
(@en, 'exhibit', '/ɪɡˈzɪbɪt/', 'exhibit', 'VERB', 'B2', 455, 'trưng bày', 'to display'),
(@en, 'extend', '/ɪkˈstend/', 'extend', 'VERB', 'B2', 456, 'mở rộng, kéo dài', 'to make longer'),
(@en, 'fascinate', '/ˈfæsɪneɪt/', 'fascinate', 'VERB', 'B2', 457, 'mê hoặc', 'to attract strongly'),
(@en, 'feature', '/ˈfiːtʃər/', 'feature', 'NOUN', 'B1', 458, 'đặc điểm', 'an important part'),
(@en, 'finance', '/ˈfaɪnæns/', 'finance', 'NOUN', 'B1', 459, 'tài chính', 'money management'),
(@en, 'function', '/ˈfʌŋkʃn/', 'function', 'NOUN', 'B1', 460, 'chức năng', 'a purpose'),
(@en, 'generate', '/ˈdʒenəreɪt/', 'generate', 'VERB', 'B2', 461, 'tạo ra', 'to produce'),
(@en, 'globalization', '/ˌɡloʊbələˈzeɪʃn/', 'globalization', 'NOUN', 'C1', 462, 'toàn cầu hóa', 'worldwide integration'),
(@en, 'guarantee', '/ˌɡærənˈtiː/', 'guarantee', 'VERB', 'B2', 463, 'bảo đảm', 'to give a promise'),
(@en, 'identify', '/aɪˈdentɪfaɪ/', 'identify', 'VERB', 'B1', 464, 'nhận diện', 'to recognize'),
(@en, 'illustrate', '/ˈɪləstreɪt/', 'illustrate', 'VERB', 'B2', 465, 'minh họa', 'to show by example'),
(@en, 'impact', '/ˈɪmpækt/', 'impact', 'NOUN', 'B2', 466, 'tác động', 'a strong effect'),
(@en, 'indicate', '/ˈɪndɪkeɪt/', 'indicate', 'VERB', 'B2', 467, 'chỉ ra', 'to show'),
(@en, 'influence', '/ˈɪnfluəns/', 'influence', 'NOUN', 'B1', 468, 'ảnh hưởng', 'the power to affect'),
(@en, 'innovate', '/ˈɪnəveɪt/', 'innovate', 'VERB', 'B2', 469, 'đổi mới', 'to create new ideas'),
(@en, 'inspire', '/ɪnˈspaɪər/', 'inspire', 'VERB', 'B2', 470, 'truyền cảm hứng', 'to motivate'),
(@en, 'interact', '/ˌɪntərˈækt/', 'interact', 'VERB', 'B2', 471, 'tương tác', 'to communicate with'),
(@en, 'interpret', '/ɪnˈtɜːrprət/', 'interpret', 'VERB', 'B2', 472, 'giải thích, phiên dịch', 'to translate or explain'),
(@en, 'investigate', '/ɪnˈvestɪɡeɪt/', 'investigate', 'VERB', 'B2', 473, 'điều tra', 'to examine carefully'),
(@en, 'involve', '/ɪnˈvɑːlv/', 'involve', 'VERB', 'B2', 474, 'liên quan', 'to include'),
(@en, 'judge', '/dʒʌdʒ/', 'judge', 'VERB', 'B1', 475, 'phán xét', 'to form an opinion'),
(@en, 'justify', '/ˈdʒʌstɪfaɪ/', 'justify', 'VERB', 'B2', 476, 'biện minh', 'to give a reason'),
(@en, 'launch', '/lɔːntʃ/', 'launch', 'VERB', 'B2', 477, 'ra mắt', 'to start something new'),
(@en, 'link', '/lɪŋk/', 'link', 'NOUN', 'B1', 478, 'liên kết', 'a connection'),
(@en, 'manage', '/ˈmænɪdʒ/', 'manage', 'VERB', 'B1', 479, 'quản lý', 'to be in charge'),
(@en, 'maximize', '/ˈmæksɪmaɪz/', 'maximize', 'VERB', 'B2', 480, 'tối đa hóa', 'to make as great as possible'),
(@en, 'monitor', '/ˈmɑːnɪtər/', 'monitor', 'VERB', 'B2', 481, 'giám sát', 'to watch over'),
(@en, 'motivate', '/ˈmoʊtɪveɪt/', 'motivate', 'VERB', 'B2', 482, 'thúc đẩy', 'to inspire'),
(@en, 'observe', '/əbˈzɜːrv/', 'observe', 'VERB', 'B2', 483, 'quan sát', 'to watch carefully'),
(@en, 'occur', '/əˈkɜːr/', 'occur', 'VERB', 'B2', 484, 'xảy ra', 'to happen'),
(@en, 'overcome', '/ˌoʊvərˈkʌm/', 'overcome', 'VERB', 'B2', 485, 'vượt qua', 'to defeat'),
(@en, 'participate', '/pɑːrˈtɪsɪpeɪt/', 'participate', 'VERB', 'B1', 486, 'tham gia', 'to take part'),
(@en, 'persuade', '/pərˈsweɪd/', 'persuade', 'VERB', 'B2', 487, 'thuyết phục', 'to convince'),
(@en, 'predict', '/prɪˈdɪkt/', 'predict', 'VERB', 'B2', 488, 'dự đoán', 'to say in advance'),
(@en, 'preserve', '/prɪˈzɜːrv/', 'preserve', 'VERB', 'B2', 489, 'bảo tồn', 'to keep safe'),
(@en, 'prevent', '/prɪˈvent/', 'prevent', 'VERB', 'B1', 490, 'ngăn chặn', 'to stop from happening'),
(@en, 'process', '/ˈprɑːses/', 'process', 'NOUN', 'B1', 491, 'quá trình', 'a series of actions'),
(@en, 'produce', '/prəˈduːs/', 'produce', 'VERB', 'B1', 492, 'sản xuất', 'to make'),
(@en, 'protect', '/prəˈtekt/', 'protect', 'VERB', 'B1', 493, 'bảo vệ', 'to keep safe'),
(@en, 'provide', '/prəˈvaɪd/', 'provide', 'VERB', 'B1', 494, 'cung cấp', 'to make available'),
(@en, 'purchase', '/ˈpɜːrtʃəs/', 'purchase', 'VERB', 'B2', 495, 'mua', 'to buy'),
(@en, 'reduce', '/rɪˈduːs/', 'reduce', 'VERB', 'B1', 496, 'giảm', 'to make smaller'),
(@en, 'reflect', '/rɪˈflekt/', 'reflect', 'VERB', 'B2', 497, 'phản ánh', 'to show; to think about'),
(@en, 'reform', '/rɪˈfɔːrm/', 'reform', 'NOUN', 'B2', 498, 'cải cách', 'a change for improvement'),
(@en, 'regard', '/rɪˈɡɑːrd/', 'regard', 'VERB', 'B2', 499, 'coi như', 'to consider'),
(@en, 'register', '/ˈredʒɪstər/', 'register', 'VERB', 'B1', 500, 'đăng ký', 'to enroll formally');

-- ========== TOEIC Business - Extended ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@en, 'accommodate', '/əˈkɑːmədeɪt/', 'accommodate', 'VERB', 'B2', 700, 'sắp xếp chỗ', 'to provide room for'),
(@en, 'agreement', '/əˈɡriːmənt/', 'agreement', 'NOUN', 'B1', 701, 'thỏa thuận', 'an arrangement'),
(@en, 'amend', '/əˈmend/', 'amend', 'VERB', 'B2', 702, 'sửa đổi', 'to make corrections'),
(@en, 'appoint', '/əˈpɔɪnt/', 'appoint', 'VERB', 'B2', 703, 'bổ nhiệm', 'to choose for a position'),
(@en, 'approve', '/əˈpruːv/', 'approve', 'VERB', 'B1', 704, 'phê duyệt', 'to officially accept'),
(@en, 'asset', '/ˈæset/', 'asset', 'NOUN', 'B2', 705, 'tài sản', 'something valuable'),
(@en, 'assign', '/əˈsaɪn/', 'assign', 'VERB', 'B2', 706, 'giao nhiệm vụ', 'to give a task'),
(@en, 'authorize', '/ˈɔːθəraɪz/', 'authorize', 'VERB', 'B2', 707, 'ủy quyền', 'to give permission'),
(@en, 'bid', '/bɪd/', 'bid', 'VERB', 'B2', 708, 'đấu thầu', 'to offer a price'),
(@en, 'branch', '/bræntʃ/', 'branch', 'NOUN', 'B1', 709, 'chi nhánh', 'a local office'),
(@en, 'brochure', '/broʊˈʃʊr/', 'brochure', 'NOUN', 'B1', 710, 'tờ rơi', 'a small magazine'),
(@en, 'cargo', '/ˈkɑːrɡoʊ/', 'cargo', 'NOUN', 'B2', 711, 'hàng hóa', 'goods carried'),
(@en, 'client', '/ˈklaɪənt/', 'client', 'NOUN', 'B1', 712, 'khách hàng', 'a customer'),
(@en, 'commission', '/kəˈmɪʃn/', 'commission', 'NOUN', 'B2', 713, 'hoa hồng', 'a fee paid'),
(@en, 'complaint', '/kəmˈpleɪnt/', 'complaint', 'NOUN', 'B1', 714, 'lời phàn nàn', 'expression of unhappiness'),
(@en, 'consult', '/kənˈsʌlt/', 'consult', 'VERB', 'B2', 715, 'tham vấn', 'to seek advice'),
(@en, 'contract', '/ˈkɑːntrækt/', 'contract', 'NOUN', 'B1', 716, 'hợp đồng', 'a written agreement'),
(@en, 'conference', '/ˈkɑːnfərəns/', 'conference', 'NOUN', 'B1', 717, 'hội nghị', 'a formal meeting'),
(@en, 'corporate', '/ˈkɔːrpərət/', 'corporate', 'ADJ', 'B2', 718, 'thuộc công ty', 'relating to a corporation'),
(@en, 'customer', '/ˈkʌstəmər/', 'customer', 'NOUN', 'A2', 719, 'khách hàng', 'a buyer'),
(@en, 'deduct', '/dɪˈdʌkt/', 'deduct', 'VERB', 'B2', 720, 'khấu trừ', 'to subtract'),
(@en, 'delivery', '/dɪˈlɪvəri/', 'delivery', 'NOUN', 'B1', 721, 'giao hàng', 'the act of bringing'),
(@en, 'department', '/dɪˈpɑːrtmənt/', 'department', 'NOUN', 'A2', 722, 'phòng ban', 'a section of an organization'),
(@en, 'discount', '/ˈdɪskaʊnt/', 'discount', 'NOUN', 'B1', 723, 'giảm giá', 'a price reduction'),
(@en, 'distribute', '/dɪˈstrɪbjuːt/', 'distribute', 'VERB', 'B2', 724, 'phân phối', 'to give to several'),
(@en, 'efficient', '/ɪˈfɪʃnt/', 'efficient', 'ADJ', 'B2', 725, 'hiệu quả', 'doing things well'),
(@en, 'employment', '/ɪmˈplɔɪmənt/', 'employment', 'NOUN', 'B1', 726, 'việc làm', 'paid work'),
(@en, 'enterprise', '/ˈentərpraɪz/', 'enterprise', 'NOUN', 'B2', 727, 'doanh nghiệp', 'a business or company'),
(@en, 'estimate', '/ˈestɪmət/', 'estimate', 'NOUN', 'B2', 728, 'ước tính', 'an approximate calculation'),
(@en, 'expand', '/ɪkˈspænd/', 'expand', 'VERB', 'B2', 729, 'mở rộng', 'to make larger'),
(@en, 'expense', '/ɪkˈspens/', 'expense', 'NOUN', 'B1', 730, 'chi phí', 'cost or fee'),
(@en, 'expertise', '/ˌekspɜːrˈtiːz/', 'expertise', 'NOUN', 'B2', 731, 'chuyên môn', 'expert skill'),
(@en, 'export', '/ˈekspɔːrt/', 'export', 'VERB', 'B1', 732, 'xuất khẩu', 'to send goods abroad'),
(@en, 'feasibility', '/ˌfiːzəˈbɪləti/', 'feasibility', 'NOUN', 'C1', 733, 'tính khả thi', 'practicality'),
(@en, 'fiscal', '/ˈfɪskl/', 'fiscal', 'ADJ', 'B2', 734, 'tài khóa', 'relating to money'),
(@en, 'forecast', '/ˈfɔːrkæst/', 'forecast', 'NOUN', 'B2', 735, 'dự báo', 'a prediction'),
(@en, 'headquarters', '/ˈhedkwɔːrtərz/', 'headquarters', 'NOUN', 'B2', 736, 'trụ sở chính', 'main office'),
(@en, 'import', '/ˈɪmpɔːrt/', 'import', 'VERB', 'B1', 737, 'nhập khẩu', 'to bring in goods'),
(@en, 'incentive', '/ɪnˈsentɪv/', 'incentive', 'NOUN', 'B2', 738, 'động lực', 'a thing that motivates'),
(@en, 'industry', '/ˈɪndəstri/', 'industry', 'NOUN', 'A2', 739, 'ngành công nghiệp', 'a type of business'),
(@en, 'inspect', '/ɪnˈspekt/', 'inspect', 'VERB', 'B2', 740, 'kiểm tra', 'to examine officially'),
(@en, 'inventory', '/ˈɪnvəntɔːri/', 'inventory', 'NOUN', 'B2', 741, 'hàng tồn kho', 'goods in stock'),
(@en, 'invest', '/ɪnˈvest/', 'invest', 'VERB', 'B1', 742, 'đầu tư', 'to put money in'),
(@en, 'lease', '/liːs/', 'lease', 'NOUN', 'B2', 743, 'hợp đồng thuê', 'a rental contract'),
(@en, 'manufacture', '/ˌmænjuˈfæktʃər/', 'manufacture', 'VERB', 'B2', 744, 'sản xuất', 'to make on a large scale'),
(@en, 'merchant', '/ˈmɜːrtʃənt/', 'merchant', 'NOUN', 'B2', 745, 'thương nhân', 'a trader'),
(@en, 'minutes', '/ˈmɪnɪts/', 'minutes', 'NOUN', 'B2', 746, 'biên bản', 'official notes of a meeting'),
(@en, 'negotiate', '/nɪˈɡoʊʃieɪt/', 'negotiate', 'VERB', 'B2', 747, 'đàm phán', 'to discuss to reach agreement'),
(@en, 'overtime', '/ˈoʊvərtaɪm/', 'overtime', 'NOUN', 'B1', 748, 'làm thêm giờ', 'extra working hours'),
(@en, 'partnership', '/ˈpɑːrtnərʃɪp/', 'partnership', 'NOUN', 'B2', 749, 'sự hợp tác', 'business association'),
(@en, 'premium', '/ˈpriːmiəm/', 'premium', 'NOUN', 'B2', 750, 'phí bảo hiểm', 'an insurance fee'),
(@en, 'productivity', '/ˌprɑːdʌkˈtɪvəti/', 'productivity', 'NOUN', 'B2', 751, 'năng suất', 'rate of production'),
(@en, 'prospect', '/ˈprɑːspekt/', 'prospect', 'NOUN', 'B2', 752, 'triển vọng', 'a possibility'),
(@en, 'quote', '/kwoʊt/', 'quote', 'VERB', 'B2', 753, 'báo giá', 'to give a price'),
(@en, 'recession', '/rɪˈseʃn/', 'recession', 'NOUN', 'B2', 754, 'suy thoái', 'economic decline'),
(@en, 'redundant', '/rɪˈdʌndənt/', 'redundant', 'ADJ', 'B2', 755, 'thừa, dôi dư', 'unnecessary'),
(@en, 'refund', '/ˈriːfʌnd/', 'refund', 'NOUN', 'B1', 756, 'hoàn tiền', 'money returned'),
(@en, 'retail', '/ˈriːteɪl/', 'retail', 'NOUN', 'B2', 757, 'bán lẻ', 'sale to consumers'),
(@en, 'subsidize', '/ˈsʌbsɪdaɪz/', 'subsidize', 'VERB', 'C1', 758, 'trợ cấp', 'to support financially'),
(@en, 'turnover', '/ˈtɜːrnoʊvər/', 'turnover', 'NOUN', 'B2', 759, 'doanh thu', 'sales total');

-- ========== IELTS Academic - Extended (B2-C2) ==========
INSERT INTO words (language_id, `text`, reading, romaji, pos, cefr_level, frequency_rank, meaning_vi, meaning_en) VALUES
(@en, 'abundant', '/əˈbʌndənt/', 'abundant', 'ADJ', 'C1', 800, 'phong phú', 'plentiful'),
(@en, 'adverse', '/ˈædvɜːrs/', 'adverse', 'ADJ', 'C1', 801, 'bất lợi', 'harmful'),
(@en, 'aesthetic', '/esˈθetɪk/', 'aesthetic', 'ADJ', 'C1', 802, 'thẩm mỹ', 'concerned with beauty'),
(@en, 'aggravate', '/ˈæɡrəveɪt/', 'aggravate', 'VERB', 'C1', 803, 'làm trầm trọng', 'to make worse'),
(@en, 'allege', '/əˈledʒ/', 'allege', 'VERB', 'C1', 804, 'cáo buộc', 'to claim without proof'),
(@en, 'ambiguous', '/æmˈbɪɡjuəs/', 'ambiguous', 'ADJ', 'C1', 805, 'mơ hồ', 'unclear'),
(@en, 'amplify', '/ˈæmplɪfaɪ/', 'amplify', 'VERB', 'C1', 806, 'khuếch đại', 'to make louder/larger'),
(@en, 'analogous', '/əˈnæləɡəs/', 'analogous', 'ADJ', 'C1', 807, 'tương tự', 'similar'),
(@en, 'anticipate', '/ænˈtɪsɪpeɪt/', 'anticipate', 'VERB', 'B2', 808, 'dự đoán', 'to expect'),
(@en, 'apparent', '/əˈpærənt/', 'apparent', 'ADJ', 'B2', 809, 'rõ ràng', 'clearly visible'),
(@en, 'articulate', '/ɑːrˈtɪkjuleɪt/', 'articulate', 'VERB', 'C1', 810, 'diễn đạt rõ', 'to express clearly'),
(@en, 'ascertain', '/ˌæsərˈteɪn/', 'ascertain', 'VERB', 'C1', 811, 'xác định', 'to find out for certain'),
(@en, 'assert', '/əˈsɜːrt/', 'assert', 'VERB', 'C1', 812, 'khẳng định', 'to state firmly'),
(@en, 'attain', '/əˈteɪn/', 'attain', 'VERB', 'C1', 813, 'đạt được', 'to achieve'),
(@en, 'attribute', '/əˈtrɪbjuːt/', 'attribute', 'VERB', 'C1', 814, 'quy cho', 'to ascribe to'),
(@en, 'augment', '/ɔːɡˈment/', 'augment', 'VERB', 'C1', 815, 'tăng cường', 'to add to'),
(@en, 'authentic', '/ɔːˈθentɪk/', 'authentic', 'ADJ', 'B2', 816, 'xác thực', 'genuine'),
(@en, 'autonomous', '/ɔːˈtɑːnəməs/', 'autonomous', 'ADJ', 'C1', 817, 'tự trị', 'self-governing'),
(@en, 'beneficial', '/ˌbenɪˈfɪʃl/', 'beneficial', 'ADJ', 'B2', 818, 'có lợi', 'helpful'),
(@en, 'biased', '/ˈbaɪəst/', 'biased', 'ADJ', 'C1', 819, 'thiên vị', 'unfairly preferring'),
(@en, 'breakthrough', '/ˈbreɪkθruː/', 'breakthrough', 'NOUN', 'C1', 820, 'bước đột phá', 'an important advance'),
(@en, 'catalyst', '/ˈkætəlɪst/', 'catalyst', 'NOUN', 'C1', 821, 'chất xúc tác', 'something causing change'),
(@en, 'cease', '/siːs/', 'cease', 'VERB', 'C1', 822, 'ngừng', 'to stop'),
(@en, 'coherent', '/koʊˈhɪrənt/', 'coherent', 'ADJ', 'C1', 823, 'mạch lạc', 'logically connected'),
(@en, 'commodity', '/kəˈmɑːdəti/', 'commodity', 'NOUN', 'C1', 824, 'hàng hóa', 'a tradable item'),
(@en, 'comprise', '/kəmˈpraɪz/', 'comprise', 'VERB', 'C1', 825, 'bao gồm', 'to consist of'),
(@en, 'conceive', '/kənˈsiːv/', 'conceive', 'VERB', 'C1', 826, 'thai nghén', 'to form an idea'),
(@en, 'concise', '/kənˈsaɪs/', 'concise', 'ADJ', 'C1', 827, 'súc tích', 'brief and clear'),
(@en, 'confine', '/kənˈfaɪn/', 'confine', 'VERB', 'C1', 828, 'giới hạn', 'to restrict'),
(@en, 'consecutive', '/kənˈsekjətɪv/', 'consecutive', 'ADJ', 'C1', 829, 'liên tiếp', 'following one after another'),
(@en, 'conspicuous', '/kənˈspɪkjuəs/', 'conspicuous', 'ADJ', 'C1', 830, 'dễ nhận thấy', 'easily seen'),
(@en, 'contradict', '/ˌkɑːntrəˈdɪkt/', 'contradict', 'VERB', 'C1', 831, 'mâu thuẫn', 'to assert the opposite'),
(@en, 'conventional', '/kənˈvenʃənl/', 'conventional', 'ADJ', 'B2', 832, 'thông thường', 'traditional'),
(@en, 'crucial', '/ˈkruːʃl/', 'crucial', 'ADJ', 'B2', 833, 'quan trọng', 'extremely important'),
(@en, 'cumulative', '/ˈkjuːmjələtɪv/', 'cumulative', 'ADJ', 'C1', 834, 'tích lũy', 'increasing by additions'),
(@en, 'deteriorate', '/dɪˈtɪriəreɪt/', 'deteriorate', 'VERB', 'C1', 835, 'xấu đi', 'to become worse'),
(@en, 'devastate', '/ˈdevəsteɪt/', 'devastate', 'VERB', 'C1', 836, 'tàn phá', 'to destroy completely'),
(@en, 'diminish', '/dɪˈmɪnɪʃ/', 'diminish', 'VERB', 'C1', 837, 'giảm bớt', 'to make smaller'),
(@en, 'discern', '/dɪˈsɜːrn/', 'discern', 'VERB', 'C1', 838, 'nhận thấy', 'to perceive'),
(@en, 'disparate', '/ˈdɪspərət/', 'disparate', 'ADJ', 'C1', 839, 'khác nhau', 'different in kind'),
(@en, 'diverse', '/daɪˈvɜːrs/', 'diverse', 'ADJ', 'B2', 840, 'đa dạng', 'varied'),
(@en, 'dynamic', '/daɪˈnæmɪk/', 'dynamic', 'ADJ', 'B2', 841, 'năng động', 'full of energy'),
(@en, 'eloquent', '/ˈeləkwənt/', 'eloquent', 'ADJ', 'C1', 842, 'hùng hồn', 'expressing well'),
(@en, 'empirical', '/ɪmˈpɪrɪkl/', 'empirical', 'ADJ', 'C1', 843, 'thực nghiệm', 'based on observation'),
(@en, 'endorse', '/ɪnˈdɔːrs/', 'endorse', 'VERB', 'C1', 844, 'tán thành', 'to publicly support'),
(@en, 'equate', '/ɪˈkweɪt/', 'equate', 'VERB', 'C1', 845, 'đánh đồng', 'to consider equal'),
(@en, 'evoke', '/ɪˈvoʊk/', 'evoke', 'VERB', 'C1', 846, 'gợi lên', 'to bring to mind'),
(@en, 'exacerbate', '/ɪɡˈzæsərbeɪt/', 'exacerbate', 'VERB', 'C2', 847, 'làm trầm trọng', 'to make worse'),
(@en, 'exhaust', '/ɪɡˈzɔːst/', 'exhaust', 'VERB', 'B2', 848, 'làm kiệt sức', 'to use up completely'),
(@en, 'expedite', '/ˈekspədaɪt/', 'expedite', 'VERB', 'C1', 849, 'đẩy nhanh', 'to make happen sooner'),
(@en, 'explicit', '/ɪkˈsplɪsɪt/', 'explicit', 'ADJ', 'C1', 850, 'rõ ràng', 'clearly stated'),
(@en, 'fluctuate', '/ˈflʌktʃueɪt/', 'fluctuate', 'VERB', 'C1', 851, 'biến động', 'to vary irregularly'),
(@en, 'foster', '/ˈfɔːstər/', 'foster', 'VERB', 'C1', 852, 'nuôi dưỡng', 'to encourage development'),
(@en, 'fundamental', '/ˌfʌndəˈmentl/', 'fundamental', 'ADJ', 'B2', 853, 'cơ bản', 'forming a base'),
(@en, 'galvanize', '/ˈɡælvənaɪz/', 'galvanize', 'VERB', 'C2', 854, 'kích thích', 'to shock into action'),
(@en, 'hierarchy', '/ˈhaɪərɑːrki/', 'hierarchy', 'NOUN', 'C1', 855, 'thứ bậc', 'a system of ranks'),
(@en, 'imminent', '/ˈɪmɪnənt/', 'imminent', 'ADJ', 'C1', 856, 'sắp xảy ra', 'about to happen'),
(@en, 'impede', '/ɪmˈpiːd/', 'impede', 'VERB', 'C1', 857, 'cản trở', 'to delay progress'),
(@en, 'implicit', '/ɪmˈplɪsɪt/', 'implicit', 'ADJ', 'C1', 858, 'ngầm hiểu', 'suggested but not stated'),
(@en, 'incline', '/ɪnˈklaɪn/', 'incline', 'VERB', 'C1', 859, 'có khuynh hướng', 'to be willing'),
(@en, 'incorporate', '/ɪnˈkɔːrpəreɪt/', 'incorporate', 'VERB', 'B2', 860, 'kết hợp', 'to include'),
(@en, 'indispensable', '/ˌɪndɪˈspensəbl/', 'indispensable', 'ADJ', 'C1', 861, 'không thể thiếu', 'absolutely necessary'),
(@en, 'inevitable', '/ɪnˈevɪtəbl/', 'inevitable', 'ADJ', 'B2', 862, 'không tránh khỏi', 'certain to happen'),
(@en, 'innate', '/ɪˈneɪt/', 'innate', 'ADJ', 'C1', 863, 'bẩm sinh', 'inborn'),
(@en, 'insightful', '/ˈɪnsaɪtfl/', 'insightful', 'ADJ', 'C1', 864, 'sâu sắc', 'showing deep understanding'),
(@en, 'integral', '/ˈɪntɪɡrəl/', 'integral', 'ADJ', 'C1', 865, 'không thể thiếu', 'essential'),
(@en, 'intricate', '/ˈɪntrɪkət/', 'intricate', 'ADJ', 'C1', 866, 'phức tạp', 'very detailed'),
(@en, 'lucrative', '/ˈluːkrətɪv/', 'lucrative', 'ADJ', 'C1', 867, 'sinh lời cao', 'profitable'),
(@en, 'manifest', '/ˈmænɪfest/', 'manifest', 'VERB', 'C1', 868, 'biểu lộ', 'to show clearly'),
(@en, 'marginal', '/ˈmɑːrdʒɪnl/', 'marginal', 'ADJ', 'C1', 869, 'không đáng kể', 'small in significance'),
(@en, 'meticulous', '/məˈtɪkjələs/', 'meticulous', 'ADJ', 'C1', 870, 'tỉ mỉ', 'very careful'),
(@en, 'notable', '/ˈnoʊtəbl/', 'notable', 'ADJ', 'B2', 871, 'đáng chú ý', 'worth noticing'),
(@en, 'notwithstanding', '/ˌnɑːtwɪθˈstændɪŋ/', 'notwithstanding', 'PARTICLE', 'C1', 872, 'mặc dù', 'in spite of'),
(@en, 'nuance', '/ˈnuːɑːns/', 'nuance', 'NOUN', 'C1', 873, 'sắc thái', 'a subtle difference'),
(@en, 'obscure', '/əbˈskjʊr/', 'obscure', 'ADJ', 'C1', 874, 'mơ hồ', 'unclear'),
(@en, 'omit', '/oʊˈmɪt/', 'omit', 'VERB', 'B2', 875, 'bỏ qua', 'to leave out'),
(@en, 'paramount', '/ˈpærəmaʊnt/', 'paramount', 'ADJ', 'C1', 876, 'tối quan trọng', 'most important'),
(@en, 'pivotal', '/ˈpɪvətl/', 'pivotal', 'ADJ', 'C1', 877, 'then chốt', 'central; crucial'),
(@en, 'plausible', '/ˈplɔːzəbl/', 'plausible', 'ADJ', 'C1', 878, 'có thể tin được', 'seeming reasonable'),
(@en, 'plummet', '/ˈplʌmɪt/', 'plummet', 'VERB', 'C1', 879, 'rơi mạnh', 'to fall steeply'),
(@en, 'prevalent', '/ˈprevələnt/', 'prevalent', 'ADJ', 'C1', 880, 'phổ biến', 'widespread'),
(@en, 'proliferate', '/prəˈlɪfəreɪt/', 'proliferate', 'VERB', 'C2', 881, 'sinh sôi', 'to increase rapidly'),
(@en, 'prone', '/proʊn/', 'prone', 'ADJ', 'C1', 882, 'có khuynh hướng', 'likely to do'),
(@en, 'prospective', '/prəˈspektɪv/', 'prospective', 'ADJ', 'B2', 883, 'tương lai', 'expected'),
(@en, 'rampant', '/ˈræmpənt/', 'rampant', 'ADJ', 'C2', 884, 'tràn lan', 'unrestrained'),
(@en, 'rationale', '/ˌræʃəˈnæl/', 'rationale', 'NOUN', 'C1', 885, 'lý lẽ', 'underlying reason'),
(@en, 'reluctant', '/rɪˈlʌktənt/', 'reluctant', 'ADJ', 'B2', 886, 'miễn cưỡng', 'unwilling'),
(@en, 'render', '/ˈrendər/', 'render', 'VERB', 'C1', 887, 'làm cho', 'to cause to be'),
(@en, 'resilient', '/rɪˈzɪliənt/', 'resilient', 'ADJ', 'C1', 888, 'kiên cường', 'able to recover'),
(@en, 'respective', '/rɪˈspektɪv/', 'respective', 'ADJ', 'C1', 889, 'tương ứng', 'each corresponding'),
(@en, 'scrutiny', '/ˈskruːtəni/', 'scrutiny', 'NOUN', 'C1', 890, 'sự xem xét kỹ', 'careful examination'),
(@en, 'staggering', '/ˈstæɡərɪŋ/', 'staggering', 'ADJ', 'C1', 891, 'đáng kinh ngạc', 'astonishing'),
(@en, 'stagnant', '/ˈstæɡnənt/', 'stagnant', 'ADJ', 'C1', 892, 'trì trệ', 'not flowing'),
(@en, 'subjective', '/səbˈdʒektɪv/', 'subjective', 'ADJ', 'C1', 893, 'chủ quan', 'based on personal opinion'),
(@en, 'substantial', '/səbˈstænʃl/', 'substantial', 'ADJ', 'B2', 894, 'đáng kể', 'considerable'),
(@en, 'succinct', '/səkˈsɪŋkt/', 'succinct', 'ADJ', 'C1', 895, 'ngắn gọn', 'briefly clear'),
(@en, 'tangible', '/ˈtændʒəbl/', 'tangible', 'ADJ', 'C1', 896, 'hữu hình', 'real and concrete'),
(@en, 'tedious', '/ˈtiːdiəs/', 'tedious', 'ADJ', 'C1', 897, 'tẻ nhạt', 'boring'),
(@en, 'tentative', '/ˈtentətɪv/', 'tentative', 'ADJ', 'C1', 898, 'tạm thời', 'not certain'),
(@en, 'thrive', '/θraɪv/', 'thrive', 'VERB', 'C1', 899, 'phát đạt', 'to grow vigorously'),
(@en, 'underlying', '/ˌʌndərˈlaɪɪŋ/', 'underlying', 'ADJ', 'C1', 900, 'tiềm ẩn', 'fundamental'),
(@en, 'undertake', '/ˌʌndərˈteɪk/', 'undertake', 'VERB', 'C1', 901, 'đảm nhận', 'to commit to do'),
(@en, 'utilize', '/ˈjuːtəlaɪz/', 'utilize', 'VERB', 'B2', 902, 'sử dụng', 'to make use of'),
(@en, 'versatile', '/ˈvɜːrsətl/', 'versatile', 'ADJ', 'C1', 903, 'đa năng', 'able to do many things'),
(@en, 'viable', '/ˈvaɪəbl/', 'viable', 'ADJ', 'C1', 904, 'khả thi', 'capable of working'),
(@en, 'vigilant', '/ˈvɪdʒɪlənt/', 'vigilant', 'ADJ', 'C1', 905, 'cảnh giác', 'watchfully alert'),
(@en, 'volatile', '/ˈvɑːlətl/', 'volatile', 'ADJ', 'C1', 906, 'biến động', 'changing rapidly');

-- ----- English example sentences (Tatoeba/curated) -----
INSERT INTO word_examples (word_id, sentence, reading, translation, level_code, source) VALUES
((SELECT id FROM words WHERE `text`='apply' AND language_id=@en LIMIT 1),
 'I will apply for the scholarship next month.', NULL, 'Tôi sẽ nộp đơn xin học bổng vào tháng tới.', 'B1', 'tatoeba'),
((SELECT id FROM words WHERE `text`='challenge' AND language_id=@en LIMIT 1),
 'Climate change is the biggest challenge of our time.', NULL, 'Biến đổi khí hậu là thách thức lớn nhất của thời đại chúng ta.', 'IELTS', 'curated'),
((SELECT id FROM words WHERE `text`='contract' AND language_id=@en LIMIT 1),
 'Please review the contract before signing.', NULL, 'Vui lòng xem xét hợp đồng trước khi ký.', 'TOEIC', 'curated'),
((SELECT id FROM words WHERE `text`='inventory' AND language_id=@en LIMIT 1),
 'Our inventory is running low this quarter.', NULL, 'Hàng tồn kho của chúng ta đang sắp hết trong quý này.', 'TOEIC', 'curated'),
((SELECT id FROM words WHERE `text`='ambiguous' AND language_id=@en LIMIT 1),
 'The instructions were ambiguous and confusing.', NULL, 'Hướng dẫn mơ hồ và gây nhầm lẫn.', 'IELTS', 'curated'),
((SELECT id FROM words WHERE `text`='exacerbate' AND language_id=@en LIMIT 1),
 'Stress can exacerbate health problems.', NULL, 'Căng thẳng có thể làm trầm trọng thêm các vấn đề sức khỏe.', 'IELTS', 'curated'),
((SELECT id FROM words WHERE `text`='thrive' AND language_id=@en LIMIT 1),
 'Children thrive in a supportive environment.', NULL, 'Trẻ em phát triển mạnh trong môi trường hỗ trợ.', 'IELTS', 'curated'),
((SELECT id FROM words WHERE `text`='negotiate' AND language_id=@en LIMIT 1),
 'We need to negotiate a better deal with our supplier.', NULL, 'Chúng ta cần đàm phán một thỏa thuận tốt hơn với nhà cung cấp.', 'TOEIC', 'curated'),
((SELECT id FROM words WHERE `text`='turnover' AND language_id=@en LIMIT 1),
 'The company reported a turnover of $5 million last year.', NULL, 'Công ty báo cáo doanh thu 5 triệu USD năm ngoái.', 'TOEIC', 'curated'),
((SELECT id FROM words WHERE `text`='breakthrough' AND language_id=@en LIMIT 1),
 'Scientists made a major breakthrough in cancer research.', NULL, 'Các nhà khoa học đã có bước đột phá lớn trong nghiên cứu ung thư.', 'IELTS', 'curated');
